### ISSUE TITLE
Avoid Ruby methods AST cache purge

### ISSUE THREAD

**Issue by ixti** [google/google-api-ruby-client#102]
At the moment each new client nukes Ruby's internal methods cache, due to singleton class modifications upon API resource builids:

``` ruby
metaclass = (class << self; self; end)
  self.discovered_resources.each do |resource|
    method_name = Google::INFLECTOR.underscore(resource.name).to_sym
    if !self.respond_to?(method_name)
      metaclass.send(:define_method, method_name) { resource }
  end
end
```

On a standard Rails project that cache purging gives a significant performance issues.

**Comment by sqrrrl** [comment]
Fixed in 0.9 which no longer uses runtime code generation.
