### ISSUE TITLE
Bug Google Analytics API v3 in analytics.management.dailyUploads.upload

### ISSUE THREAD

**Issue by shved270189** [google/google-api-ruby-client#122]
When use analytics.management.daily_uploads.upload request is to

POST 
https://www.googleapis.com/analytics/v3/management/accounts/*******/webproperties/*******/customDataSources/*****************/dailyUploads/2014-04-06/uploads?appendNumber=1&type=cost&key={YOUR_API_KEY}

I get bad response with message "Upload request url should start with https://www.googleapis.com/upload/analytics/..." and status 400.

This request I get in Google APIs Explorer https://developers.google.com/apis-explorer/#s/analytics/v3/analytics.management.dailyUploads.upload too.

But in documentation https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/dailyUploads/upload state that http request 

POST https://www.googleapis.com/upload/analytics/v3/management/accounts/accountId/webproperties/webPropertyId/customDataSources/customDataSourceId/dailyUploads/date/uploads

**Comment by danielterega** [comment]
same isssue

**Comment by sqrrrl** [comment]
Try adding the uploadType parameter (set to either media, multipart, or resumable.) Client could certainly be a little smarter and pick a default when media is present, but currently requires that it be specified in the request.

**Comment by wswoodruff** [comment]
Running into this issue in October 2017
