### ISSUE TITLE
Is the schemas id field required?

### ISSUE THREAD

**Issue by lynnaloo** [google/google-api-ruby-client#137]
The Node and Python google api clients work without an 'id' field in the discovery doc schemas, but the Ruby client breaks if one does not exist when parsing schemas. Is this 'id' field required?

**Comment by sqrrrl** [comment]
Closing as wont-fix. 0.9 moved away from dynamic API generation to ahead of time generation. It still requires the ID field at the time of generation though. If you have a discovery doc that *doesn't* have an ID (e.g. cloud endpoints maybe?) you can modify it to add a synthetic ID before running the generator.
