### ISSUE TITLE
Documentation for QPX Express Ruby wrapper

### ISSUE THREAD

**Issue by myfashionhub** [google/google-api-ruby-client#138]
I cannot find any specific example for using QPX Express in Ruby except this one line: `qpxExpress.trips.search`. When you click on it, the example is for javascript/json.
https://developers.google.com/apis-explorer/#p/qpxExpress/v1/

Another question is: Does the API provide a way to purchase the ticket listed? Otherwise the search would be pretty unfruitful.

**Comment by sqrrrl** [comment]
FYI - 0.9 switched to generating the APIs ahead of time which has the benefit of producing documented code too :) See https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/qpx_express_v1/service.rb
