### ISSUE TITLE
Uploading APKs with the new androidpublisher V2 api fails with a 500 error

### ISSUE THREAD

**Issue by johnhamelink** [google/google-api-ruby-client#140]
Hi there,

I'm new to Google's ruby API client. I'm trying to implement an "APK Pusher" in ruby for my CI system (hopefully I'll open source the project and put it on Github for others to enjoy). 

I've been following the work done in the Python Examples ([here](https://github.com/googlesamples/android-play-publisher-api/blob/master/v2/python/basic_upload_apks.py)).

I've managed to sign in with my p12 key and insert a new edit against the APK's packagename, but when I attempt to Upload the APK I get this:

    #<Google::APIClient::Schema::Androidpublisher::V2::Apk:0x1f9931c DATA:{"error"=>{"code"=>500, "message"=>nil}}>

My apk uploading code looks like this:

     apk_response = client.execute(
       api_method: service.edits.apks.upload,
       parameters: {
         'editId'      => edit_request.data['id'],
         'packageName' => "com.farmgeek.agricountantdemo.app"
       },
       media: Google::APIClient::UploadIO.new(file, 'application/vnd.android.package-archive')
     )

Where file is a pathname and edit_request is the variable storing the inserted edit.

Any help would be very much appreciated!

**Comment by nofxx** [comment]
@johnhamelink Hello John. Did it worked out?
Looking for a solution to upload apks. 
What a monkey job browse/login/upload is.

**Comment by kevinj** [comment]
I just got this working. You have to use 0.9 pre. Check out the migration guide:
https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

then you use the new API to upload:

```ruby
# create a publisher object
publisher = Google::Apis::AndroidpublisherV2::AndroidPublisherService.new
publisher.authorization = ...

# start a new edit
edit = publisher.insert_edit(packageName)

# upload the APK
apk = publisher.upload_apk(packageName, edit.id, upload_source: apkFileName)

# update the alpha track to point to this APK
track = publisher.get_track(packageName, edit_id, 'alpha')
track.update!(version_codes: [ apk.version_code ]) # you need to use a track object to change this
publisher.update_track(packageName, edit_id, 'production', track) # save the modified track object

# commit the edit
publisher.commit_edit(packageName, edit_id)
```

**Comment by nofxx** [comment]
@kevinj let's build a gem =D

**Comment by nofxx** [comment]
Done! https://github.com/fireho/capkin
Going to some management: listing apks and promoting stage tomorrow.

**Comment by sqrrrl** [comment]
Nice work on capkin, keep going :) Going to close this issue since it's a bit old and seems to be fine in 0.9.

**Comment by nofxx** [comment]
@sqrrrl ty! Wouldn't be possible without your work on this gem.
