### ISSUE TITLE
Don't override Object#send

### ISSUE THREAD

**Issue by ttanimichi** [google/google-api-ruby-client#191]
https://github.com/google/google-api-ruby-client/blob/master/lib/google/api_client/request.rb#L159

FYI. Google::APIClient overrides [Object#send](http://ruby-doc.org/core-2.2.0/Object.html#method-i-send). It may cause unexpected errors.

**Comment by mrkplt** [comment]
It looks like it overrides #send inherited from Object in Google::ApiClient::Request#send but the behavior is isolated to that class. Unfortunately #send is very different from Object#send. So, yeah, that's going to cause problems.

**Comment by sqrrrl** [comment]
Fix in 0.9 due soon
