### ISSUE TITLE
Revoke access token support?

### ISSUE THREAD

**Issue by Mehonoshin** [google/google-api-ruby-client#192]
Hi folks!

I looked through this repo, and didn't find any support to revoke access token via API.
It is present in api reference https://developers.google.com/accounts/docs/OAuth2WebServer#tokenrevoke

I could make a contribution. Is it suitable for this gem?

**Comment by rcaught** [comment]
+1, the other languages have this implemented.

**Comment by Mehonoshin** [comment]
I've made a dirty implementation.
https://github.com/revve/google-api-ruby-client/commit/cf201893923837eec4157a2d8debae7e0e2fa163

If gem maintainers are interested, I'll do PR

**Comment by sqrrrl** [comment]
There's google/google-auth-library-ruby#48 which adds revocation support among other things. Trying to consolidate auth support there.

**Comment by cchandler81** [comment]
There doesn't seem to by any documentation on either gem, or the internet at large, on how exactly to call the revoke function in the google-auth-library-ruby. Can you provide an example? I've tried unsuccessfully to call it on the Signet client and the Google API service. Please help!

**Comment by hundsim** [comment]
Any news on this?
