### ISSUE TITLE
Custom api method/resources ignored; if they conflict with built-in methods on Object

### ISSUE THREAD

**Issue by glreese12** [google/google-api-ruby-client#194]
I am trying to implement the rise vision apis. The library is ignoring all the display resources/methods (i.e. core.display.get, core.display.list) for the api; possibly because they conflict with the built-in methods on object.  Is it possible for the library to have rules for disambiguating names to handle this situation? 

Risevision API: https://apis-explorer.appspot.com/apis-explorer/?base=https://rvaserver2.appspot.com/_ah/api#p/

CODE SNIPPET:
(@client.register_discovery_uri('core', 'v1', 'https://rvaserver2.appspot.com/')) rescue Exception
 @core = @client.register_discovery_document('core', 'v1', File.read("#{Rails.root}/tmp/core.json"))
 result = @client.execute(:api_method => @core.display.get, :parameters => {'id' => 'displayId'})

thanks

**Comment by sqrrrl** [comment]
0.9 moves away from runtime code generation. The new code generator correctly avoids conflicts with built-in names.
