### ISSUE TITLE
API client ignores rootUrl API property in discovery document 

### ISSUE THREAD

**Issue by munangst** [google/google-api-ruby-client#195]
The API client doesn't seem to pay attention to the [rootUrl property](https://developers.google.com/discovery/v1/using#build-compose) in the API discovery document, and always sends requests to the :host parameter passed to the APIClient constructor (or defaults to www.googleapis.com). This breaks discovery-based client support for APIs that use a rootUrl other than https://www.googleapis.com.

**Comment by sqrrrl** [comment]
Yeah, definitely a bug. There is a workaround you can do by manually registering discovery docs:

    (client.register_discovery_uri('foo', 'v1', 'https://base.url.to.api/')) rescue Exception
    api = client.register_discovery_document('foo', 'v1', File.read('foo.json'))
