### ISSUE TITLE
Inconsistent Google Calendar behavior - calendar ID

### ISSUE THREAD

**Issue by zachfeldman** [google/google-api-ruby-client#198]
The API inconsistently returns the calendar ID. Sometimes it's the calendar name, other times it's the calendar ID. Pretty maddening and I'm not really sure if it's an implementation issue in the gem or a Google API issue. This makes it impossible to consistently store a calendar ID and retrieve information about it. Any ideas? Here's some sample code:

````ruby
service = client.discovered_api('calendar', 'v3')
result = client.execute(:api_method => service.calendar_list.list)

@calendars = result.data
````

````erb
<%=form_tag "/calendars/save" do %>
            <% @calendars.items.each do |calendar| %>
                <%=label_tag do %>
                    <%=check_box_tag 'calendar_ids[]', calendar["id"], false %>
                    <%= calendar["summary"] %>
                <% end %>
                <br>
            <% end %>
            <%=submit_tag %>
        <% end %>
````

**Comment by zachfeldman** [comment]
Haha ok, close my issue without looking at it...it's irrelevant anyway at this point I suppose!

**Comment by sqrrrl** [comment]
It's based on an old version of the client and I'm not able to reproduce it. If you can reproduce with 0.9.x, please re-open and make sure that https://developers.google.com/apis-explorer/#search/calendar/m/calendar/v3/calendar.calendarList.list works as expected for your account.
