### ISSUE TITLE
Permission issue, other user can not require `google/api_client`

### ISSUE THREAD

**Issue by sonots** [google/google-api-ruby-client#205]
I am just curious about the permission of `google/api_client`:

```
$ ls -l ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib//google
drwxr-xr-x 5 sonots sonots  4096  March 24 18:32 2015 api_client
-rw-r----- 1 sonots sonots 27249  March 24 18:32 2015 api_client.rb
```

that is, there is no readable permission for other users. I have never seen such gem. For example, `faraday` gem permits to read for other users. 

```
$ ls -l ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/
drwxr-xr-x 5 sonots sonots 4096  March 24 18:31 2015 faraday
-rw-r--r-- 1 sonots sonots 7946  March 24 18:31 2015 faraday.rb
```

Could you tell me whether there is a reason to drop the readable permission for other users? If not, I prefer to have the readable permission for other users. 

FYI: This is related with an issue which I met with `td-agent` https://github.com/treasure-data/omnibus-td-agent/issues/35

PS. It seems, in git repository, it is assigning the readable permission for other users.

**Comment by cbeer** [comment]
I'm seeing the same problem with google-api-client 0.8.3. The previous release worked fine.

**Comment by repeatedly** [comment]
Maybe, this problem could happen when users use system installed gems.
Releasing fixed version is better.

**Comment by kazunori279** [comment]
Contacted Tim who's the owner of this and explained how this issue affects the BigQuery plugin users. Will keep updating the status.

**Comment by tbetbetbe** [comment]
This has been addressed by a new patch release [0.8.4](https://rubygems.org/gems/google-api-client/versions/0.8.4).

**Comment by cbeer** [comment]
Thank you.

**Comment by sonots** [comment]
Thanks!

**Comment by kenjiskywalker** [comment]
Thank! :smile:
