### ISSUE TITLE
User does not have sufficient permission for site

### ISSUE THREAD

**Issue by Dimcha** [google/google-api-ruby-client#206]
I run this code and I get the response data:
```
@data=#<Google::APIClient::Schema::Webmasters::V3::UrlCrawlErrorsSamplesListResponse:0x67752d0 DATA:{"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"forbidden", "message"=>"User does not have sufficient permission for site 'http://www.mysite.com/'. See also: https://support.google.com/webmasters/answer/2451999."}], "code"=>403
```
Any ideas why do I get this error? 
```
require 'google/api_client'

SERVICE_ACCOUNT_EMAIL_ADDRESS = 'Service_Account_Email_address'
PATH_TO_KEY_FILE = Rails.root.join('config/google_api_key.p12')
SITE_URL = "http://#{Rails.application.routes.default_url_options[:host]}"

def oauth_options
  {
    token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
    audience: 'https://accounts.google.com/o/oauth2/token',
    scope: 'https://www.googleapis.com/auth/webmasters',
    issuer: SERVICE_ACCOUNT_EMAIL_ADDRESS,
    signing_key: Google::APIClient::PKCS12.load_key(PATH_TO_KEY_FILE, 'passphrase')
  }
end

def default_not_found_params
  {
    siteUrl: SITE_URL,
    platform: 'web',
    category: 'notFound'
  }
end

@client = Google::APIClient.new(
  application_name: 'MySite',
  application_version: '3.0.0'
)
@client.authorization = Signet::OAuth2::Client.new(oauth_options).tap(&:fetch_access_token!)
@api_handle = @client.discovered_api('webmasters', 'v3')

@client.execute(
  api_method: @api_handle.urlcrawlerrorssamples.list,
  parameters: default_not_found_params
)
```

**Comment by jeremywadsack** [comment]
Well, according to the error the account logging in doesn't have permissions to access crawl errors on that site.

Have you authorized the service account for access to that site in Webmaster Tools? Alternately, if you have authorized another account in the domain, you can authorize your service account to impersonate your domain users for the scope. See [here](https://developers.google.com/accounts/docs/OAuth2ServiceAccount#delegatingauthority) for details.

**Comment by Dimcha** [comment]
I followed those steps: **Delegating domain-wide authority to the service account** from your link, but nothing changed. I keep getting same error. 

What I changed:
in admin.google.com/AdminHome I added those scopes : `https://www.googleapis.com/auth/webmasters,
https://www.googleapis.com/auth/webmasters.readonly` for my Service Account Client ID.

Any other ideas?

**Comment by jeremywadsack** [comment]
That all sounds right. Just to check, you have authorized some account in Webmaster tools, right? Is that account in the domain that you authorized the service account for? (Perhaps specifics would help here.)

You could try authorizing the service account directly in Webmaster tools. At least that would eliminate one level of authorization check (the domain-wide authority).

**Comment by Dimcha** [comment]
Yay, it works!!! I just did not add  Service Account  email into webmaster tools user list.

Thank you Jeremy! :tada: :smile:

**Comment by vinaynan1** [comment]
jeremywadsack, I am facing a similar issue i added service account in the google webmaster account but still the same issue, can you please help. I am new to programming.

I see the samr 403 issue/
