### ISSUE TITLE
Getting servingLimitExceeded using batch requests

### ISSUE THREAD

**Issue by jeremywadsack** [google/google-api-ruby-client#210]
I'm using this gem to batch up thousands of API calls into a few HTTP requests. When I do that I get 'servingLimitExceeded' error messages for _some_ results within a batch but not for the entire batch. For example, I may get 100 records responding with this error and then it starts returning more results. All within the a single batch. I'm using up to 1000 requests within a batch.

I assume this is the requests/second limit as it resolves after several failed attempts. But it's not clear from the message, which is [described as](https://developers.google.com/webmaster-tools/v3/errors#FORBIDDEN) "The overall rate limit specified for the API has already been reached."

If batches are handled internally by Google API, how can I adjust them to not hit the rate limit?

**Comment by sqrrrl** [comment]
Use smaller batches :)

Seriously, 1000 is the max size of a batch, but that doesn't mean that the API your calling is going to allow you to make that may calls concurrently. Some APIs might, but if you're consistently running into issues with batches not completing you'll need to rate limit yourself by creating smaller batches.

**Comment by jeremywadsack** [comment]
That aligns with the response I got from the Webmaster Tools team as well. In this case they are limiting to 20QPS (no matter what you set in the API console). 

Because of how the `webmasters.urlcrawlerrorssamples` API is designed we are making about 5M API calls each time we gather data. I was hoping we could make this faster, but we've worked around the "servingLimitExceeded" error for now.
