### ISSUE TITLE
I try to download file from google drive, but download_url is null

### ISSUE THREAD

**Issue by eddiefisher** [google/google-api-ruby-client#212]
https://gist.github.com/eddiefisher/b1a85a6f259ef574f9f2 - code

file exist, but I can't get download_url from file

**Comment by sqrrrl** [comment]
There are cases where drive won't return a download url. That's normally. For example, if a file is shared to you with read/comment access and the owner has disabled copy/print the download url will be omitted. There are also file types that aren't blobs and don't have any content to directly download (Google Docs, Sheets, Slides, as well as some 3rd party apps.)
