### ISSUE TITLE
API#batch_patch should be based on service's root_uri

### ISSUE THREAD

**Issue by remi** [google/google-api-ruby-client#215]
An API's #batch_path is constructed from `www.googleapis.com` + `/` + `batchPath` where `'batchPath'` comes from the service's discovery document.

Paraphrased excerpt from current [HEAD implementation](https://github.com/google/google-api-ruby-client/blob/1ed677b796afad92b5f232165912ab269c0b4b8a/lib/google/api_client/discovery/api.rb#L187-L196):

```ruby
class Google::APIClient::API
  def batch_path
    self.document_base.join(Addressable::URI.parse('/' + @discovery_document['batchPath']))
  end
end
```

Not all Google APIs are served from `www.googleapis.com` so this should probably (*unverified*) be based off of the API's `'rootUrl'` instead, eg.

```ruby
class Google::APIClient::API
  def batch_path
    self.root_uri.join(Addressable::URI.parse('/' + @discovery_document['batchPath']))
  end
end
```

This needs to be verified and tests added.

For context: [Pull #213 Use discovered 'rootUrl' as base URI for services](https://github.com/google/google-api-ruby-client/pull/213)

**Comment by tbetbetbe** [comment]
@remi, can you confirm that this was fixed by #213 and close this ?
