### ISSUE TITLE
Unable to Connect to Pub/Sub

### ISSUE THREAD

**Issue by blowmage** [google/google-api-ruby-client#218]
I am unable to connect to a Pub/Sub service. I've tried on three separate accounts, all with Pub/Sub enabled, and for each I get "Internal Error".

```ruby
require "json"
project = ENV["PUBSUB_PROJECT"]
keyfile = JSON.parse File.read ENV["PUBSUB_KEYFILE"]

require "signet/oauth_2/client"
options = {
  token_credential_uri: "https://accounts.google.com/o/oauth2/token",
  audience: "https://accounts.google.com/o/oauth2/token",
  scope: ["https://www.googleapis.com/auth/pubsub",
          "https://www.googleapis.com/auth/cloud-platform"],
  issuer: keyfile["client_email"],
  signing_key: OpenSSL::PKey::RSA.new(keyfile["private_key"]) }
signet = Signet::OAuth2::Client.new options
signet.fetch_access_token!

require "google/api_client"
client = Google::APIClient.new application_name: "blowmage",
                               application_version: "1.0.0"
client.authorization = signet
pubsub = client.discovered_api "pubsub", "v1beta2"

client.execute api_method: pubsub.projects.topics.list,
               parameters: { project: "projects/#{project}" }
```

This returns a 500 response with the following JSON:

```javascript
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "internalError",
    "message": "Internal Error"
   }
  ],
  "code": 500,
  "message": "Internal Error"
 }
}
```

Am I missing something in this code? Is Pub/Sub v1beta2 known to work?

**Comment by blowmage** [comment]
It looks like google_api_client is using the wrong URLs for connecting to Pub/Sub v1beta2. In my previous code example, you can inspect the API method's `uri_template` value to see the URL that it is using:

```ruby
pubsub.projects.topics.list.uri_template.pattern #=> "https://www.googleapis.com/v1beta2/{+project}/topics"
```

The API call works when we monkey-patch that method to point to the [URL that the documentation specifies](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/topics/list):

```ruby
t = pubsub.projects.topics.list.uri_template
def t.pattern
  "https://pubsub.googleapis.com/v1beta2/{+project}/topics"
end

client.execute api_method: pubsub.projects.topics.list,
               parameters: { project: "projects/#{project}" } #=> success!
```

This seems odd to me because the [discovery JSON](https://www.googleapis.com/discovery/v1/apis/pubsub/v1beta2/rest) is clearly using "https://pubsub.googleapis.com/" and not "https://www.googleapis.com/". Is there something else going on in google_api_client that is causing this?

**Comment by blowmage** [comment]
I compiled the gem locally and commit 1ed677b796afad92b5f232165912ab269c0b4b8a seems to have fixed this. Is work on using the discovery document's baseUrl/rootUrl completed? Any word on when a new version with this fix will be released?

**Comment by remi** [comment]
Hey Mike, that commit should be ready to release but I'm not sure about when a new version will be released.

@tbetbetbe Can we release 0.8.6 to get the rootUrl fix released?

**Comment by blowmage** [comment]
Hey remi! Long time! :)

**Comment by blowmage** [comment]
Some more observations. `pubsub.projects.subscriptions.acknowledge` hits the URL 
`https://pubsub.googleapis.com/projects/#{project}/subscriptions/#{subscription_name}:acknowledge`, but note the missing `/v1beta2` from the [URL in the documentation](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/subscriptions/acknowledge). The pattern in `uri_template.pattern` is "{+subscription}:acknowledge".

Compare to `pubsub.projects.topics.list` which hits the URL `"https://pubsub.googleapis.com/v1beta2/projects/#{project}/topics"` with the pattern in `uri_template.pattern` having the full URL "https://pubsub.googleapis.com/v1beta2/{+project}/topics".

I'm stuck on other issues ATM, but from what I've seen so far I would not expect the calls to `pubsub.projects.subscriptions.acknowledge`, `pubsub.projects.subscriptions.pull`, or `pubsub.projects.topics.publish` to work as is.

**Comment by remi** [comment]
I only tested `pubsub.projects.topics.list` to start with.  Are you looking into fixes for these discovered methods?  Let me know if not and I'll dive in and we can make sure all discovered methods work.

**Comment by blowmage** [comment]
I've got some other things taking my attention ATM, but I'll take a look at these discovered methods tomorrow morning. I would assume that using the discovery document's `baseUrl` instead of `rootUrl` would fix it.

**Comment by remi** [comment]
Looks like its [`method_base.join(Addressable::URI.parse(@discovery_document['path']))`](https://github.com/google/google-api-ruby-client/blob/0003e564b19e35386320f13e5efb1dc85cb5b6b8/lib/google/api_client/discovery/method.rb#L111) that's hurting us.

```ruby
>> require "addressable/uri"
>> uri = Addressable::URI.parse "{+topic}:publish"
>> uri.scheme
=> "{+topic}"
>> uri.path
=> "publish"
```

Because `"{+topic}:publish"` has a scheme (thanks to its `":"`) it doesn't join with the `method_base` resulting in our `uri_template` being simply `"{+topic}:publish"` instead of the expected full `"https://pubsub.googleapis.com/v1beta2/{+topic}:publish"`

This seems fair, so I updated our method `#uri_template` builder to use `method_base` (eg. `"https://pubsub.googleapis.com/v1beta2/"`) `+ "./" + @discovery_document['path']`

**Comment by blowmage** [comment]
Ah, that makes more sense. :)
