### ISSUE TITLE
Safe Browsing Lookup API

### ISSUE THREAD

**Issue by avokhmin** [google/google-api-ruby-client#224]
https://developers.google.com/safe-browsing/lookup_guide

Which params should be passed into `discovered_api` for getting of `Safe Browsing Lookup API`?

```
[20] pry(main)> client.discovered_api('safebrowsing', 'v3.1')
Google::APIClient::ClientError: Not Found
[22] pry(main)> client.discovered_api('safebrowsing', '3.1')
Google::APIClient::ClientError: Not Found

and etc raises the same error.
```

**Comment by sqrrrl** [comment]
That API isn't supported by any of the API clients. It doesn't conform to the conventions used by the other APIs.

**Comment by avokhmin** [comment]
:( Thanks!
