### ISSUE TITLE
Stopping an instance shows a TERMINATED status

### ISSUE THREAD

**Issue by tyler-ball** [google/google-api-ruby-client#225]
If I stop an instance through the console or through the API, and then fetch the instance again it returns with a status of `STOPPING` then `TERMINATED`.  I assumed this would be `STOPPING` then `STOPPED`.  Is this the correct behavior?

**Comment by icco** [comment]
This is the general Google auth library for Ruby, but for the [Compute Engine API](https://cloud.google.com/compute/docs/reference/latest/instances#resource), I know the rough answer.

```
status: The status of the instance. One of the following values: PROVISIONING, STAGING, RUNNING, STOPPING, STOPPED, TERMINATED.	
```

What determines when you stop the instance though is from https://cloud.google.com/compute/docs/instances#stop_job

**Comment by tyler-ball** [comment]
I understand the behavior is enforced by the API and not this library.  But I haven't seen anywhere the `STOPPED` status is referenced.  Do you know when this status is ever applied to the instance?
