### ISSUE TITLE
Is JSON Key file supported?

### ISSUE THREAD

**Issue by a2ikm** [google/google-api-ruby-client#226]
These days Google Developer Console generates JSON Key, not P12 Key by default.
https://cloud.google.com/storage/docs/authentication#generating-a-private-key

If it is, I'm happy to hear how to authenticate `Google::APIClient` with a JSON Key file.

Thanks.

**Comment by sqrrrl** [comment]
Yes, using https://github.com/google/google-auth-library-ruby. Just requires that you set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the json key.

**Comment by a2ikm** [comment]
Oh, I've missed it. Thank you!

**Comment by wenshutang** [comment]
You may also specify the path to your JSON key when creating a service account credential:

`scope = ["https://www.googleapis.com/auth/analytics.readonly"]`
`file = File.open('/path/to/your/file', 'r')`
`authorization = Google::Auth::ServiceAccountCredentials.make_creds({:json_key_io=> file, :scope => scope})`

Hope that helps!
