### ISSUE TITLE
How to retrieve a list of Calendar Resources (Rooms)?

### ISSUE THREAD

**Issue by andrewhavens** [google/google-api-ruby-client#236]
I am trying to use the Google API Ruby client library to retrieve a list of calendar resources. However, I am able to retrieve a list of events for a specific calendar, but I cannot find a way to list the calendar resources as described in this documentation: https://developers.google.com/admin-sdk/calendar-resource/#retrieving_calendar_resources

I have tried something like this, but it does not work:

```ruby
calendar = client.discovered_api('calendar/resource')
```

...but no API is discovered. I did not find any methods on the `calendar` object. How can I retrieve the list of calendar resources?

**Comment by sqrrrl** [comment]
The Calendar Resource API is based on an older protocol and isn't compatible with this client.

**Comment by JulienBreux** [comment]
@sqrrrl But, do you have an example? (links? or other?). Thx in advance.

**Comment by sqrrrl** [comment]
@JulienBreux See https://developers.google.com/admin-sdk/calendar-resource/.

**Comment by JulienBreux** [comment]
@sqrrrl Big thx!

**Comment by vipin-infobeans** [comment]
@sqrrrl https://developers.google.com/admin-sdk/calendar-resource/ is available on github. ?i checked it but don't found. I know this is not right place to ask you but i really need this in my project

**Comment by JulienBreux** [comment]
Note: Now, you must use: https://developers.google.com/admin-sdk/directory/v1/reference/resources/calendars

**Comment by paragdas** [comment]
I too am looking to retrieve the room names from the Resources.Buildings . Can anyone help???
