### ISSUE TITLE
Quickstart documentation inconsistent with ClientSecrets implementation

### ISSUE THREAD

**Issue by professor** [google/google-api-ruby-client#241]
The documentation says to create and download a client secrets.json fille, however, after doing so, the ClientsSecrets can not parse the downloaded json.

https://developers.google.com/admin-sdk/directory/v1/quickstart/ruby

Google::APIClient::ClientSecrets.initialize parses this information incorrectly. Looking at the code, there is no way that it can parse the downloaded json file. I'm guessing there is an issue with the documentation.

{"private_key_id"=>"randonmness1",
 "private_key"=>
  "-----BEGIN PRIVATE KEY----------END PRIVATE KEY-----\n",
 "client_email"=>
  "randomness2@developer.gserviceaccount.com",
 "client_id"=>
  "radnomness3.apps.googleusercontent.com",
 "type"=>"service_account"}

**Comment by sqrrrl** [comment]
You created the wrong type of credentials. Those are credentials for a service account and can be used (quite easily) with the googleauth library. The quickstart instructions specify creating an "Installed application" client. If you do that, the "Download JSON" button will produce the correct format.
