### ISSUE TITLE
broken links on https://developers.google.com/api-client-library/ruby/reference/rubydoc

### ISSUE THREAD

**Issue by laurelfan** [google/google-api-ruby-client#246]
All the links to rubydoc documentation from this page:
https://developers.google.com/api-client-library/ruby/reference/rubydoc

are broken. Eg:
http://www.rubydoc.info/github/google/google-api-ruby-client/file/README.md

**Comment by sqrrrl** [comment]
Docs on developer.google.com were updated for the new version and links fixed.

**Comment by laurelfan** [comment]
awesome, thanks!
