### ISSUE TITLE
Clarification on Admin Apis and service accounts (0.9pre1)

### ISSUE THREAD

**Issue by professor** [google/google-api-ruby-client#249]
Do I set the "impersonated service account email address" (not the client_email/client_id)  on the authorization or the admin directory service? 

I've tried examining the source code, but I can't seem to find the correct key for this setting.

Option 1?
authorization = Google::Auth.get_application_default(scopes)
some_headers = { ???key = my_email_address }
authorization.apply(some_headers)

or 
Option2 ?
admin = Google::Apis::AdminDirectoryV1::DirectoryService.new({???key  = my_email_address})
result = admin.get_user('some_domains_email_address')

Context:
The Admin APis documentation (https://developers.google.com/admin-sdk/directory/v1/guides/delegation) says that

"Only users with access to the Admin APIs can access the Admin SDK Directory API, therefore your service account needs to impersonate one of those users to access the Admin SDK Directory API."

The accompany java example suggest setServiceAccountUser. I'm not able to find the corresponding method in ruby.

**Comment by sqrrrl** [comment]
If you're using the googleauth lib for your service account, impersonating a user on a domain is pretty easy:

```ruby
authorization = Google::Auth.get_application_default(scopes)
...
user_auth = authorization.dup # Make a copy so we can modify for the specific user
user_auth.sub = 'user@example.org' # Set the user we're impersonating
user_auth.fetch_access_token! # Fetch a new access token
...
```

Of course you need to make sure that the client ID is authorized for the domain (via the domain's control panel.)
