### ISSUE TITLE
set youtube channel banner image 

### ISSUE THREAD

**Issue by anbublacky** [google/google-api-ruby-client#250]
I am able to upload image to youtube channel arts.

this is the ruby script i am having https://gist.github.com/anbublacky/ff76b56642613bfe3066

i am unable to set the uploaded image as banner

https://developers.google.com/youtube/v3/docs/channels/update

They have given python example, where i don know what this function does

image_url = resumable_upload(insert_request)
they are assinging image url to

channel_brandingSettings["image"]["bannerExternalUrl"] = banner_url
and again don know how to convert this to ruby

channels_update_response = youtube.channels().update(
  part='brandingSettings',
  body=dict(
    brandingSettings=channel_brandingSettings,
    id = channels_response["items"][0]["id"]
  )).execute()

How to set uploaded image as banner?

This  is not a bug/issue, please help me, i have also asked stackoverflow

http://stackoverflow.com/questions/31137906/set-youtube-v3-channel-banner-image-through-ruby

as there is not enough documentation for ruby i am asking here

# updated:

This is what i'm trying to set banner 

    banner_url = JSON.parse(image_insert_response.body)["url"]
    channel_list_res["items"][0]["brandingSettings"]["image"]["bannerExternalUrl"] = []
    channel_brandingSettings = channel_list_res["items"][0]["brandingSettings"]
    channel_brandingSettings["image"]["bannerExternalUrl"] = banner_url

  channels_update_response = client.execute!(
  	:api_method => youtube.channels.update,
	:parameters => {  	
    	:part => 'brandingSettings',
    },
    :body => {
    	'brandingSettings' => channel_brandingSettings,
    	'id' => channel_list_res['items'][0]['id']
	})

shows this error  undefined method `bytesize' for #<Hash:0x0000000438e178>

the body part i'm sending is wrong don know how to send

**Comment by sqrrrl** [comment]
Change :body to :body_object. It expects :body to be the raw body content (string or IO), not a hash and should rarely be used, if ever. Most cases you should be using :body_object.

**Comment by anbublacky** [comment]
Thanks @sqrrrl , you are my saviour, and it worked fine. I am able to set youtube channel banner now
This is the new file, https://gist.github.com/anbublacky/aedee0284f1bd2ea0a71. Hope it helps someone.

**Comment by anbublacky** [comment]
Hi,

I got into a problem, in local when i execute the script  https://gist.github.com/anbublacky/aedee0284f1bd2ea0a71, it will open up a browser and ask for authorization, i thought i would send the access token file which created during authorization would be enough  to set banner from vps, but when i run the it is trying to open up a browser and showing the error.

    Launchy::CommandNotFoundError: Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new

Is there anyway i could use the access toke to post it, or how to run the script in vps terminal

As the script is going to be run in cron job.
