### ISSUE TITLE
Missing loading pkcs keys

### ISSUE THREAD

**Issue by professor** [google/google-api-ruby-client#252]
I'm upgrading code from 0.8 to 0.9. I'm not finding where this method is in the new auth api: Google::APIClient::KeyUtils.load_from_pkcs12

Context: I'm deploying ruby code to heroku for service account access to Google Admin SDK. Since the code base is open source, I can not store the json file or pkcs12 on the filesystem. I see that in Issue 27 you added support for reading a json file from environment variables, but I'm having a deuce of a time formatting the json so that it can be stored as an environment variable. As such, I'd like to be able to pull in a pkcs12 key from an environment variable.

**Comment by g33kidd** [comment]
I've had this same issue trying to move from 0.8 to 0.9pre3. It seems I can't require 'google/api_client' anymore so, what would be the work around to using my .json or .p12 file for authorization?

**Comment by professor** [comment]
It looks like this ruby library is no longer supporting heroku based ruby
applications. I decided to abort a 0.9 upgrade and stick with 0.8

**Comment by sqrrrl** [comment]
Added KeyUtils back temporarily, but really, the correct thing to do is migrate to using the `googleauth` gem (which itself is just a wrapper around signet.) That requires downloading a new private key from the Developer console in JSON format. Downloading a new key won't invalidate your old one, so you should be able to migrate gracefully.

There shouldn't be any issues running on Heroku. If you have specific issues, please raise them.
