### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by jamox** [google/google-api-ruby-client#255]
The link for the CONTRIBUTING.md is broken in Readme.md.
The fix is simple:
```diff
-See [CONTRIBUTING](contributing).
+See [CONTRIBUTING](CONTRIBUTING.md).
```
Feel free to fix it directly, or I can create a pr (currently following the first step of the process described in the contributing.md...)

**Comment by sqrrrl** [comment]
Updated readme.
