### ISSUE TITLE
Retry ClientError exceptions that are caused by exceeding the rate limit in v0.8.x

### ISSUE THREAD

**Issue by hmnhf** [google/google-api-ruby-client#256]
The gem doesn't retry any kind of ClientError exception.
Currently I am getting this exception:
Google::APIClient::ClientError: Rate limit exceeded for creating file subscriptions
I think there should be an extra condition in APIClient#client_error_handler, to retry the ClientError if it has been caused by exceeding the rate limit.

**Comment by sqrrrl** [comment]
Do you happen to know what the specific error response was? It should be retrying (if enabled) if the reason is either rateLimitExceeded or userRateLimitExceeded. Those should be getting converted to RateLimitErrror instead of the more generic ClientError.

**Comment by hmnhf** [comment]
Unfortunately, I don't have the exact error response,  but exceptions's #inspect has returned this:
"Google::APIClient::ClientError: Rate limit exceeded for creating file subscriptions"

And as far as I know, RateLimitError is introduced in v0.9, but I'm currently using v0.8.6.
It seems that there's no retrying for the ClientError exceptions in v0.8.x, as APIClient#client_error_handler is raising the exception if it's a ClientError.

As a quick fix, I have changed #client_error_handler to retry if the exception's message contains "Rate limit exceeded".
Taskulu/google-api-ruby-client@a90b775

**Comment by jeremywadsack** [comment]
@hmnhf We did the same under 0.8.x — retries 403. Understanding that it it would be the same status code if you actually are not authorized for the resource.


@sqrrrl https://developers.google.com/webmaster-tools/v3/errors documents the following "rate limit" errors:

- servingLimitExceeded
- rateLimitExceeded
- userRateLimitExceeded
- concurrentLimitExceeded
- variableTermLimitExceeded

In addition I've seen "serviceLimit" from the `list_errors_samples` and `get_errors_sample` methods.

Also, with the `query_search_analytics` call, we get "quotaExceeded" errors of which John Mueller for the Search Console team said, "We use the same error for both situations" (rate and quota).
