### ISSUE TITLE
Bundle install fails because google_auth and auto_parse depend on different multi_json versions

### ISSUE THREAD

**Issue by gisborne** [google/google-api-ruby-client#257]
$ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.......
Bundler could not find compatible versions for gem "multi_json":
  In Gemfile:
    googleauth (~> 0.3) x86-mingw32 depends on
      multi_json (= 1.11.0) x86-mingw32

    multi_json (1.11.1)

**Comment by robly** [comment]
Any update/fix on this?

**Comment by rusikf** [comment]
@gisborne , @robly  Is it actual for now ? How to reproduce this error? Can you show the full Gemfile, Gemfile.lock ? Do you use only googleauth or google-api-ruby-client too ?
