### ISSUE TITLE
Samples broken?

### ISSUE THREAD

**Issue by ahmetabdi** [google/google-api-ruby-client#259]
All fail when trying to require the api

``
cannot load such file -- google/apis/translate_v2 (LoadError)
``

**Comment by FergusonSean** [comment]
I have this same issue. How did you resolve this?

**Comment by FergusonSean** [comment]
For those who see this later you need to make sure you on the 0.9.pre1 version of the gem

**Comment by ahmetabdi** [comment]
Yep @FergusonSean that was it :) sorry for late response.
