### ISSUE TITLE
Automatically format strings from a result set?

### ISSUE THREAD

**Issue by ahmetabdi** [google/google-api-ruby-client#260]
Using ``Google::Apis::PagespeedonlineV2::Result::FormattedResults::RuleResult``

``Your page has no redirects. Learn more about {{BEGIN_LINK}}avoiding landing page redirects{{END_LINK}}.``

Is it possible to auto format these results with the arguments that get returned from the API

**Comment by sqrrrl** [comment]
Nope. The library is intended to be fairly generic as far as supporting a large number of different Google APIs. That particular logic for formatting pagespeed reports is very specific to that API. If it's useful, it's easy enough to build a pagespeed specific wrapper library or report formatting library that people can reuse. But that should be done as a separate gem.
