### ISSUE TITLE
can't require google/apis/drive_v2

### ISSUE THREAD

**Issue by prussiap** [google/google-api-ruby-client#266]
I'm feeling kind of dumb because I'm using Rails 4.2 and everything i'm reading seems to make this part of the process plug and go and easy. Yet I can't for the life of me get this gem to load.

I have a rails app. I need both omniauth2 access devise app to have users sign in etc. Then I need to use the API access on the admin main account (with all our company files) for offline access to create documents, download docs, and spreadsheets etc. This without possibly duplicating omniauth2 or users etc.. 

I have refresh tokens and tokens in omniauth but they expire so I need to do some voodoo to re-auth and get new token but sadly i don't get far.

My Gemfile has
 ``` 
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'google_drive'
gem 'google-api-client', '0.8.6', require: 'google/api_client' 
```
 
It all loads just fine when I do bundle update/install. 
I can require in console 
```
require "google_drive"
require "google/api_client"
```
just fine but I think those are not the same libraries as described.

When I try : 
```
require 'google/apis/drive_v2' 
I get:
LoadError: cannot load such file -- google/apis/drive_v2
from /Users/blah/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
``` 
I checked that the gems are installed and they are, they're also fine in bundle with no issues.

Sorry feeling dumb for asking but clearly i'm missing something. That or the order of the gems (or duplication) is causing an issue. 

ironically googling for this issue hasn't led me to an answer that works. 
This does work though so maybe there are alternate ways of getting to drive2 using this:
```
require "google/api_client"
@client = Google::APIClient.new
```
But then i'm lost on using my existing omniauth users (and the access/refresh tokens I have) to re-auth get new tokens and then get access to drive. Preferably without having to go from scratch again each time since i'm in offline mode.

Any help is appreciated

**Comment by sqrrrl** [comment]
google/apis/drive_v2 was introduced in 0.9.pre1. You're using 0.8.x.

You can still use Drive with 0.8.x of course. See https://developers.google.com/drive/web/quickstart/ruby for an example.

**Comment by prussiap** [comment]
@sqrrrl thanks. Question though: How do you know that documentation is for 0.8.x ? There is not a single line of text in there that specifies what versions this represents and if it's deprecated etc.. I've been going by this: https://developers.google.com/api-client-library/ruby/start/get_started which also has no info telling me what version of the API it represents. 

Feels like if both of these are for the same api yet totally different versions it would be important to disclose that somewhere? Is there a way to request that documentation change? Would certainly have saved me a day of frustration.

The link you sent does seem to be more appropriate for what I've been doing though.

**Comment by prussiap** [comment]
oh and sorry. when i force it to update to pre3 latest

```
gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- google/api_client (LoadError)
```

**Comment by prussiap** [comment]
ok for all those that are pulling their hair out or are on a low brain level like me. At some point (guessing 0.9pre1 or 2)

When the api changed the project for google-api-ruby-client combined the apis for drive and the client library. So when I was requiring drive after I had loaded api-ruby-client it broke since it was already added.. 

this got me there: https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

Sorry if i'm dumb asking these questions but I didn't get anything from either site that I was reading that specified the massive changes in the how the libraries are loaded, used and required.

the migration doc does indicate how to use each version but not explicitly for version changes.

anyway hope it helps others.

**Comment by olilogic77** [comment]
thanks prussiap - the migrating post you found is a lifesaver
