### ISSUE TITLE
Support batch custom call ids [v0.9]

### ISSUE THREAD

**Issue by rcaught** [google/google-api-ruby-client#267]
[`0.8.x` supports custom call ids on batch objects](https://github.com/google/google-api-ruby-client/blob/v0.8.6/lib/google/api_client/batch.rb#L120), but [I don't see support for it in `0.9`](https://github.com/google/google-api-ruby-client/blob/986a47c30ba226171b58f5b22f7c068b183c7a13/lib/google/apis/core/batch.rb#L58).

**Comment by sqrrrl** [comment]
Curious - what use case do you have in mind for these? The previous version had them mostly because the implementation was ported from one of the other client libraries. But given that the library manages pairing up requests/responses, there isn't too much value in specifying call IDs.

**Comment by rcaught** [comment]
Hi @sqrrrl,
Yeah, after reading your comment I just reevaluated how I was doing multiple level batching in some `0.8.x` code.  I now realise that I was doing unnecessary work with `call_id`'s and that the library is smarter than I expected!  :smile:
