### ISSUE TITLE
Connection hangs; never closes

### ISSUE THREAD

**Issue by jeremywadsack** [google/google-api-ruby-client#278]
Running under 0.8.x we had maybe 1 in 10,000 connections get stuck where they never timed out or completed. We set timeout to 120s for Faraday options in the gem, so I don't understand how can this ever get stuck. We've had connections open for _days_.

I opened [an issue with Faraday](https://github.com/lostisland/faraday/issues/510) on this, but then saw that Faraday is EOL. 

So we upgraded all of our code to 0.9pre3 to take advantage of Hurley in the hopes that would resolve the issue. Now we get this for about 50% of API calls.

Our settings are as follows:

```ruby
      @webmasters_service ||= Google::Apis::WebmastersV3::WebmastersService.new.tap do |client|
        client.request_options.timeout_sec = 120
        client.request_options.retries = 3
      end
```

**Comment by jeremywadsack** [comment]
It looks like the error rate is still fairly low, but when we switched over we must have hit something that caused successive hanging connections for a few hours. 

Any ideas on how this could happen if the timeout is set to 120s?

**Comment by sqrrrl** [comment]
One potential issue is I noticed open_timeout isn't being set. It exists in hurley's options, but isn't set by the api client library.

Could you try adding a call like

    @webmaster_service.client.request_options.open_timeout = 120

and see if that resolves the issue?

**Comment by jeremywadsack** [comment]
```
NoMethodError: undefined method `open_timeout=' for #<Google::Apis::RequestOptions:0x000000080b4368>
```

**Comment by sqrrrl** [comment]
Err, what was the code you actually tried? `open_timeout` doesn't exist on `Google::Apis::RequestOptions` but does on `Hurley::RequestOptions`. The code in the previous comment should have been giving you the underlying Hurley client/options.

**Comment by jeremywadsack** [comment]
My mistake, Steve. I had changed my constructor to this which was setting the `Google::Apis::RequestOptions`:

```ruby
    @webmasters_service ||= Google::Apis::WebmastersV3::WebmastersService.new.tap do |client|
        client.request_options.timeout_sec = 120
        client.request_options.retries = 3
        client.request_options.open_timeout = 120
      end
```

I changed that last line to this which doesn't crash:

```ruby
        client.client.request_options.open_timeout = 120
```

I'll run this through our system for a couple days and see if we've resolved the issue. 

Thanks, also, for the response and suggestion.

**Comment by jeremywadsack** [comment]
I think this is good @sqrrrl. We've run several million API calls and have not hit the error since this change.

I was going to open a PR with [this patch](https://github.com/google/google-api-ruby-client/compare/master...keylimetoolbox:hurley_open_timeout) but the CLA process was too complicated for such a simple change, so I thought I'd just let you write the code. :)

**Comment by sqrrrl** [comment]
Thanks for trying it out. I'll expose open_timeout in the next version.
