### ISSUE TITLE
How to use Contacts API ?

### ISSUE THREAD

**Issue by davidhq** [google/google-api-ruby-client#280]
Not clear at all and it's not in `generated/google/apis`

**Comment by sqrrrl** [comment]
Contacts API isn't supported by this library. It's based on an older data format (gdata) that was deprecated quite awhile ago. There are only a handful of Google APIs still using that format and there are no plans to add support for them in this library.

**Comment by davidhq** [comment]
In v0.8.6 I managed to use Contacts API with this library like here: https://gist.github.com/cantino/d1a63045fbfe5fc55a94

Now that I need creating and editing contacts, I couldn't figure out how to do it... https://developers.google.com/google-apps/contacts/v3/?hl=en#creating_contacts

I need POST requests... so is this possible to do manually either in 0.8.6 or in 0.9.0?

**Comment by sqrrrl** [comment]
There is a generic [`http`](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/base_service.rb#L181) method that can be used to make arbitrary requests in the same way that gist uses the old `execute` method. The format of the call is a little different, but you should be able to modify that gist without too much work.

**Comment by davidhq** [comment]
thank you... for now I managed to do everything I need with 0.8.6 .. maybe I will migrate to 1.0.0 when it's ready.. I now know which method to use
