### ISSUE TITLE
clear_calendar(calendar_id) does not work

### ISSUE THREAD

**Issue by JimW** [google/google-api-ruby-client#284]
clear_calendar(calendar_id) does not work.  
Be it primary or secondary, when owned by a service account.
results in "forbidden"

**Comment by sqrrrl** [comment]
Please provide additional details about the error and sample code to reproduce. Also, it's not clear if this is a client issue or an issue with the calendar API. What happens if you make the same call with curl or another tool?

**Comment by JimW** [comment]
OK, but first: this is what clear_calendar says it does: 
"Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account." 

I need to clear or truly delete all events on a secondary calendar owned by a service account.  I could not figure it out, so I just manually looped through all the events and deleted them.  The problem with that, is that the events still live, just marked as "cancelled".  This is a problem because if I then try to insert an event with the same id as one that is cancelled, it will fail.  Is there any way at all to truly delete for real, all events on a calendar?  Might it not be more clear to rename delete_event to cancel_event, since that is all that it's doing?  Is there any way at all to truly delete a calendar event? Is that what the "clear" in clear_calendar means?  

As a side note, I tried to just move all the cancelled events into a trash calendar, but then that caused a "cannotChangeOrganizer" error during the move.  I cannot just delete the whole calendar and create a new one, because then a new acl would need to be applied which would unnecessarily involve everyone subscribed.  I just want to delete all the events.  Is this possible?

**Comment by sqrrrl** [comment]
I'm not aware of any way to force deletion of a calendar event. IIRC deleted events are kept around for ~30 days as tombstone entries for clients that sync with the calendar. If they were instantly deleted, clients that only pull incremental updates would have no indication that an event is no longer valid.

Anyway, for help with the semantics of the calendar API I suggest asking on [StackOverflow](http://stackoverflow.com/questions/tagged/google-calendar) instead.
