### ISSUE TITLE
Provide a working example of analytics connection for the 0.9pre3 release

### ISSUE THREAD

**Issue by mihaibb** [google/google-api-ruby-client#291]
Every example here is using an older version of the gem but nothing for the latest release.
I have trouble setting up a basic connection using an access key.

A lot of classes have been moved or removed.

Can you provide an working example for the analytics service ?

**Comment by mperham** [comment]
Likewise.  We can't figure out how to set up authorization so this gem is impossible to use at the moment.  Please help!

**Comment by six7zero9** [comment]
agreed, help would be appreciated.

**Comment by mihaibb** [comment]
I've managed to figure it out how to use it.
Here are the steps:

1. Go to google developer console and create a new project.
2. Generate a service key ( I've used json key). 
3. When you generate the key an email address is created for the key. Go to analytics admin dashboard -> user management  and add that email address with read permissions.
4. Code
```

class GoogleApi
  attr_accessor :profile_id # Go to google analytics admin -> view settings 

  def google_api_key_path
    Rails.root.join('config', 'google_api_key.json').to_s
  end

  def google_api_key
    File.open(google_api_key_path, "r")
  end

  def authorization(scope)
    Google::Auth::ServiceAccountCredentials.new(json_key_io: google_api_key, scope: scope )
  end

  def ga_profile
    @ga_profile ||= "ga:#{profile_id}"
  end

  # Use this if you want to use the access token in javascript and use google js api without
  # oauth2 authorization
  def analytics_access_token
    analytics_service.authorization.access_token
  end

  def analytics_service
    scope = [
      'https://www.googleapis.com/auth/analytics.readonly'
    ]

    client = Google::Apis::AnalyticsV3::AnalyticsService.new

    client.authorization = authorization(scope)

    ## Request a token for our service account
    client.authorization.fetch_access_token!

    client
  end
end
```

**Comment by jeremyhaile** [comment]
We also can't figure out how to set up authorization when we already have an oauth token. This was easy in prior versions. How do you do it in this version?

Here's an example in the old API: 

```ruby
Google::APIClient.new(application_name: 'MyApp', application_version: '1.0').tap do |client|
    client.authorization.client_id = google_client_id
    client.authorization.client_secret = google_client_secret
    client.authorization.access_token = token if token
    client.authorization.refresh_token = refresh_token if refresh_token
end
```

How do you do this in the new API? When I try to do something similar, authorization is nil.

**Comment by mihaibb** [comment]
@jeremyhaile What service are you try to use ? Drive APi ?

**Comment by jeremyhaile** [comment]
@mihaibb I'm using the YouTubeV3 API.

**Comment by thebucknerlife** [comment]
@jeremyhaile did you figure this out?

**Comment by jeremyhaile** [comment]
@thebucknerlife yes, see the thread on this related issue: #279

Basically I do this after creating the client now:
```ruby
      if token
        client.authorization = Signet::OAuth2::Client.new(
          authorization_uri:    'https://accounts.google.com/o/oauth2/auth',
          token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
          client_id:            <client_id>,
          client_secret:        <client_secret>
        )
        client.authorization.access_token  = token
        client.authorization.refresh_token = refresh_token if refresh_token
      else
        client.key = <google_api_key>
      end
```

**Comment by thebucknerlife** [comment]
@jeremyhaile great thanks! does this gem handle getting a new access_token after the token expires?

I've got this working but wondering how I make sure I can continue to get analytics for my users without requiring authentication hourly

**Comment by jeremyhaile** [comment]
@thebucknerlife I need to do more testing, so I'm not 100% sure. It seemed like it was not refreshing the tokens automatically, but it is supposed to.

In my case, I'm rescuing from `Google::Apis::AuthorizationError` and then calling `client.authorization.fetch_access_token!` to ensure I refresh the token in case the library doesn't.
