### ISSUE TITLE
invalidArgument exception when creating Triggers in Google Tag Manager API

### ISSUE THREAD

**Issue by mpedrera** [google/google-api-ruby-client#297]
I am trying to populate a Google Tag Manager container via API. This involves creating variables, tags and triggers programmatically. 

I ~~almost~~ didn't have any issues with the `#create_tag` and `#create_variable` methods of the `TagmanagerService` class, but I'm struggling with the triggers, presumably because they have the most complex structure out of the three.

The steps followed have been:
 1. Instantiate `TagmanagerV1::Parameter` objects for the `parameter` arrays inside the trigger filter(s).
 2. Instantiate a `TagmanagerV1::Trigger` object, and set its attributes according to the example structure (this involves converting them to `snake_case` before).
 3. Call `TagmanagerService#create_trigger`
 4. **Get error back from the API: `Google::Apis::ClientError Exception: invalidArgument`**

With some debugging, I am able to see that the json output generated before making the request is not correct.

```ruby
# google-api-client-0.9.pre3/lib/google/apis/core/api_command.rb
# Before converting to JSON:
(byebug) pp request_representation.new(request_object)

#<Google::Apis::TagmanagerV1::Trigger::Representation:0x007fecd5a50270
 @represented=
  #<Google::Apis::TagmanagerV1::Trigger:0x007fecd7b93658
   @account_id="69231082",
   @container_id="1180351",
   @custom_event_filter=
    [{"type"=>"EQUALS",
      "parameter"=>
       [#<Google::Apis::TagmanagerV1::Parameter:0x007fecd7b93b08
         @key="arg0",
         @type=["TEMPLATE", "arg0", "{{_event}}"],
         @value="{{_event}}">,
        #<Google::Apis::TagmanagerV1::Parameter:0x007fecd7b93928
         @key="arg1",
         @type=["TEMPLATE", "arg1", "addToCart"],
         @value="addToCart">]}],
   @fingerprint="1431603290036",
   @name="EEC - addToCart",
   @trigger_id="8",
   @type="CUSTOM_EVENT">>
``` 

becomes this:
```ruby
# google-api-client-0.9.pre3/lib/google/apis/core/api_command.rb
JSON.parse(request_representation.new(request_object).to_json)
{"accountId"=>"69231082", "autoEventFilter"=>nil, "checkValidation"=>nil, "containerId"=>"1180351", "customEventFilter"=>[{"parameter"=>nil, "type"=>nil}], "enableAllVideos"=>nil, "eventName"=>nil, "filter"=>nil, "fingerprint"=>"1431603290036", "interval"=>nil, "limit"=>nil, "name"=>"EEC - addToCart", "triggerId"=>"8", "type"=>"CUSTOM_EVENT", "uniqueTriggerId"=>nil, "videoPercentageList"=>nil, "waitForTags"=>nil, "waitForTagsTimeout"=>nil}
```

There are many attributes being lost when converting to JSON. I have even tried creating the objects manually for the example [given in the docs](https://developers.google.com/tag-manager/api/v1/reference/accounts/containers/triggers/create#examples), and the result is the same.

**Comment by sqrrrl** [comment]
Can you share sample code for how you're creating the object? Without knowing what you're doing, it's a little hard to tell you what's wrong. That said, it looks like you did set some incorrect values, specifically  Parameter#type isn't an array, just a string.

There's an example of how to create a trigger at https://developers.google.com/tag-manager/api/v1/reference/accounts/containers/triggers/create#examples

Those examples are for Java & Python, but translated to this client it would look something like:

```ruby
require 'google/apis/tagmanager_v1'

T = Google::Apis::TagmanagerV1

arg0 = T::Parameter.new(type: 'template', key: 'arg0', value: '{{Page URL}}')
arg1 = T::Parameter.new(type: 'template', key: 'arg1', value: 'timed.html')

condition = T::Condition.new(type: 'contains', parameter: [arg0, arg1])

event_name = T::Parameter.new(type: 'template', value: 'gtm.timer')
interval = T::Parameter.new(type: 'template', value: '10000')
limit = T::Parameter.new(type: 'template', value: '10')

trigger = T::Trigger.new(name: 'Timer Trigger',
                         type: 'timer',
                         auto_event_filter: [condition],
                         event_name: event_name,
                         interval: interval,
                         limit: limit)

tag_manager = T::TagManagerService.new
#tag_manager.authorization = ...

account_id = '123456'
container_id = '54321'
tag_manager.create_trigger(account_id, container_id, trigger)
```

That would end up sending the following JSON to https://www.googleapis.com/tagmanager/v1/accounts/12345/containers/abc/triggers

```json
{
  "autoEventFilter": [
    {
      "parameter": [
        {
          "key": "arg0",
          "type": "template",
          "value": "{{Page URL}}"
        },
        {
          "key": "arg1",
          "type": "template",
          "value": "timed.html"
        }
      ],
      "type": "contains"
    }
  ],
  "eventName": {
    "type": "template",
    "value": "gtm.timer"
  },
  "interval": {
    "type": "template",
    "value": "10000"
  },
  "limit": {
    "type": "template",
    "value": "10"
  },
  "name": "Timer Trigger",
  "type": "timer"
}
```

Anyway, hope that helps...

**Comment by mpedrera** [comment]
Thanks @sqrrrl , by looking at your snippet I've been able to solve it by instantiating `Condition` objects for filters, which I was missing.

**Comment by ParthivSavani4582** [comment]
@sqrrrl I want to trigger an existing event with event_name and parameters from controller action. How to do that?
