### ISSUE TITLE
Using Drive API with Omniauth/Devise instead of Signet/GoogleAuth

### ISSUE THREAD

**Issue by pchowdhry** [google/google-api-ruby-client#298]
Hi I;m trying to implement some drive functionality and already have omniauth devise integrated into my app. I've been able to get the token process working, and have successfully retrieved both the access and refresh tokens.  I've been able to use these in curl to successfully call the drive APIs.

I'm hoping to use the ruby client however can't figure out how to use (pass) the access token to the library. The documentation has a one liner using the google libraries, but nothing about how to pass in a token.

Hoping its possible to simply pass in a valid token and use the Ruby APIs.

Thanks

**Comment by sqrrrl** [comment]
See #296 which has some snippets on how to adapt credentials from another library.
