### ISSUE TITLE
ACLRule - role Documentation Error

### ISSUE THREAD

**Issue by JimW** [google/google-api-ruby-client#300]
For the ACLRule for the role, it says: 

"reader" - Provides read access to the calendar. Private events will appear to users with reader access, but event details will be hidden.
__ 

It should say that event details will be "visible". That makes sense and is currently how it's working.
Jim

**Comment by sqrrrl** [comment]
Descriptions are autogenerated based on the API definition. If there's an issue with how a field is described, please see the support options for that particular API.
