### ISSUE TITLE
Version 0.9 should be called 1.0 instead following semantic versioning

### ISSUE THREAD

**Issue by gimite** [google/google-api-ruby-client#301]
Hello team,

It looks 0.9 API is incompatible with 0.8 or before:
https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

Rubygems suggests gems to follow Semantic Versioning:
http://guides.rubygems.org/patterns/#semantic-versioning

which suggests to update MAJOR version when you make incompatible API changes:
http://semver.org/
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

So 0.9 should be called 1.0 instead, I believe. It will prevent users who specifies "google-api-client ~> 0.8" etc. in their Gemfile or gemspec from braking their product, by accidentally updating to google-api-client 0.9 without required migration.

**Comment by sqrrrl** [comment]
Nope. See #4 as semver.org -- Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by gimite** [comment]
Oh I see. Thanks!

**Comment by sesam** [comment]
Rant: So sad this wasn't published as a new gem (with a new name), and the old could probably easily function at least at some basic level as a wrapper for the new, hot, more modular rewrite.

I only recall google releasing ruby gems that must be require:d with a special string, but if google must have a string, at least please don't change it inside the same gem.
