### ISSUE TITLE
Where is the email settings API

### ISSUE THREAD

**Issue by Carpela** [google/google-api-ruby-client#304]
Doesn't seem to be in the api list?

**Comment by Carpela** [comment]
Just seen your response to my other issue. Wondered where that had gone... 

Any hints on how one accesses with a service account in the absence of the api being supported with a client? 

Google sort of reccommend quite strongly not doing this without a library... 

Note: These service-account scenarios require applications to create and cryptographically sign JSON Web Tokens (JWTs). We strongly encourage you to use a library to perform these tasks. If you write this code without using a library that abstracts token creation and signing, you might make errors that would have a severe impact on the security of your application. For a list of libraries that support this scenario, see the service-account documentation.

**Comment by sqrrrl** [comment]
You can use the library for the authorization support, but it won't give you much in the way of constructing requests or parsing responses.

If you *just* want support for service accounts, see https://github.com/google/google-auth-library-ruby. You can go a little further using this library and treat it as a slightly smarter HTTP client. There's a generic method on the base service class called [`http`](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/base_service.rb#L158) which hands things like auth, retries, etc.
 You'll still have to build the URLs correctly and parse the XML yourself though.

**Comment by Carpela** [comment]
I tried using this for authorisation support.
Got the auth_key and tried to authenticate manually and the email settings API still fails.
Have an open call with google support on it aswell.

**Comment by Carpela** [comment]
Can I use the auth library alongside the normal client without any conflicts?

**Comment by sqrrrl** [comment]
Yes.

Happy to help with the auth questions, but need to provide a lot more information than simply saying it fails...

**Comment by Carpela** [comment]
Ok. 
Have an issue which is under investigation by google support. 

I can generate an access_token for my service account.

I can authenticate with said access_token for drive api
I cannot authenticate with access_token for Email Settings api using the same method.

i.e. 
https://www.googleapis.com/drive/v2/files?access_token=gobbledygook

Works fine

https://apps-apis.google.com/a/feeds/emailsettings/2.0/example.com/bob/filter?access_token=gobbledygook
Doesn't work

Permissions are (as far as I can tell) correctly set for the domain.
