### ISSUE TITLE
http_proxy not work issue(version: 0.9.pre3)

### ISSUE THREAD

**Issue by mylake** [google/google-api-ruby-client#306]
I want to add proxy settings

uri_proxy = URI.parse('http://myproxy.com')
Google::Apis::ClientOptions.default.proxy_url = uri_proxy
adx_buyer_service = Google::Apis::AdexchangebuyerV1_3::AdExchangeBuyerService.new

but not working. Am I using correctly?

**Comment by sqrrrl** [comment]
What error(s) are you getting?

**Comment by mylake** [comment]
my code like this:

```
key = Google::APIClient::KeyUtils.load_from_pkcs12(KEY_FILE, KEY_SECRET)

  auth_options = {
      :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      :audience => 'https://accounts.google.com/o/oauth2/token',
      :scope => 'https://www.googleapis.com/auth/adexchange.buyer',
      :issuer => SERVICE_ACCOUNT_EMAIL,
      :signing_key => key
  }

  authorization = Signet::OAuth2::Client.new(auth_options)

  Google::Apis::ClientOptions.default.application_name = "Ruby #{API_NAME} samples: #{$0}"
  Google::Apis::ClientOptions.default.application_version = "1.0.0"

  uri_proxy = URI.parse('http://myproxy.com')
  Google::Apis::ClientOptions.default.proxy_url = uri_proxy

  adx_buyer_service = Google::Apis::AdexchangebuyerV1_3::AdExchangeBuyerService.new
  adx_buyer_service.authorization = authorization

  creative_object = Google::Apis::AdexchangebuyerV1_3::Creative.new(google_creative)

  response = adx_buyer_service.insert_creative(creative_object)
```

  and the result is: 

  Network is unreachable - connect(2) for "accounts.google.com" port 443

  Am I using correctly?

**Comment by sqrrrl** [comment]
Currently the oauth client uses a separate connection. Easiest way to work around this is to set the proxy option on Faraday's default connection. Should be something like:

```ruby
Faraday.default_connection = Faraday.new do |conn|
  conn.proxy 'http://myproxy.com'
end
```

**Comment by mylake** [comment]
I have modified my code 

Faraday.default_connection = Faraday.new do |conn|
  conn.proxy 'http://myproxy.com'
end

but I got another error: 
```
#<Signet::AuthorizationError: Unexpected status code: .  Server message:
grant_type=............................................
```
Am I using correctly?

**Comment by sqrrrl** [comment]
Sorry, you'll need to do more debugging on your end -- can you make requests through your proxy using curl or other clients? What about using Faraday or Net::HTTP directly?

The fact that behavior changed is a good thing -- it looks like it's trying to use the proxy. But whether or not your proxy URL is correct or there are other issues going on I can't tell you.
