### ISSUE TITLE
Segfault when calling insert_calendar with String-key hash

### ISSUE THREAD

**Issue by feifanzhou** [google/google-api-ruby-client#307]
Not sure if this an issue with the gem itself, but I can consistently reproduce this issue: 
https://bugs.ruby-lang.org/issues/11675

If the hash keys are symbols, it throws `ArgumentError (unknown keyword: summary)`, which is a relevant error here.

**Comment by sqrrrl** [comment]
The segfault itself is a ruby issue. That said, the [README](https://github.com/google/google-api-ruby-client#hashes) is clear in saying hash keys must be symbols, not strings.
