### ISSUE TITLE
Unknown keyword error raised when it shouldn't be

### ISSUE THREAD

**Issue by feifanzhou** [google/google-api-ruby-client#308]
def create_calendar(calendar_name)
      entry = { summary: calendar_name }
      created_calendar = calendar.insert_calendar(entry)  # Error thrown here
      # …..
    end

`ArgumentError (unknown keyword: summary)` is thrown here, even though [it looks like](https://github.com/google/google-api-ruby-client/blob/549e4bd11343715ab3f69eb11feae7695686d2d4/generated/google/apis/calendar_v3/representations.rb#L193) Calendar objects have a `summary` property.

**Comment by sqrrrl** [comment]
Ruby quirk with hash parameters as last arg -- it tries to expand it into method parameters.

Either:

*    Create a Calendar object instead of a hash:
```ruby
entry = Google::Apis::CalendarV3::Calendar.new(summary: 'foo')
```
*   Pass another option like fields (good to always specify fields anyway) to disambiguate.
```ruby
created_calendar = calendar.insert_calendar(entry, fields: 'id') # Only return the id attribute
```
