### ISSUE TITLE
Errors raised in callbacks are swallowed

### ISSUE THREAD

**Issue by afn** [google/google-api-ruby-client#309]
Given an instance of `Google::Apis::GmailV1::GmailService`:

```
gmail.get_user_message('me', '12345') { |result,err| if err then puts err.message; raise err; end }
```

will print `notFound` but the re-raised error is swallowed, presumably because of the `proc.nil?` check here: https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/http_command.rb#L111

**Comment by afn** [comment]
Note that the behavior is different (and correct, I think) when the request is batched:

```
gmail.batch do
  gmail.get_user_message('me', '12345') { |result,err| if err then puts err.message; raise err; end }
end
```

The above both prints `notFound` and re-raises the error.

**Comment by afn** [comment]
Another bug that's closely related to this one is that in the event of a retriable error, the callback is invoked multiple times (possibly several times with an error and then with a success).  This doesn't seem right; from the caller's perspective, the request either fails or succeeds.

The call to `success` or `error` should happen in `execute`, not in `execute_once`.

**Comment by sqrrrl** [comment]
@afn  Planning another release soon -- can you sign CLA so I can merge your changes?

**Comment by afn** [comment]
Done
