### ISSUE TITLE
Resumable uploads should use the documented protocol

### ISSUE THREAD

**Issue by kiwidrew** [google/google-api-ruby-client#311]
The `Google.Apis.Core.ResumableUploadCommand` class appears to be using an undocumented method for initiating and controlling the resumable upload.  The officially-supported resumable upload protocol (documented, for instance, in the ["Upload Files" section of the Drive REST API guide](https://developers.google.com/drive/web/manage-uploads#resumable)) relies on the standard `Content-Length` and `Content-Range` HTTP headers.  This library instead seems to use headers such as `X-Goog-Upload-Command` and `X-Goog-Upload-Offset`:

    # Implementation of the resumable upload protocol
    class ResumableUploadCommand < BaseUploadCommand
      UPLOAD_COMMAND_HEADER = 'X-Goog-Upload-Command'
      UPLOAD_OFFSET_HEADER = 'X-Goog-Upload-Offset'
      BYTES_RECEIVED_HEADER = 'X-Goog-Upload-Size-Received'
      UPLOAD_URL_HEADER = 'X-Goog-Upload-URL'
      UPLOAD_STATUS_HEADER = 'X-Goog-Upload-Status'

I can't find any documentation whatsoever regarding these request headers.  Is there any particular reason why this library isn't using the standard and documented method?

**Comment by sqrrrl** [comment]
Short answer is it is a valid protocol, don't worry about it :) Longer answer is...long. There are a lot of moving parts with evolving protocols, docs for multiple APIs, client libraries in multiple languages, etc and things don't always happen at the same time.
