### ISSUE TITLE
Uploading videos to YouTube w/ Ruby and v3 API results in Unauthorized error

### ISSUE THREAD

**Issue by samullen** [google/google-api-ruby-client#313]
Let me start by apologizing. I don't think this is an actual issue, I just can't get this to work. I've posted the question to StackOverflow [here](http://stackoverflow.com/questions/33921697/uploading-videos-to-youtube-w-ruby-and-v3-api-results-in-unauthorized-error) but have not received an answer of any kind. 

I'm trying to create a service which will upload videos to my client's YouTube account.

Here's what I've done so far:

* I'm using Google Ruby gems - googleauth and google-api-client - and have the "service account" set up.
* I've set the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the downloaded json file provided when setting up the service account
* I'm requiring the correct library: google/apis/youtube_v3

Here's the code:

```
class Video < ActiveRecord::Base

  def upload_to_youtube!(force=false)
    if self.youtube_key.blank? || force
      yt = Google::Apis::YoutubeV3::YouTubeService.new
      scopes =  [
        "https://www.googleapis.com/auth/youtube", 
        "https://www.googleapis.com/auth/youtube.force-ssl", 
        "https://www.googleapis.com/auth/youtube.upload"
      ]
      authorization = Google::Auth.get_application_default(scopes)
      yt.authorization = authorization

      title = "Clever Title"
      description = "Lorem ipsum dolor"
      file_path = "/path/to/mp4/file.mp4"

      metadata = {
        snippet: {
          title: title,
          description: description,
        },
      }

      yt.insert_video("id", metadata, upload_source: file_path, content_type: "video/mp4", options: {retries: 3})
    else
      true
    end
  end
end
```

When running this, I get the following error:

```
Sending upload start command to https://www.googleapis.com/upload/youtube/v3/videos?part=id
Upload status final
Error - #<Google::Apis::AuthorizationError: Unauthorized>

Retrying after authentication failure
Sending upload query command to
Error - #<NoMethodError: undefined method `+' for nil:NilClass>

NoMethodError: undefined method `+' for nil:NilClass
from /Users/samullen/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1532:in `addr_port'
```

I'm at a loss and I'm running out of time. I don't know if there's something else with OAuth I need to do, a sacrifice which needs to be made, or a jig that needs to be danced. I'm just stumped.

**Comment by sqrrrl** [comment]
Most likely the issue is you're getting a [youtubeSignupRequired](https://developers.google.com/youtube/v3/docs/errors) error due to trying to use a service account.

That said, it looks like a bug with resumable upload masking the original error. It should be keeping the status as start on the retry, not trying to resume. I'll fix that.

**Comment by samullen** [comment]
If I'm understanding the error description correctly, YouTube doesn't allow service accounts to upload videos, right?

> This error is commonly seen if you try to use the OAuth 2.0 Service Account flow. YouTube does not support Service Accounts, and if you attempt to authenticate using a Service Account, you will get this error.

I'll look into alternate solutions. Thanks.
