### ISSUE TITLE
faraday error

### ISSUE THREAD

**Issue by nvedul2** [google/google-api-ruby-client#317]
Loading development environment (Rails 3.2.19)
2.1.7 :001 > Account.create(:email => 'researchfive82@gmail.com', :password => 'research.1', :android_id => '3c6cfa9c6f7a721a')
Faraday::Error::ConnectionFailed: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /Users/uicuser/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:75:in `perform_request'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:38:in `call'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday/request/url_encoded.rb:14:in `call'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday/connection.rb:118:in `post'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/faraday-0.8.9/lib/faraday.rb:24:in `method_missing'
	from /Users/uicuser/Desktop/playdrone-master/app/models/account.rb:40:in `login!'
	from /Users/uicuser/Desktop/playdrone-master/app/models/account.rb:68:in `auth_token'
	from /Users/uicuser/Desktop/playdrone-master/app/models/account.rb:21:in `block in create'
	from /Users/uicuser/Desktop/playdrone-master/app/models/account.rb:20:in `tap'
	from /Users/uicuser/Desktop/playdrone-master/app/models/account.rb:20:in `create'
	from (irb):1
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from /Users/uicuser/.rvm/gems/ruby-2.1.7/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
 i am not sure why this error is coming

**Comment by sqrrrl** [comment]
I don't even see the API client in that stack... need waaay more info and/or sample code to reproduce.
