### ISSUE TITLE
Google::Apis::ClientError: Invalid request

### ISSUE THREAD

**Issue by Rajniktc** [google/google-api-ruby-client#318]
classroom = Google::Apis::ClassroomV1beta1 # Alias the module      
service = classroom::ClassroomService.new
courses = service.list_courses(page_size:  0, options: { authorization: auth_client })

Error:-

Sending HTTP get https://classroom.googleapis.com/v1beta1/courses?pageSize=0
404
#<Hurley::Response GET https://classroom.googleapis.com/v1beta1/courses?pageSize=0 == 404 (1587 bytes) 1282ms>
Caught error Invalid request
Error - #<Google::Apis::ClientError: Invalid request>

**Comment by Rajniktc** [comment]
Generated requested url must be https://classroom.googleapis.com/v1/courses?pageSize=0 instead of https://classroom.googleapis.com/v1beta1/courses?pageSize=0

**Comment by sqrrrl** [comment]
Updated the classroom API to v1 in 0.9.pre4
