### ISSUE TITLE
Is there any plan to update the compute_beta api so that knife-google can utilize the subnet functionality currently in beta?

### ISSUE THREAD

**Issue by jameshcoppens** [google/google-api-ruby-client#321]

**Comment by sqrrrl** [comment]
I'll add it for the list of APIs and generate the beta version. That said, the knife-google plugin is using an older version of the client that doesn't strictly require it.

**Comment by jameshcoppens** [comment]
Can I help integrate that API into the code base?  I'd obviously need some direction on your part.
