### ISSUE TITLE
Docs Missing for Google API Ruby Client

### ISSUE THREAD

**Issue by danielbonnell** [google/google-api-ruby-client#324]
Hello,

I'm trying to integrate the Ruby API Client into my app but the docs seems to be missing or inaccessible. 
If I follow the links from [this page](https://developers.google.com/api-client-library/ruby/start/get_started) they are broken. Additionally, a [quick search](http://www.rubydoc.info/find/github?q=google-api-ruby) of RubyDocs.info turns up nothing.

Thanks!

**Comment by sqrrrl** [comment]
They're back. Weird issue with rubydoc.info -- local doc generation is fine, but for some reason it kept failing to update there.
