### ISSUE TITLE
Missing instructions on Google Analytics and opening Wiki gives 500 error.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [google/google-api-ruby-client#328]
Hello.

I want to use this gem to fetch data from my Google Analytics dashboard. In this page, there is no instructions of how to use this gem for Gogle Analytics. When I open Wiki it gives 500 error. I search others tutorials and they are outdated.

Also when I open ruby-doc it says that page does not exist.

This situation reminds me old quest games: You don't know what to do, you don't know where you are and you don't know how to do something. You have to guess.

Please, I mean, PLEASE add step by step guide of getting info from analytics of this gem.

**Comment by pdcoutinho** [comment]
+1

**Comment by icco** [comment]
This doesn't solve the issue for analytics, but https://github.com/google/google-api-ruby-client-samples has some examples to get you in the right direction at least.

**Comment by StefanoOrdine** [comment]
+1

**Comment by sqrrrl** [comment]
Added a simple analytics sample to the samples directory.

**Comment by SuperMasterBlasterLaser** [comment]
:+1:

**Comment by StefanoOrdine** [comment]
Also this turned out very useful for me! http://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/AnalyticsV3
