### ISSUE TITLE
Hurley author is shutting down his project

### ISSUE THREAD

**Issue by xeron** [google/google-api-ruby-client#336]
Just wondering if it will be an issue in the future.

https://github.com/lostisland/hurley/issues/43

**Comment by sqrrrl** [comment]
Thanks for the heads up. It's not the end of the world since Hurley isn't directly exposed in the API. I'll likely just switch to use HTTPClient directly. Faraday doesn't yet support streaming responses yet which is a problem for APIs like Drive, Storage, etc. that can return large media blobs.

**Comment by aaronchi** [comment]
You may want to check out https://github.com/httprb/http

**Comment by cedricpim** [comment]
Hi @sqrrrl, any estimation when this switch is going to happen? 
I was trying to update to the new version of the gem but my tests are relying on [VCR](https://github.com/vcr/vcr) which does not support Hurley and was wondering if it is worth it to look into that or wait.

Thanks.

**Comment by sqrrrl** [comment]
You should be able to use VCR via webmock today. Hurley & Faraday are just wrappers around other HTTP client libraries. Right now I have Hurley wired to use HTTPClient, and from a VCR perspective just treat the library as if it were using HTTPClient directly.

As for switching off Hurley, I have another branch locally where I'm making some changes to get rid of it. Mostly there (all but 2 tests pass) but not in any rush to get it done.

**Comment by cedricpim** [comment]
I ended up noticing the problem was not specifically with Hurley but I think might be with the streaming (VCR body of the response is empty). 
Thanks :+1:

**Comment by sqrrrl** [comment]
FYI, pushed the first pass of this on branch httpclient. Still need to do a lot more testing (specifically batching) against some live APIs, but it's there if anyone is curious and wants to try it out.

**Comment by jharbert** [comment]
:+1: @sqrrrl - Tested the httpclient branch against my code and all seems well, it also fixes the VCR issues described above.  Will keep testing it out.

**Comment by icco** [comment]
I'll give this a try on [fog-google](https://github.com/fog/fog-google).

**Comment by cedricpim** [comment]
Regarding the VCR issues, a fix was merged into webmock master branch and it is working good from it. This was the fix: https://github.com/bblimke/webmock/pull/582

**Comment by sqrrrl** [comment]
Thanks!

**Comment by blowmage** [comment]
Is moving from Hurley to HTTPClient still going to happen?

**Comment by sqrrrl** [comment]
Yes, just waiting for the next release of HTTPClient which contains a fix I need for resumable media downloads to work correctly.

**Comment by sqrrrl** [comment]
Hurley removed in v0.10 branch

**Comment by blowmage** [comment]
@sqrrrl Is there a timeline for a v0.10 release?

**Comment by sqrrrl** [comment]
Not sure. Maybe 2 or 3 weeks.

**Comment by JanStevens** [comment]
Any update on this? Hurley is not maintained at all and pretty much dead.
Also any google project lib uses this client.

Excon is a pretty good alternative?

**Comment by TheCorp** [comment]
We're on 0.11 now and I still see Hurley being used, can you comment on the status?

**Comment by saicheems** [comment]
I'll get this done as soon as I can

**Comment by TheCorp** [comment]
Awesome thanks!
