### ISSUE TITLE
Translate service API do not work

### ISSUE THREAD

**Issue by mbigatti** [google/google-api-ruby-client#341]
Example code:

    #!/usr/bin/ruby
    require 'google/apis/translate_v2'

    translate = Google::Apis::TranslateV2::TranslateService.new
    translate.key = 'key'
    result = translate.list_translations(source: 'en', target: 'es', q: 'Hello world!')
    puts result.translations.first.translated_text`

fails with this error:
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9/generated/google/apis/translate_v2/service.rb:157:in `list_translations': wrong number of arguments (1 for 2) (ArgumentError)
	from ./test.rb:7:in `<main>'

**Comment by sqrrrl** [comment]
Fixed the snippet in the README. There's a working sample for translate in the samples dir too.
