### ISSUE TITLE
`require': cannot load such file -- google/api_client

### ISSUE THREAD

**Issue by samcambridge** [google/google-api-ruby-client#343]
I've been looking through issues/googling and I've had no luck resolving this issue so I thought I'd make a ticker, apologies if it's been covered somewhere and I've missed it.

Whilst installing the gem and trying to run `rails s` I'm getting the error `require': cannot load such file -- google/api_client`

This error appears after version `0.9.pre1` and occurs all the way up to `0.9.1`, unfortunately if I bump it down I get a similar issue but with the calendar api. 

First off here is how I'm including it in my gemfile (which could be wrong):
```
gem 'google-api-client', '0.9.1', require: ['google/api_client', 'google/api_client', 'google/apis/calendar_v3', 'google/apis/plus_v1']
```

If I remove the requires and test requiring them in `rails c` I get the same error as I do if I try and require them in the app.

If it helps my ruby version is:
```ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]```.

Would anyone have any ideas as to why I'm getting this?

**Comment by sqrrrl** [comment]
Just remove google/api_client from the list of requires.

```
gem 'google-api-client', '0.9.1', require: ['google/apis/calendar_v3', 'google/apis/plus_v1']
```

**Comment by samcambridge** [comment]
Yup, sorry. I should have mentioned. That gives me ```uninitialized constant Google::APIClient``` which led me to start requiring it in the first place.

It happens when calling ` Google::APIClient.new` which I've taken from countless examples, has this changed in recent versions?

**Comment by sqrrrl** [comment]
Yes. See https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md
