### ISSUE TITLE
cannot load such file -- google/api_client (LoadError)

### ISSUE THREAD

**Issue by Rockyyost** [google/google-api-ruby-client#348]
Up updated my gem file to google-api-ruby-client version 0.9.1.
When starting the application, I know get the below error. 

Let me know if you need any other information.

The error and trace:

/Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require': cannot load such file -- google/api_client (LoadError)
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/ryost/Documents/repositories/nightingale/config/application.rb:14:in `<top (required)>'
	from /Users/ryost/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ryost/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/cli.rb:231:in `boot_system'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/cli.rb:49:in `run'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/bin/sidekiq:12:in `<top (required)>'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/bin/Sidekiq:23:in `load'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/bin/Sidekiq:23:in `<main>'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryost/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sqrrrl** [comment]
See the [migration guide](https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md) for moving between 0.8.x and 0.9.x

**Comment by benjaminchan** [comment]
Attempting to follow the first example in the migration guide.  Using 0.9.1.  

Any chance you might tell me what I'm doing incorrectly? 

1.9.3-p551 :001 > require 'google/apis/drive_v2'
SyntaxError: /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: syntax error, unexpected tLABEL, expecting ')'
...f get_about(include_subscribed: nil, max_change_id_count: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
..._about(include_subscribed: nil, max_change_id_count: nil, st...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
... nil, max_change_id_count: nil, start_change_id: nil, fields...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
...unt: nil, start_change_id: nil, fields: nil, quota_user: nil...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
...rt_change_id: nil, fields: nil, quota_user: nil, user_ip: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
..., fields: nil, quota_user: nil, user_ip: nil, options: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
... quota_user: nil, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:87: Can't assign to nil
...il, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:124: syntax error, unexpected tLABEL
...    def get_app(app_id, fields: nil, quota_user: nil, user_i...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:124: Can't assign to nil
...ef get_app(app_id, fields: nil, quota_user: nil, user_ip: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:124: Can't assign to nil
..., fields: nil, quota_user: nil, user_ip: nil, options: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:124: Can't assign to nil
... quota_user: nil, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:124: Can't assign to nil
...il, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: syntax error, unexpected tLABEL, expecting ')'
...ist_apps(app_filter_extensions: nil, app_filter_mime_types: ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
...pps(app_filter_extensions: nil, app_filter_mime_types: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
...il, app_filter_mime_types: nil, language_code: nil, fields: ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
...types: nil, language_code: nil, fields: nil, quota_user: nil...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
...anguage_code: nil, fields: nil, quota_user: nil, user_ip: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
..., fields: nil, quota_user: nil, user_ip: nil, options: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
... quota_user: nil, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:170: Can't assign to nil
...il, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:207: syntax error, unexpected tLABEL
...f get_change(change_id, fields: nil, quota_user: nil, user_i...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:207: Can't assign to nil
..._change(change_id, fields: nil, quota_user: nil, user_ip: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:207: Can't assign to nil
..., fields: nil, quota_user: nil, user_ip: nil, options: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:207: Can't assign to nil
... quota_user: nil, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:207: Can't assign to nil
...il, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: syntax error, unexpected tLABEL, expecting ')'
...f list_changes(include_deleted: nil, include_subscribed: nil...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...t_changes(include_deleted: nil, include_subscribed: nil, max...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...: nil, include_subscribed: nil, max_results: nil, page_token...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...scribed: nil, max_results: nil, page_token: nil, spaces: nil...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
..._results: nil, page_token: nil, spaces: nil, start_change_id...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
..., page_token: nil, spaces: nil, start_change_id: nil, fields...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...ces: nil, start_change_id: nil, fields: nil, quota_user: nil...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...rt_change_id: nil, fields: nil, quota_user: nil, user_ip: ni...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
..., fields: nil, quota_user: nil, user_ip: nil, options: nil, ...
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
... quota_user: nil, user_ip: nil, options: nil, &block)
...                               ^
/Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2/service.rb:255: Can't assign to nil
...il, user_ip: nil, options: nil, &block)
...                               ^
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/google-api-client-0.9.1/generated/google/apis/drive_v2.rb:15:in `<top (required)>'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
	from (irb):1
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.11/lib/rails/commands/console.rb:47:in `start'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.11/lib/rails/commands/console.rb:8:in `start'
	from /Users/benjaminchan/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.11/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by sqrrrl** [comment]
@benjaminchan - Ruby 1.9.3 is no longer supported by this lib or even at ruby-lang.org. It hit it's EOL a year ago. Even 2.0 is about to be EOL'd. Suggest updating to 2.2+

**Comment by gxbe** [comment]
I'm seeing this in 2.2.3 

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d OpenJDK 64-Bit Server VM 25.72-b05 on 1.8.0_72-internal-b05 +jit [linux-amd64]

maybe a JRuby bug ?
