### ISSUE TITLE
discovery/resource.rb:58 wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by Rockyyost** [google/google-api-ruby-client#349]
I'm trying to pull the ads list and I'm using code that is similar to the sample Ruby code provided.

Below is the code I am trying to run:

    # Construct the request
    request = dfareporting.ads.list(
      :active => true,
      :profileId => profile_id,
      :advertiserId => advertiser_id
    )

    loop do
      result = request.execute()

      # Display results
      result.data.ads.each do |ad|
        puts 'Found ad with ID %d and name "%s".' % [ad.id, ad.name]
        
      end

      token = result.next_page_token

      break unless token and result.data.ads.any?
      request = result.next_page
    end

I get the  following error:

wrong number of arguments (1 for 0)
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/google-api-client-0.8.6/lib/google/api_client/discovery/resource.rb:58:in `block (2 levels) in initialize'
/Users/ryost/Documents/repositories/nightingale/app/workers/dcm_get_dimensions.rb:24:in `get_ads'
/Users/ryost/Documents/repositories/nightingale/app/workers/dcm_get_dimensions.rb:13:in `perform'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:150:in `execute_job'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/logging.rb:30:in `with_context'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:132:in `call'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:127:in `block in process'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:166:in `stats'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:126:in `process'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:79:in `process_one'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:67:in `run'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:16:in `watchdog'
/Users/ryost/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:24:in `block in safe_thread'

It looks like the method I'm using does expect more than one param, plus it's the way in the sample code. But there's something deeper in the ruby gem that does not. 

First, I'm I coding this wrong and not seeing it? Or is there an error in the gem? If there is an error, is there a work around?

Thanks!

**Comment by sqrrrl** [comment]
What was line 24 in your `dcm_get_dimensions.rb` file?

**Comment by Rockyyost** [comment]
That's this line:

request = dfareporting.ads.list(
  :active => true,
  :profileId => profile_id,
  :advertiserId => advertiser_id
)

**Comment by sqrrrl** [comment]
Looks like you're mixing calling styles in the API - you're using the service-style calls, but not actually creating the service correctly.

My hunch is you have some code before that which looks like:
```ruby
client = Google::APIClient.new
dfareporting = client.discovered_api('dfareporting', 'v2.3')
```

That was the only way I could reproduce that error (and the only way it would make sense from looking at the code.)

Given the way the rest of the code looks, you should have something like:

```ruby
dfareporting = Google::APIClient::Service.new('dfareporting', 'v2.3')
```

Starting with 0.9 there's only way to do things so it should be simpler. If you want to migrate to 0.9, the code would look something like (note: I haven't actually run this, so may contain errors ;)

```ruby
require 'google/apis/dfareporting_2_3/'

dfa = Google::Apis::DfareportingV2_3:: DfareportingService.new
dfa.authorization = ... # your credentials

next_page_token = nil
loop do
  result = dfa.list_ads(profile_id, active: true, advertiser_id: advertiser_id, page_token: next_page_token)
  # Display results
  result.ads.each do |ad|
    puts 'Found ad with ID %d and name "%s".' % [ad.id, ad.name]
  end

  next_page_token = result.next_page_token
  break if next_page_token.nil?
end
```
