### ISSUE TITLE
Issue with Task API going from completed to needsAction

### ISSUE THREAD

**Issue by priceflex** [google/google-api-ruby-client#351]
After googling a bit I found that the API requires you to send a nil or NULL on the completed parameter along with the status of "needsAction" in order to change it.

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/tasks_v1/classes.rb
I believe this setter method is preventing a nil from being sent when I want a nil to be sent 
args[:completed] unless args[:completed].nil?

I also tried sending a blank string and it says it's invalid as well. 
Error - #<Google::Apis::ClientError: invalid: Invalid value for: Invalid format: ""> - Status 400

Your help is greatly appreciated.

Thanks,
Steve

**Comment by sqrrrl** [comment]
The client does allow nils to be sent, but you're right that new/update are an issue. Those should be changed to check if the key is present rather than the value nil or not.

Explicitly setting the attribute to nil outside new/update! should work though.

```ruby
task = Google::Apis::TasksV1::Task.new(status: 'needsAction)
task.completed = nil
```

**Comment by priceflex** [comment]
Thanks! I'll try that and i'll let you know.

**Comment by sqrrrl** [comment]
Fixed the templates and will regenerate the services for the next release.

Also, LMK if any issues with the previous suggestion
