### ISSUE TITLE
'View on GitHub' links in docs broken

### ISSUE THREAD

**Issue by akostadinov** [google/google-api-ruby-client#353]
Hello, excuse me for using this venue, but I couldn't find it in any docs. Could you point at the tool used to generate the nice API documentation [1]?

btw links "[View on GitHub]" do not work in the documentation. At least reported a real issue :smile: 

[1] http://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ComputeV1/ComputeService

**Comment by sqrrrl** [comment]
Docs are generated with [yardoc](http://yardoc.org/).

Thanks for pointing out the broken github links. I'll take a look and see if I can get those fixed.

**Comment by akostadinov** [comment]
@mattwhisenhunt , why did you close the issue? The github links are still broken as far as I can tell?

**Comment by mattwhisenhunt** [comment]
Looks like all Github links on that site are broken not. I am not sure what that has to do with this library.

**Comment by akostadinov** [comment]
@mattwhisenhunt , you mean broken or "not"?

Original link I give in description - I see github links broken there. I checked some other [random project](http://www.rubydoc.info/github/vmware/rbvmomi/master/RbVmomi/VIM/Folder#findByDnsName-instance_method) and github links there are working for me.

The original link in the description is the api docs page about this library as far as I can tell. My understanding is that this library team controls the metadata to have these links working.

Let me know if I'm missing your point.
