### ISSUE TITLE
Google Drive v2 insert_file causes timeout?

### ISSUE THREAD

**Issue by jponc** [google/google-api-ruby-client#357]
Hi guys,

I'm trying to upload a file to Google drive -- It's a 400MB file.

```
Google::Apis::TransmissionError: execution expired
from /Users/jponc/.rbenv/versions/2.1.6/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
```

I'm encountering this error and I got stuck from there. I tried a couple of things like changing `uploadType` to reusable, but no luck

**Comment by jponc** [comment]
```rb
metadata = GoogleDrive::File.new(title: attachment.file_name, mime_type: attachment.file_type, parents: [folder_file])
      drive.insert_file(metadata, upload_source: local_file_location.to_s, content_type: attachment.file_type)
```

Here's a gist of my insert_file related code

**Comment by jponc** [comment]
<img width="675" alt="screenshot 2016-02-15 22 34 19" src="https://cloud.githubusercontent.com/assets/4714727/13051457/4d9c5fd0-d434-11e5-82d4-e79af259ca27.png">

This is basically the screencap of the error I encountered.

**Comment by jponc** [comment]
```rb
GoogleDrive::DriveService.new.tap do |client|
  client.request_options.timeout_sec = 1200
  client.request_options.open_timeout_sec = 1200
  client.request_options.retries = 3
end
```

Kudos to my friend https://github.com/sylv3rblade

**Comment by webzorg** [comment]
Still a problem. says `'syswrite': execution expired (Google::Apis::TransmissionError)` as an error and `NoMethodError: undefined method `open_timeout' for #<Google::Apis::RequestOptions:0x0056455e909aa8>` when I try to alter the parameter. I also tried passing params as a request option but no luck.

**Comment by jcxswc** [comment]
@webzorg Not the easiest to read, but try https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ClientOptions#open_timeout_sec-instance_method

I ended up using:
```
service.client_options.send_timeout_sec = 1200
service.client_options.open_timeout_sec = 1200
```
