### ISSUE TITLE
command.params not working?

### ISSUE THREAD

**Issue by olilogic77** [google/google-api-ruby-client#358]
Disclaimer: I'm a ruby noob

I'm using this gem as my first real Rails app in order to do some meaningful things with our Google for Work account (such as auto-creating/updating group membership).

I've updated from the pre 0.9 format to the new format in accessing the API's, but am hitting this error - 

/Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:203:in `check_status': notFound: Resource Not Found: groupKey (Google::Apis::ClientError)
from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:171:in `process_response'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:278:in `execute_once'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:108:in `block (2 levels) in execute'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:105:in `block in execute'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/http_command.rb:97:in `execute'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Users/darren/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.1/generated/google/apis/admin_directory_v1/service.rb:1130:in `list_group_aliases'
	from lib/tasks/google_demo.rb:34:in `<main>'

The exact same group key and scope works in the pre-0.9 version, and I'm able to list all the groups so I know that the authorization is working ok.

It's probably not the right way to debug but I put a "puts url" in execute_once in http_command.rb which output the following ...

**https://www.googleapis.com/admin/directory/v1/groups/group_key,[groupname@htw.com.au]/aliases?**

where [groupname@htw.com.au] is the name of the group.  I may be completely on the wrong track, and apologies if I am, but I wonder of the params aren't merging across as intended (eg I would expect that the url wouldn't include "group_key" at all.

**Comment by sqrrrl** [comment]
Could you include a snippet from your code where you're calling the API?

**Comment by olilogic77** [comment]
the group list works but the members doesn't ... thanks for helping!

require 'google/apis/admin_directory_v1'
require 'googleauth'

	scopes = ['https://www.googleapis.com/auth/admin.directory.user', 
		'https://www.googleapis.com/auth/admin.directory.group', 
		'https://www.googleapis.com/auth/admin.directory.group.member',
		'https://www.googleapis.com/auth/admin.directory.group.readonly', 
		'https://www.googleapis.com/auth/admin.directory.group.member.readonly']

	ENV["GOOGLE_APPLICATION_CREDENTIALS"] = 'config/keys/google_drive_demo.json'

	authorization = Google::Auth.get_application_default(scopes).dup
	authorization.sub = (my username)

	#client_id = Google::Auth::ClientId.from_file('client_secret.json')
	Google::Apis::RequestOptions.default.authorization = authorization

	adminapi = Google::Apis::AdminDirectoryV1::DirectoryService.new

  #puts adminapi.list_groups.inspect

  next_page = nil

  begin
	  group_list = adminapi.list_groups(domain: (my domain name), page_token: next_page)
	  group_list.groups.each do |g|
	  	puts "#{g.name} - #{g.email} => #{g.direct_members_count} members"
	  end

	  next_page = group_list.next_page_token
	end while next_page

	puts "first group to check is #{group_list.groups.first.email}"
	puts adminapi.list_group_aliases(group_key: group_list.groups.first.email)

	member_list = adminapi.list_members(group_key: group_list.groups.first.email)
	member_list.members.each do |m|
		puts m
	end

**Comment by sqrrrl** [comment]
The problem is just that you're passing the group key incorrectly. It's a positional parameter, not a keyword argument.

```ruby
member_list = adminapi.list_members(group_list.groups.first.email)
```

I know it's a little weird that some things are positional, others keywords, but unfortunately required keyword arguments weren't introduced until ruby 2.1. Since there wasn't a good way to express required arguments using keyword arguments that worked with 2.0, all required arguments (as well as the request body, which isn't required but isn't named either...) are positional.

**Comment by olilogic77** [comment]
Ahh that's done the trick - thanks so much for your help!

**Comment by virgildantas** [comment]
i can't insert a new member on a group, all says is missing field: member
trys:
 service.insert_member(group_key: "croup_key@mydomain.com",member_object: "my_email@gmail.com")
 service.insert_member("croup_key@mydomain.com", "my_email@gmail.com")
 
 says:
 
 Traceback (most recent call last):
       16: from (irb):209:in `rescue in irb_binding'
       15: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-api-client-0.53.0/generated/google/apis/admin_directory_v1/service.rb:1331:in `insert_member'
       14: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/base_service.rb:377:in `execute_or_queue_command'
       13: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:102:in `execute'
       12: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
       11: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
       10: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        9: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:110:in `block in execute'
        8: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        7: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        6: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        5: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
        4: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:310:in `execute_once'
        3: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:194:in `process_response'
        2: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/api_command.rb:134:in `check_status'
        1: from /home/virgilio/.rvm/gems/ruby-2.6.3@sorteio/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:228:in `check_status'
Google::Apis::ClientError (required: Missing required field: member)



can some one help?

**Comment by virgildantas** [comment]
i have tryed to list users by query, but not has success.

if has samples using query(addess, email, orgUnit)

i can understending de documentation
https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/list?apix_params=%7B%22customFieldMask%22%3A%22recovery_email%22%2C%22customer%22%3A%22virgiliodantas.ti%40ueg.br%22%7D
