### ISSUE TITLE
make easy to convert JSON to object

### ISSUE THREAD

**Issue by akostadinov** [google/google-api-ruby-client#363]
Hello, imagine a use case:
```
res = compute.insert_instance(project, zone, instance_object)
```

Now I want to wait for operation to complete. I can do that by regularly getting `#self_link` and reading the `status` key value. While it's possible to use the resulting `Hash` to see for `error` and `warnings`, it would be much nicer if I can get an `Operation` object and look at it.

Could you by any chance add a `#from_json` method to all API objects such that I can do:
```
object_hash = JSON.load(compute.http(:get, url))
object = Google::Apis::ComputeV1::Operation.from_json(object_hash)
```

Or it would be even more awesome if I can do:
```
Google::Apis::Helper.from_json(object_hash)
```

**Comment by sqrrrl** [comment]
Yep, reasonable to add for the top level types. Thought about doing it a while back but never had a good use case.

I you just want your own version, the generic version would be:

```ruby
def from_json(cls, json)
  representer = cls.const_get(:Representation)
  fail "Invalid type specified" if representer.nil?
  representer.new(cls.new).from_json(json, unwrap: cls)
end

operation = from_json(Google::Apis::ComputeV1::Operation, json_body)
```

FYI - For the compute use case, you don't have to use the self_link. You can also call get_(global|region|zone)_operation depending on the type to get the current status.

**Comment by akostadinov** [comment]
Ah, didn't spot these methods, was searching for `get_operation`. My use case is that I wanted to get away with a single method to wait for whatever object to reach the desired status.
```
    def wait_status(object, status, timeout: 120, interval: 10)
      url = object.respond_to?(:self_link) ? object.self_link : object
      return if object.respond_to?(:status) && object.status == status

      last_status = nil
      ohash = nil
      success = wait_for(timeout, interval: interval) {
        ohash = JSON.load(compute.http(:get, url))
        last_status = ohash["status"]
        last_status == status
      }

      if success
        return ohash
      else
        raise "#{url} never reached #{status.inspect}, only #{last_status.inspect}"
      end
    end

    wait_status(operation, "DONE")
```

One implementation to use with any object. But now I am thinking, it makes a lot of sense to have a method for most API objects to wait until particular status is reached. If it is API object specific, one can implement optimizations, e.g. fail early if waiting for status RUNNING but current status is ERROR.

**Comment by sqrrrl** [comment]
FWIW, I'm not entirely sure **why** there are 3 different get_*_operation methods. I think it's an artifact of implementation more than anything. But that's a question for the compute engine team :)
