### ISSUE TITLE
please remove Active support

### ISSUE THREAD

**Issue by akostadinov** [google/google-api-ruby-client#364]
I grepped through the code and saw Active support only used to camelize/decamelize string. I think it's too intrusive to pull in whole Active support just for that. Same thing can be done adding just 2 methods into codebase.

**Comment by sqrrrl** [comment]
The inflector is used for more than that -- singularize/pluralize are also used during code generation and I'd rather not have to duplicate the rules for that (not nearly as trivial as converting between camel<-> snake case :).

That said, singularize/pluralize are only used for code generation. I could make it a soft dependency --- move it to Gemfile + throw an nice error message in the code generator if it isn't installed.

**Comment by akostadinov** [comment]
Would be much nicer if that's done. Trying to keep dependencies sane and what bugs me about Active support is that it monkey patches a lot without being asked to do so.

**Comment by yob** [comment]
I would love this change as well. 

Is the code generation only used by developers of this gem? Maybe activesupport could become a development dependency?

**Comment by sqrrrl** [comment]
Mostly used by developers of the gem, but it is installed when the gem is installed as there are a few use cases for others to use it (consuming an API built with cloud endpoints, or if you have early access to an API that isn't fully public yet.) Even so, it's rare enough that I could just check at runtime (and ActiveSupport::Inflector tends to be very stable between versions, so not too worried about *specific* versions being installed...)

Anyway, will do.

**Comment by akostadinov** [comment]
Thanks a lot! Much better.
