### ISSUE TITLE
Large POST requests (e.g. KML data) are being sent via query string (via Hurley)

### ISSUE THREAD

**Issue by jaredbarr** [google/google-api-ruby-client#365]
I'm using the client to fire off SQL clients to the Fusion Tables API.  Although the client does a POST via hurley, the entire query goes through the query string in the URL, rather than a POST body. 

As the SQL query can get rather long (i'm inserting KML data), the URL limit of 2K is reached and a bad request occurs.  

This is a bit of an ugly patch I quickly made that ensures this request uses a body rather than query string, within lib/google/apis/core/http_command.rb

Hope it makes sense and is helpful.

Since Hurley will likely be dropped - worth checking on native HTTP client too.  Plus I'm not sure if other Google APIs require perhaps a split of query string and body params, so this could be expanded further.

`def execute_once(client)
          body.rewind if body.respond_to?(:rewind)
          begin
            logger.debug { sprintf('Sending HTTP %s %s', method, url) }
            
            response = nil
            if method.to_s == 'post'
              uri = URI.parse(url)
              # get the url without the query string
              new_url = uri.to_s.split("?")[0]
              # query string to be used as POST body
              new_body = uri.query
              # set the content-type to ensure valid form post
              form_content_type = 'application/x-www-form-urlencoded; charset=UTF-8'
              # send the data
              response = client.post(new_url, new_body, form_content_type) do |req|
                apply_request_options(req)
              end
            else
              response = client.send(method, url, body) do |req|
                # Temporary workaround for Hurley bug where the connection preference
                # is ignored and it uses nested anyway
                req.url.query_class = Hurley::Query::Flat
                query.each do | k, v|
                  req.url.query[k] = normalize_query_value(v)
                end
                # End workaround
                apply_request_options(req)
              end
            end
            
            
            logger.debug { response.status_code }
            logger.debug { response.inspect }
            response = process_response(response.status_code, response.header, response.body)
            success(response)
          rescue => e
            logger.debug { sprintf('Caught error %s', e) }
            error(e, rethrow: true)
          end
        end`

**Comment by sqrrrl** [comment]
Have to think about how to do this in a way that is safe for all APIs.

I think it is OK to do *iff*:
* The method is PUT/POST *and*
* There is no other body type specified (e.g. no JSON payload)

Will take a look.
