### ISSUE TITLE
Error when installing google-api-client gem on Mac OSX

### ISSUE THREAD

**Issue by viecode09** [google/google-api-ruby-client#373]
when I use bundler I got this error :

```
An error occurred while installing google-api-client (0.9.3), and Bundler cannot continue.
Make sure that `gem install google-api-client -v '0.9.3'` succeeds before bundling.

```

And I try to install it manually as It's said in the error :

```
ERROR:  Error installing google-api-client:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass
```

Really appreciate for all feedback..

Cheers,

**Comment by sqrrrl** [comment]
What versions of ruby and bundler are you using?

**Comment by viecode09** [comment]
Ruby 2.2.3 and Bundler version 1.11.2..

But I think It's not about Bundler, But on the way installing google-api-client gem..

It's still failing on my machine, is there anything that I can do to fix this issue anyway?

**Comment by sqrrrl** [comment]
From a [quick search](https://www.google.com/search?q=package+is+corrupt%2C+exception+while+verifying%3A+undefined+method+%60size%27+for+nil%3ANilClass&oq=package+is+corrupt%2C+exception+while+verifying%3A+undefined+method+%60size%27+for+nil%3ANilClass) it looks like deleting the gem from your local cache and re-installing might fix the issue. I don't know what would have caused the corruption in the first place, but give it a shot.

**Comment by viecode09** [comment]
Ah I got it.. seems to be working when I delete all caches in local directory..
Just wondering about corruption possibility in gem dependency related with google-api-client..

Thanks for your feedback.. really appreciate it!
