### ISSUE TITLE
Ruby client: export_file

### ISSUE THREAD

**Issue by dsignr** [google/google-api-ruby-client#374]
Calling `export_file` returns an undefined method error when using Google API Ruby client 0.9, although I can still see it inside the source here: https://github.com/google/google-api-ruby-client/tree/a68c43da9cf86cb0fd7af8d071d62d6e30c39a14

Trying `get_file(file_id, 'mime type', download_destination: StringIO.new)` throws an error of invalid arguments (3 instead of 2). I guess 'mime type' isn't accepted anymore?

Trying just `get_file(file_id, download_destination: StringIO.new)` returns nil.

I'm trying to get the raw html contents of the doc.

Using 0.9 version of the gem.

Any ideas? 
Thanks!

**Comment by sqrrrl** [comment]
Which version of drive api? v2 or v3?

For v2, that method was only recently introduced and you'll need to be on 0.9.3+

**Comment by dsignr** [comment]
Yes, V2, thank you. I'll try it out and update you soon.
