### ISSUE TITLE
Google People API 2-way sync

### ISSUE THREAD

**Issue by Ksreenivas** [google/google-api-ruby-client#378]
Hi, @sqrrrl is there any way for 2-way sync in people api.
currently in People V1 there are only 3 services
[https://developers.google.com/apis-explorer/#p/people/v1/](url)

**Comment by sqrrrl** [comment]
Nope. That API is read only at the moment.

You can use the older Contacts API for that, though it's based on an older protocol and not supported by this client library.

https://developers.google.com/google-apps/contacts/v3/
