### ISSUE TITLE
Drive v3 API list_file method operators 'or' and 'and' giving invalid parameter error when used with 'readers' collection in query string

### ISSUE THREAD

**Issue by towhead09** [google/google-api-ruby-client#382]
in the 'try it!' section of the drive API website this query string works and returns files...

"q=mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in readers or  'group1@test.org' in readers) and fullText contains 'example string' "

using the gem, the same query string returns this error

"{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value",
    "locationType": "parameter",
    "location": "q"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}
"

substituting 'and' for 'or' as operator for 'in readers' gives the same error

however this works with the gem... 

"q=mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in writers or 'group1@test.org' in writers) and fullText contains 'example string' "

 and of course in the 'Try it" section of the website....

substituting 'and' for 'or' as operator for 'in writers' works as well

not sure whats going on.....any help would be greatly appreciated

thanks

**Comment by sqrrrl** [comment]
What does your code look like?

This works for me...
```ruby
drive = Google::Apis::DriveV2::DriveService.new
drive.authorization = ... # your creds
query = "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in readers or 'group1@test.org' in readers) and fullText contains 'example string'"
puts drive.list_files(q: query)
```

**Comment by towhead09** [comment]
thanks for the quick reply...

strange....

for me

`files=drive.list_files( :q => "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in readers or 'group1@test.org' in readers) and fullText contains '#{search}'")`

does not work....'Invalid Value' is returned...

but by only substituting 'writers' for 'readers' using the same exact code

`files=drive.list_files( :q => "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in writers or 'group1@test.org' in writers) and fullText contains '#{search}'")`

works...and files are returned

if I search using either 'reader' individually 

`files=drive.list_files( :q => "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in readers) and fullText contains '#{search}'")`

or 

`files=drive.list_files( :q => "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ( 'group1@test.org' in readers) and fullText contains '#{search}'")`

success....

but if I combine 'readers' with 'and' or 'or' ....

`files=drive.list_files( :q => "mimeType != 'application/vnd.google-apps.folder' and trashed = false and ('user1@test.org' in readers and 'group1@test.org' in readers) and fullText contains '#{search}'")`

fails...

so with everything else in the code staying exactly the same...

('user1@test.org' in **readers and** 'group1@test.org' in **writers**) = files returned
('user1@test.org' in **readers or** 'group1@test.org' in **writers**)= files returned
('user1@test.org' in **writers and** 'group1@test.org' in **readers**)= files returned
('user1@test.org' in **writers or** 'group1@test.org' in **readers**)=files returned
('user1@test.org' in **writers and** 'group1@test.org' in **writers**)=files returned
('user1@test.org' in **writers or** 'group1@test.org' in **writers**)=files returned
('user1@test.org' in **readers and** 'group1@test.org' in **readers**)= 'Invalid Value'
('user1@test.org' in **readers or** 'group1@test.org' in **readers**)= 'Invalid Value'
('user1@test.org' in readers)= files returned
( 'group1@test.org' in readers)=files returned

rather bizarre...

gem version is 0.9

little more testing....seems if mimetype is excluded from the query then it works....

`files=drive.list_files( :q => "trashed = false and ('user1@test.org' in readers and 'group1@test.org' in readers) and fullText contains '#{search}'")`

.....works

`files=drive.list_files( :q => "mimeType = 'application/pdf' and trashed = false and ('user1@test.org' in readers and 'group1@test.org' in readers) and fullText contains '#{search}'")`

fails....

thanks

**Comment by sqrrrl** [comment]
When you got it to work in the API explorer, were you using the same account to test?

I don't see anything on the client side that would be causing this (e.g. it doesn't appear to be corrupting the query or on anything like that.) The only thing I could think of is an issue on the backend where it might reject queries that end up being too complex to answer for a given user (typically those with a very large corpus.)

FYI - there is one small potential bug in your example -- Make sure that you escape any embeded ' chars in search, otherwise you'll get mismatched quotes when '#{search}' is interpolated which *will* give you an invalid value error.

**Comment by towhead09** [comment]
same account...

I would agree it seems to be on the backend....

the only difference I could find between the  API explorer, and the gem was the way the uri was encoded when the http request is sent....

the API explorer seems to encode the spaces with a '+'  and leaves the single quotes as is... (q='parent_id'+in+parents)

while using the gem (addressable 2.3.6 ?) encodes the spaces to %20 and single quotes to %27
( q=%27parent_id%27%20in%20parents) 

so could be that somehow as well....

after removing the mime_type from the query string, I was able to query for 2 readers using the gem....
but interestingly when I changed it to 3 (
user1@test.org' in readers or 'group1@test.org' in readers or 'group2@test.org in readers') it failed again...

I worked around it by organizing the groups into a better hierarchy, requiring less querying...

so not crippling any longer...

Thanks for the help( and the gem)!

**Comment by surajsoundar** [comment]
aaron-lorenz -> it is failed because the query which u entered is wrong it seems since the third one is "'emailid.org' in readers" not "'emailid.org in readers'"

**Comment by Hatemii** [comment]
```
def google_drive_files
    drive = Google::Apis::DriveV3::DriveService.new
    drive.authorization = 'your_access_token'
    
    query = "mimeType='application/vnd.google-apps.spreadsheet' and trashed=false"
    @drive_files = drive.list_files(q: query).files

    @drive_files
  end
```

thank me later !
