### ISSUE TITLE
ClientError when trying to call list_user_messages on GmailService

### ISSUE THREAD

**Issue by vojtad** [google/google-api-ruby-client#385]
Hello @sqrrrl!
I want to automatically search for messages in my Gmail account using Gmail API and Service Account authrorization. Here is the code I am using:
```
auth = Google::Auth::ServiceAccountCredentials.make_creds(json_key_io: StringIO.new(json), scope: 'https://www.googleapis.com/auth/gmail.readonly')
auth.fetch_access_token!

gmail = Google::Apis::GmailV1::GmailService.new
gmail.authorization = auth.dup

response = gmail.list_user_messages('me')
```
`json` is string downloaded from developer console.

Here is the exception I receive when executing this code:
```
Sending HTTP get https://www.googleapis.com/gmail/v1/users/me/messages?
400
#<Hurley::Response GET https://www.googleapis.com/gmail/v1/users/me/messages == 400 (179 bytes) 187ms>
Caught error failedPrecondition: Bad Request
Error - #<Google::Apis::ClientError: failedPrecondition: Bad Request>

Google::Apis::ClientError: failedPrecondition: Bad Request
```

Is this a bug? Or is there any other required parameter I am missing?

**Comment by sqrrrl** [comment]
It's likely due to using a service account. The way you're using it, you're not actually accessing your own email, but that of the service account. And since it's not a real user and never enrolled in gmail, that's likely the source of the error.

You should be using *UserAuthorizer to get credentials on your behalf.

**Comment by vojtad** [comment]
Ah, I see. Is there any way to do this using a service account?

We are using Google Apps and I set the service account to be domain-wide for our domain. I have also tried to change user id in list_user_messages to an email from our domain. However, I still get the same error.

**Comment by sqrrrl** [comment]
If you've already configured the service account for delegation with the gmail scopes you're using, then you just need to make a small change to the code.

```ruby
auth = Google::Auth::ServiceAccountCredentials.make_creds(json_key_io: StringIO.new(json), scope: 'https://www.googleapis.com/auth/gmail.readonly')

gmail = Google::Apis::GmailV1::GmailService.new
gmail.authorization = auth.dup
gmail.authorization.sub = 'user@example.com' # Set to email of user to impersonate...

response = gmail.list_user_messages('me') # Me now refers to the impersonated user
```

**Comment by vojtad** [comment]
It works! Thank you very much for your assistance. I am closing this issue since it was my bad it didn't work.
