### ISSUE TITLE
User does not have sufficient permissions for this profile.

### ISSUE THREAD

**Issue by corehook** [google/google-api-ruby-client#392]
Hi dudes!
I want get ga:users for my blog.
1. in https://console.developers.google.com/apis/credentials i register client
2. my google_oauth2 i grant access with scope  'email,profile,analytics.readonly'
3. Try to read data

```ruby
> client = Signet::OAuth2::Client.new(access_token: UserOmni.last.google_token)
> service = Google::Apis::AnalyticsV3::AnalyticsService.new
> service.authorization = client
> service.get_ga_data('ga:75117298', '2015-01-01', '2016-01-01', 'ga:users')
```

```irb
Sending HTTP get https://www.googleapis.com/analytics/v3/data/ga?end-date=2016-01-01&ids=ga%3A75117298&metrics=ga%3Ausers&start-date=2015-01-01
403
#<Hurley::Response GET https://www.googleapis.com/analytics/v3/data/ga?end-date=2016-01-01&ids=ga%3A75117298&metrics=ga%3Ausers&start-date=2015-01-01 == 403 (232 bytes) 1025ms>
Caught error insufficientPermissions: User does not have sufficient permissions for this profile.
Error - #<Google::Apis::ClientError: insufficientPermissions: User does not have sufficient permissions for this profile.>
```

**Comment by corehook** [comment]
I also registered service account and add permission on google analytics site.
Why i must add permission?
My flow must looks like this:
1. User click "Sign in by Google", accept permissions (  'email,profile,analytics.readonly' )
2. User enter site id ( UA-XXXXXXX-1 )
3. Backend get ga:users.

Where i miss something ?

**Comment by corehook** [comment]
After googling i don't believe that i cant get ga:users with Oauth2 access_token / refresh_token...why i must add access to service@email  in my google analytics settings ? 

For example our service provide feautures for analyze ecommerce,  also we must show unique visitors. 

so we cant get ga:users if user just grant access by oauth2 to ther account with scope 'email,profile,analytics.readonly' ?

**Comment by sqrrrl** [comment]
It's unclear from your comments what you're actually doing. You mentioned service accounts, but then in other places it looks like you're just using the user's account instead.

In either case, the error indicates that whatever account you're using doesn't have permission to access the particular profile. That account needs to be authorized via Analytics for the given profile.

See https://developers.google.com/analytics/devguides/reporting/core/v3/help for more details of how to get help using analytics (TL;DR - use stackoverflow)
