### ISSUE TITLE
Youtube Partner API

### ISSUE THREAD

**Issue by assembler** [google/google-api-ruby-client#394]
Why isn't there youtube_partner_v1 API in genrerated/google/apis? Any idea on when it might become available? The old version of google-api-ruby-client worked just fine with youtubePartner api..

**Comment by sqrrrl** [comment]
Mostly just oversight, will generate the API and release a new version soon (hopefully tomorrow :)

**Comment by sqrrrl** [comment]
Now available in 0.9.5+

**Comment by assembler** [comment]
thanks! it works
