### ISSUE TITLE
Google Analytics Reporting API v4

### ISSUE THREAD

**Issue by scottious** [google/google-api-ruby-client#395]
It looks as though the Analytics v4 is not yet in the client. Is this easy to add?

Thanks

**Comment by scottious** [comment]
I failed to read all of the README. Figured it out. Thanks!

**Comment by borey** [comment]
@scottious how to use v4 API? I try to read README but couldn't figure it out.

**Comment by scottious** [comment]
Related to the section under [Generating APIs](https://github.com/google/google-api-ruby-client#generating-apis) if you run this:

`$ generate-api gen <output_dir> --url='https://analyticsreporting.googleapis.com/$discovery/rest'`

Include like so:
`require 'google/apis/analyticsreporting_v4'`

I must say though I had a lot of trouble trying to get this class to execute and return the request and ended up resorting to a more simpler approach to use v4.

**Comment by borey** [comment]
Thanks.
