### ISSUE TITLE
Since yesterday afternoon, CalendarService started returning Invalid Request on Windows

### ISSUE THREAD

**Issue by bg** [google/google-api-ruby-client#398]
With:
- Ruby 2.2.4
- google-api-client 0.9.4 and 0.9.5

Ever since about 24 hours ago, all calls to CalendarService return "Invalid Request", but only on Windows clients. On my Linux clients, I don't have this issue. Here is some debug output from a simple request to "list_settings" with no arguments.

```
D, [2016-04-15T12:32:55.930002 #5200] DEBUG -- : Sending HTTP get https://www.googleapis.com/calendar/v3/users/me/settings?
D, [2016-04-15T12:32:58.086252 #5200] DEBUG -- : 404
D, [2016-04-15T12:32:58.086252 #5200] DEBUG -- : #<Hurley::Response GET https://www.googleapis.com/calendar/v3/users/me/settings == 404 (962 bytes) 2062ms>
D, [2016-04-15T12:32:58.101877 #5200] DEBUG -- : Caught error Invalid request
D, [2016-04-15T12:32:58.101877 #5200] DEBUG -- : Error - #<Google::Apis::ClientError: Invalid request>

```

So far as I can recall, the exact same code was running without errors on the morning of April 14th, but some time in the afternoon it started to fail for reasons opaque to me. Has something changed at the Google service end of things?

I should also note that I am using two workarounds to issues discovered on Windows during my initial development, but these workarounds worked fine over the past few days:

```
# Workaround for https://github.com/google/google-api-ruby-client/issues/253
# - Note: some others in that thread report upgrading to Ruby 2.3.0
#   worked for them.
cert_path = Gem.loaded_specs['google-api-client'].full_gem_path+'/lib/cacerts.pem'
ENV['SSL_CERT_FILE'] = cert_path

# From https://gist.github.com/MikhailSamolinov/635af4fc00e1b46bff04
# See also: https://github.com/google/signet/issues/70
module Signet
  module OAuth2
    class Client
      alias_method :o_normalize_timestamp, :normalize_timestamp
      def normalize_timestamp(time)
        case time
        when NilClass
          nil
        when Time
          time
        when String
          Time.parse(time)
        when Fixnum, Bignum
          #Adding Bignum ^ here as timestamps like 1453983084 are bignums on 32-bit systems
          Time.at(time)
        else
          fail "Invalid time value #{time}"
        end
      end
    end
  end
end
```

Thanks,
Ben

**Comment by bg** [comment]
Still experiencing the same failure with google-api-client 0.9.6

**Comment by bantini** [comment]
Is anyone still facing this problem with the latest version of the library?

**Comment by bantini** [comment]
Closing it for now because there was no response. Feel free to reopen this issue if the problem comes up again.
