### ISSUE TITLE
blank custom_schemas after user creation

### ISSUE THREAD

**Issue by ivanfeob** [google/google-api-ruby-client#401]
I am creating a new user and inserting some custom data in custom_schemas property of a AdminDirectoryV1 :: User object :

```
new_user = Google::Apis::AdminDirectoryV1::User.new
new_user.primary_email = 'tester@mycompany.com'
new_user.password ='teste'
new_user.org_unit_path = '/Test'
new_user.custom_schemas = {"test" => "my custom value"}

name = Google::Apis::AdminDirectoryV1::UserName.new
name.given_name = "Test"
name.family_name = "Google API Test"

new_user.name = name
service.insert_user(new_user)
```

This way I'm able to register the user normally. But I am not able to retrieve the information you have saved custom_schemas.

I am seeking users like this:

```
response = service.list_users(customer: 'my_customer',
                              max_results: 500,
                              projection: 'full',
                              query: 'orgUnitPath=/Test',
                              order_by: 'email')
```

When I try to access the property this way:

```
response.users.each { |user| 

puts user.custom_schemas

}
```

It returns me just an empty line in the console (empty hash).

I have looked in the documentation and examples and apparently I'm not doing anything wrong , at least not in the user creation time .

Somebody else had this problem ?

**Comment by sqrrrl** [comment]
You're using the wrong value for custom schema. [As in the docs](https://developers.google.com/admin-sdk/directory/v1/guides/manage-schemas#json-request), it's not a flat hash of key/value pairs. Instead, it's a set of nested hashes. The top is a hash of schema names -> hash. The nested hashes contain the actual key/value pairs for your specific schema.

I don't know your specific schema name, but should be something like:
```ruby
new_user.custom_schemas = {
  "my_schema_name" => { "test" => "my custom value"}
}
```

If the schema is not defined you'll get an error. You can call insert_schema to create the schema if needed.

Interestingly, looks like a minor bug on the server -- it should have rejected your request with a 40x error.

**Comment by ivanfeob** [comment]
Thanks for the help Steve .
It is now giving error as expected because not yet created the scheme .
In fact I had already seen this error I'm getting now . But as he was taking the wrong way I was doing, just ignored .
