### ISSUE TITLE
Google Sheets API doesn't exist?

### ISSUE THREAD

**Issue by jhuangtw-dev** [google/google-api-ruby-client#405]
looks like the generated APIs are there, but the developer console doesn't recognize it (and thus can't enable it?). when running I encounter the following error:

Google::Apis::ClientError: forbidden: Google Sheets API has not been used in project [my_project_name] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=[my_project_name] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by sqrrrl** [comment]
That was added in error.

**Comment by sqrrrl** [comment]
And the current sheets API is not supported by this client.

**Comment by jhuangtw-dev** [comment]
thanks @sqrrrl. are there any plan in the future for sheets API?

**Comment by stevestofiel** [comment]
+1

**Comment by kaogaau** [comment]
+1

**Comment by sqrrrl** [comment]
Sheets v4 is now available :)

**Comment by kaogaau** [comment]
cool! thanks
