### ISSUE TITLE
Add support to Analytics Reporting API V4

### ISSUE THREAD

**Issue by jbertrand-siliconsalad** [google/google-api-ruby-client#408]

**Comment by scottious** [comment]
Just FYI, until it's added to the core, you can generate the api code for Analytics Reporting API v4 by doing the following in your own repo:

`$ generate-api gen <output_dir> --url='https://analyticsreporting.googleapis.com/$discovery/rest'

Include like so:
`require 'google/apis/analyticsreporting_v4'`

**Comment by sqrrrl** [comment]
Available in 0.9.7
