### ISSUE TITLE
Support for extended metadata/interaction of the Play Store

### ISSUE THREAD

**Issue by ravinggenius** [google/google-api-ruby-client#412]
Currently `Google::Apis::AndroidpublisherV2` only supports a small set of interactions with the Play Store. I would find it extremely useful to be able to do a number of other things as well. For instance selecting a Category and Content Rating, acknowledge Content Guidelines and export laws, setting the Privacy Policy URL and Price, declaring if the app contains ads. Basically I would like to do as much setup as possible through the API. I explored what I could do yesterday; if I missed how to do something please point me to where I can find it.

**Comment by sqrrrl** [comment]
See https://developers.google.com/android-publisher/ for guides on how to use the API. This issue tracker is for the ruby bindings only.

**Comment by ravinggenius** [comment]
@sqrrrl Thanks for the clarification. The API doesn't seem to support what I'd like to do, so who can I get in touch with to submit my petition? I couldn't find any contact information on the site you gave me.
