### ISSUE TITLE
[Question] How to do GCS streaming transfers

### ISSUE THREAD

**Issue by sonots** [google/google-api-ruby-client#413]
I want to use https://cloud.google.com/storage/docs/streaming

I anyway tried codes which passes an IO object like

```ruby
          r, w = IO.pipe
          w << '{"foo":"bar"}'
          body = {
            name: object,
          }
          opts = {
            upload_source: r,
            content_type: 'application/json'
          }
          response = client.insert_object(bucket, body, opts)
```

but I had no success with an error message like

```
:message=>"No such file or directory - No such file or directory - local.path"
```

Does google-api-ruby-client supports GCS streaming transfers? How to do it?

**Comment by sqrrrl** [comment]
At the moment, no. The current upload implementation in the client assumes a stream where the length is known.

**Comment by sonots** [comment]
Hmm, thank you for answering.
