### ISSUE TITLE
Where are Google Maps APIs ?

### ISSUE THREAD

**Issue by josephpage** [google/google-api-ruby-client#421]
Except of Coordinates API, none of Google Maps APIs are available through this gem. Why ?

People ask about it for 1 year :
- http://stackoverflow.com/questions/25228646/directions-api-with-google-api-ruby-client

**Comment by sqrrrl** [comment]
The Maps APIs are built on different infrastructure/protocols than most of the other APIs and have their own clients.

https://developers.google.com/maps/web-services/
