### ISSUE TITLE
InsufficientPermissions error when accessing Fit data?

### ISSUE THREAD

**Issue by Eblohm** [google/google-api-ruby-client#427]
I'm trying to access Fit data in my app, but whenever I try to create a datasource I get a `Google::Apis::ClientError: insufficientPermissions: Insufficient Permission` error.

Here's the code I've got

    require 'google/apis/fitness_v1'
    require 'googleauth'

    scopes = ['https://www.googleapis.com/auth/fitness.activity.read']
    authorization = Google::Auth.get_application_default(scopes)

    some_headers = {}
    authorization.apply(some_headers)

    fitness = Google::Apis::FitnessV1
    fit = fitness::FitnessService.new
    fit.authorization = authorization

    s = fit.create_user_data_source(google_id.uid)

`google_id` is accessed earlier in my code, so I know that's not what's raising the error, and when I check the link it runs the user's ID is included in it, so I know it's successfully retrieving the uid from my database, but I can't figure out why I'm getting this error. My application has the FitAPI enabled.

**Comment by sqrrrl** [comment]
It's because you're not requesting the correct scopes. In your example, you're only asking for read access, but are attempting to write data (create a data source.)

See https://developers.google.com/fit/rest/v1/reference/users/dataSources/create
