### ISSUE TITLE
require 'google/api_client' doesn't work post 0.8.2

### ISSUE THREAD

**Issue by epugh** [google/google-api-ruby-client#432]
I upgraded to the latest version, and the Google:APIClient class maybe disappeared?  Methods like

```
client = Google::APIClient.new
client.authorization.access_token = session[:google_token]
```
don't work because the authorization object is nil.   Some folks highlighted this gotcha, like here: http://www.thegreatcodeadventure.com/using-the-google-api-ruby-client-with-google-calendar-api/

Is there a work around with that latest version?

**Comment by sqrrrl** [comment]
See https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md
