### ISSUE TITLE
Unable to upload to Storage_v1 API

### ISSUE THREAD

**Issue by martincalvert** [google/google-api-ruby-client#433]
Attempting to upload a file through the gem to the storage api results in a `Google::Apis::ClientError: parseError: This API does not support parsing form-encoded input.` error. 

```
storage.insert_object(bucket_name, nil, { name:'test_test.tar.gz.gpg', upload_source: File.open(file_path,'rb')})
```

is the command that I am trying to run. This [line](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/http_command.rb#L152) appears to be setting the content-type to form-encoded 

Which is trigger right above it because the body is empty, which is empty because [here](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/api_command.rb#L52) 

Thanks for any help.

**Comment by martincalvert** [comment]
Whoops guess I should have added this in the initial comment. @sqrrrl

**Comment by sqrrrl** [comment]
FWIW, should be able to work around it by specifying the name in the body instead of query param.

```
storage.insert_object(bucket_name, { name: 'test_test.tar.gz.gpg' }, upload_source: File.open(file_path,'rb'))
```

**Comment by martincalvert** [comment]
Thank you that will work!! I owe you a  🍺

**Comment by mattwhisenhunt** [comment]
Looks like this issue is resolved.

I'll add for any future search results to use https://github.com/GoogleCloudPlatform/google-cloud-ruby for the Cloud Storage API
