### ISSUE TITLE
Google::Apis::DfareportingV2_3 is deprecated 

### ISSUE THREAD

**Issue by bruzos** [google/google-api-ruby-client#434]
Hi, my automated reports for DFA reporting with version 2.3 are not working, as are showed in doc this version is deprecated and not allowed by consumed.

Please can you generate the api version to: 
- Google::Apis::DfareportingV2_4
- Google::Apis::DfareportingV2_5

Please can you tell me the regenerate procedure, may be I could help with  a pull request. ??

**Comment by sqrrrl** [comment]
Client updated to include DFA 2.5
