### ISSUE TITLE
Bug in Google::Apis::StorageV1::ObjectAccessControls

### ISSUE THREAD

**Issue by blowmage** [google/google-api-ruby-client#436]
The `Google::Apis::StorageV1::ObjectAccessControls` class is incorrect. The `#items` method should return `Array<Google::Apis::StorageV1::ObjectAccessControl>`, but instead returns `Array<Object>`, which ends up being an array of hashes.

For example, compare the following:
- [`Google::Apis::StorageV1::ObjectAccessControls#items`](http://www.rubydoc.info/gems/google-api-client/Google/Apis/StorageV1/ObjectAccessControls#items-instance_method)
- [`Google::Apis::StorageV1::BucketAccessControls#items`](http://www.rubydoc.info/gems/google-api-client/Google/Apis/StorageV1/BucketAccessControls#items-instance_method)

**Comment by sqrrrl** [comment]
Unfortunately it's a longstanding bug in the API description that affects all the client libraries and it doesn't appear that it will be fixed any time soon (and likely can't be fixed without breaking apps at this point.)

See https://www.googleapis.com/discovery/v1/apis/storage/v1/rest -- it defines the type as 'any' which is mapped to a hash by this and most of the other clients.

**Comment by blowmage** [comment]
@sqrrrl Was this addressed fixed in the recent 0.10.0 release?

**Comment by sqrrrl** [comment]
Appears so -- looks like the discovery doc issue was fixed and recent regens have been using the correct type.

**Comment by blowmage** [comment]
Yep. Verified the return type is correct now. Thanks!
