### ISSUE TITLE
sheetV4 API

### ISSUE THREAD

**Issue by kaogaau** [google/google-api-ruby-client#437]
Are there any documents about google sheetV4 API of this gem? I want to add a new spreadsheet file in googledrive and assign a specific file name. I have create a new spreadsheet  by default name successful but couldn't assign a specific file name.

Are there any solutions or who has same experience?

Thank for your help.

**Comment by sqrrrl** [comment]
There's an example of renaming a sheet in the API docs:

https://developers.google.com/sheets/guides/batchupdate

Sheets API is a bit complex in that it's designed for batching a lot of complex operations together. So there's no direct 'rename_sheet' method.

Instead, most things (other than simple read/write cell values) goes through batch_update_spreadsheet(...), which takes a list of operations to perform. For your case, you'd need to include an update_sheet_properties operation.

**Comment by kaogaau** [comment]
It's no use that i have try a lot of times
I write a code in below
<code>
hash = {"properties"=>{"title"=>"tomato"}}
response = sheets.create_spreadsheet(spreadsheet_object = hash)
</code>
I  think it will create a spreadsheet that names `tomato`, actually it create a spreadsheet file successful but instead of the name `tomato`,it name is `無標題的試算表` that means `default` when i use spreadsheet in traditional chinese environment

Why???
