### ISSUE TITLE
ActiveSupport dependency effectively breaks v8 for Ruby <2.2.2

### ISSUE THREAD

**Issue by Temikus** [google/google-api-ruby-client#438]
Since ActiveSupport 5.0 release in june dependency effectively breaks v8 for Ruby <2.2.2:
```
temikus λ bundle update
...
Installing activesupport 5.0.0 (was 4.2.7)
...
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
...
An error occurred while installing activesupport (5.0.0), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.
```

This is due to the spec being relaxed badly in https://github.com/google/google-api-ruby-client/pull/211
I do understand that it's a legacy version, however, is it possible to push a minor version of v8 out to fix to unblock the projects that still haven't upgraded? I'm asking since some of the features used by other projects, like `fog`, are only present starting with 0.8.6, like PubSub support.

**Comment by sqrrrl** [comment]
Pushed an 0.8.7 release with the dependency locked down.

**Comment by Temikus** [comment]
@sqrrrl Thanks Steve! 👍
