### ISSUE TITLE
How to get the gmail id which we synced our account?

### ISSUE THREAD

**Issue by Ksreenivas** [google/google-api-ruby-client#441]
hi @sqrrrl is there any way that i can get **gmail id** which i had synced my account with?

**Comment by sqrrrl** [comment]
Can you clarify? What exactly are you looking for?

**Comment by Ksreenivas** [comment]
I am using Google calendar API v3 and I couldn't find using which email I'd I have synced with.
Or is there any way to find out email I'd is already synced with Google calendar.

**Comment by sqrrrl** [comment]
You can use the [calendar.calendarList.list](https://developers.google.com/apis-explorer/#p/calendar/v3/calendar.calendarList.list) to get that. The primary calendar is the email address of the account.
