### ISSUE TITLE
service_account private_key failure

### ISSUE THREAD

**Issue by etalley** [google/google-api-ruby-client#442]
Using Version 0.8.6 I am trying to authenticate a service_account. I have downloaded the .json file from console.developers.google.com.

    client = Google::APIClient.new(
        :application_name => 'Example Ruby application',
        :application_version => '1.0.0'
     )

    scope = ["https://www.googleapis.com/auth/gmail.readonly"]
    s = StringIO.new(ENV['GOOGLE_CLIENT_SECRETS'])
    authorization = Google::Auth::ServiceAccountCredentials.make_creds({:json_key_io=> s, :scope => scope})

    client.authorization = authorization

the private key and client email both render correctly from the json reader but OpenSSL is throwing an error.

> OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error

I have extracted the private_key to a PEM file and tried various methods to validate that its a valid PKS#8 key but so far it seems that its invalid. PuTTYgen couldn't load the pem.

I can try upgrading to .0.9.11, I stayed on 0.8.6 due to bundler not seeing .9 but am looking for a bit of insight.

**Comment by srehne** [comment]
Did you solve this? I have been having problems as well ...

**Comment by etalley** [comment]
I think so, I generated a new json key. either the first one I generated was bad or I somehow modified the file. the new one worked with the code I provided above. Haven't tried making a call yet but thats not the scope of this issue.

**Comment by neycodes** [comment]
Has anyone had any luck with authenticating a service account? So far nothing I've tried works.
