### ISSUE TITLE
How PredictionService#predict_trained_model works on 0.9.x?

### ISSUE THREAD

**Issue by apraditya** [google/google-api-ruby-client#449]
Hi,

I am migrating to 0.9.x from 0.8.x. I used to do

```ruby
client.execute(:api_method =>  prediction.trainedmodels.predict,
               :parameters =>  { :id => model_id },
               :body_object => { input: { csvInstance: features } })
```

However, on the new version what I understand from `#predict_trained_model` [the documentation](http://www.rubydoc.info/github/google/google-api-ruby-client/Google%2FApis%2FPredictionV1_6%2FPredictionService%3Apredict_trained_model), the following doesn't work:

```ruby
google_predict.predict_trained_model(
  ENV['google_app_project'],
  ENV['gpredict_model_id'],
  { csvInstance: data_to_predict }
)
```

I get `ArgumentError: unknown keyword: csvInstance`. Similarly, I have the same kind of error when passing `{ input: { csvInstance: article.data_to_predict } }` on the last argument.

I am confused. Can you give me an example? Thanks!

**Comment by sqrrrl** [comment]
That's a ruby quirk with using a hash as the last parameter to call. Rather than pass it in as is, it's trying to expand it in to keyword args.

You can add an extra empty hash param at the end to work around it.

```ruby
google_predict.predict_trained_model(
  ENV['google_app_project'],
  ENV['gpredict_model_id'],
  { input: { csv_instance: data_to_predict }},
  {} #prevent keyword expansion of body...
)
```
