### ISSUE TITLE
Speech API supported?

### ISSUE THREAD

**Issue by pauljacksonrodgers** [google/google-api-ruby-client#454]
Is the v1beta cloud speech API supported by this gem? It is listed [here](https://developers.google.com/api-client-library/ruby/apis/) as a supported API, but it doesn't look like it's included here, unless I'm missing something.

**Comment by codekitchen** [comment]
I had to generate the API classes using the `generate-api` command included with this gem, and then everything worked as expected for `syncrecognize_speech` and `asyncrecognize_speech`. However, the `StreamingRecognize` operation is only allowed via gRPC, not REST, so it isn't supported by this gem.

**Comment by pauljacksonrodgers** [comment]
Ah, OK. Is there any way of implementing the API on the non-gRPC endpoints?

**Comment by remi** [comment]
@sqrrrl Can we generate the API client for Cloud Speech v1beta1 and push a new release?

I'm working on a [sample](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/e5bdaedf0cd22d79151e1004d564a91e0d0cef63/speech/recognize.rb) that uses this API.  It works, but I currently have to include the generated code in the sample.

**Comment by sqrrrl** [comment]
Yep, will do later today.
