### ISSUE TITLE
how to move or create spreadsheet in my specified folder

### ISSUE THREAD

**Issue by kaogaau** [google/google-api-ruby-client#458]
Hi~all 
I have create a new spreadsheet file by "sheet_v4 API" successfully, but it's default create the file in the root path "/", how could I create spreadsheet in my specified folder or create spreadsheet then move the spreadsheet file in my specified folder.

I try to write some code in the below 
<code>
drive.update_file(file_id,add_parents: folder_id,fields: 'id, parents')
</code>

but it show the error in the below
<code>
parseError: This API does not support parsing form-encoded input.
</code>

Anyone know any solution? Thanks for your help.

**Comment by sqrrrl** [comment]
Can work around that by giving it a request body that is a no-op update (e.g. set the name to it's existing name)

**Comment by kaogaau** [comment]
I have solve this problem. @sqrrrl Thanks for help^^
