### ISSUE TITLE
Fetch all available application

### ISSUE THREAD

**Issue by bolom** [google/google-api-ruby-client#464]
It's possible to Fetch all available application for a specific google developer account ?

**Comment by sqrrrl** [comment]
Sorry, I don't know what you mean. Are you trying to list projects from console.developers.google.com or something like that?

**Comment by bolom** [comment]
@sqrrrl thanks for your quick. What i would like to do call a method who will returns a object with all the package name for a specific account like that i will be able to have a list all the android app in Google Play Store

https://developers.google.com/android-publisher/api-ref/

**Comment by sqrrrl** [comment]
While the android publisher API is supported by this client, I'm not aware of any method that does exactly that. All the list methods work on a specific package, not across the entire developer account.

**Comment by summera** [comment]
@bolom I'm also looking for a way to query a google play account for all packages under the account. Have you found a way to do this?

**Comment by bolom** [comment]
nope :(

**Comment by summera** [comment]
welp, that's unfortunate...
