### ISSUE TITLE
How to get cluster credentials?

### ISSUE THREAD

**Issue by Zhomart** [google/google-api-ruby-client#466]
`gcloud` has command `$ gcloud container clusters get-credentials CLUSTER-NAME`, it creates `HOME/.kube/config` for kubernetes to use. How to create this file using Google Api client?

ContainerService didn't help much:

```
require 'googleauth'
require 'google/apis/container_v1'

scopes = [
  'https://www.googleapis.com/auth/cloud-platform',
]

authorization = Google::Auth.get_application_default(scopes)
some_headers = {
  key: 'API key from console.cloud.google.com/apis/credentials'
}
authorization.apply(some_headers)

Google::Apis::RequestOptions.default.authorization = authorization

cluster = Google::Apis::ContainerV1::ContainerService.new
c = cluster.get_zone_cluster('PROJECT', 'us-central1-a', 'CLUSTER')

puts c.methods
```

**Comment by sqrrrl** [comment]
Sorry, can't help here. This issue tracker is mainly for bugs with the client library, not how-to's on specific APIs. I try to answer the questions that I can, but in this case I just don't know.

I suggest trying one of the developer communities listed at https://cloud.google.com/support/
