### ISSUE TITLE
can't get a list of users

### ISSUE THREAD

**Issue by andreydeineko** [google/google-api-ruby-client#468]
My goal is to get a list of all domain users and see which are **`suspended`**.

In developers console I've created service account, generated the key (`secrets.json`).

The code:

```ruby
require 'googleauth'
require 'google/apis/admin_directory_v1'
ENV['GOOGLE_APPLICATION_CREDENTIALS'] = 'secrets.json'

scopes = [Google::Apis::AdminDirectoryV1::AUTH_ADMIN_DIRECTORY_USER]

auth = Google::Auth.get_application_default(scopes)

Google::Apis::RequestOptions.default.authorization = auth

service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.list_users #=> Google::Apis::ClientError: badRequest: Bad Request
```
It errors with

```ruby
Sending HTTP get https://www.googleapis.com/admin/directory/v1/users?
400
#<Hurley::Response GET https://www.googleapis.com/admin/directory/v1/users == 400 (171 bytes) 566ms>
Caught error badRequest: Bad Request
Error - #<Google::Apis::ClientError: badRequest: Bad Request>

Google::Apis::ClientError: badRequest: Bad Request
```

Any change to get it working? Actually, I was getting the same error with the [official Google ruby guide](https://developers.google.com/admin-sdk/directory/v1/quickstart/ruby).

Thanks in advance!

**Comment by sqrrrl** [comment]
Thanks for noticing the broken quickstart in the docs, I'll have that fixed.

Two issues with the code here:

* Service accounts aren't members of a domain and don't have access to the directory. You can use service accounts, but you also need to make sure they're authorized to access the domain as well as impersonate a valid user on the domain.
* IIRC the `customer` parameter is required for list_users.

With the code as it is, there's no signal to the back end as to which domain/org you're trying to list the users for, hence the `bad request` error.

**Comment by andreydeineko** [comment]
@sqrrrl could please-please advise on what is the easiest and straightforward way to retrieve all users? I tried few approaches and none worked. I am new to Google API.

If you fix the quickstart, what do I have to pass into the `service.list_users`? I've checked the source, and it takes a dozen of optional args and a block, but it didn't.

**Comment by sqrrrl** [comment]
The quickstart was just updated and should work again.

list_users requires either a domain or customer parameter. Since the way the underlying API is written neither is technically required, they both appear as optional params, but you need at least one of them. See https://developers.google.com/admin-sdk/directory/v1/reference/users/list

The quickstart uses the special value 'my_customer' which is an alias for the user's current org.

**Comment by andreydeineko** [comment]
@sqrrrl, thanks for the update!

With edited `quickstart` I now have something better, but still an error:

```ruby
Google::Apis::ClientError: forbidden: Not Authorized to access this resource/api
```

What do you think? I followed the guide step-by-step..

**Comment by andreydeineko** [comment]
@sqrrrl Thanks! It works now. One last question - list users gives me the list of all users, how do I add specific fields to response? I tried:

```ruby
service.list_users(customer: 'my_customer', order_by: 'email', fields: 'suspended')
```
But it says
```ruby
Google::Apis::ClientError: invalidParameter: Invalid field selection suspended
```

**Comment by emirkin** [comment]
@sqrrrl, which **user**'s current org?

**Comment by jochenstu** [comment]
FWIW I am having the same issue in late 2023. 

`response = @service.list_users(customer: 'my_customer', max_results: 10, order_by: 'email')`

leads to 

```
Google API Error: invalid: Invalid Input
Status Code: 400
Headers: #<HTTP::Message::Headers:0x00007f8df587aa20 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x3b74 URI:https://admin.googleapis.com/admin/directory/v1/users?customer=my_customer&maxResults=10&orderBy=email>, @request_query=nil, @request_absolute_uri=nil, @status_code=400, @reason_phrase="Bad Request", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Tue, 05 Dec 2023 09:42:26 GMT"], ["Server", "ESF"], ["Cache-Control", "private"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"], ["Transfer-Encoding", "chunked"]], @dumped=false>
Body: {
  "error": {
    "code": 400,
    "message": "Invalid Input",
    "errors": [
      {
        "message": "Invalid Input",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

Interestingly, when I supply a domain instead of `customer: 'my_customer'` – changing nothing else – I get this:

```
Google API Error: forbidden: Not Authorized to access this resource/api
Status Code: 403
Headers: #<HTTP::Message::Headers:0x00007fab522d9920 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x3b74 URI:https://admin.googleapis.com/admin/directory/v1/users?domain=hallo-nomina.de&maxResults=10&orderBy=email>, @request_query=nil, @request_absolute_uri=nil, @status_code=403, @reason_phrase="Forbidden", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Tue, 05 Dec 2023 09:46:17 GMT"], ["Server", "ESF"], ["Cache-Control", "private"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"], ["Transfer-Encoding", "chunked"]], @dumped=false>
Body: {
  "error": {
    "code": 403,
    "message": "Not Authorized to access this resource/api",
    "errors": [
      {
        "message": "Not Authorized to access this resource/api",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
```

I have been trying to make this work on an off for 2 days now. I tried using both `Google::Auth::ServiceAccountCredentials.make_creds` and `Google::Auth.get_application_default`.  For the service account, I have set up DWD in Google Admin with the required scope (https://www.googleapis.com/auth/admin.directory.user.readonly)

To no avail. Any pointers?

**Comment by ssapa** [comment]
Hello Team, I am also obseving similar issue as mentioned by @jochenstu. May I know the solution of this issue please.
