### ISSUE TITLE
Google analytics Demo account

### ISSUE THREAD

**Issue by arjunmenon** [google/google-api-ruby-client#469]
Hey
You guys are offering a [Demo account](https://support.google.com/analytics/answer/6367342?utm_source=GA%20Education&utm_medium=affiliate&utm_content=GA%20blog&utm_campaign=Demo%20Account). But is the data available from the API?

I tried testing it for simple pageviews, but I get an error
`insufficientPermissions: User does not have sufficient permissions for this profile.`,
even from the Query Explorer.
Can you please confirm its availability and how to properly access it?

It becomes useful and understand all scenarios to build a test app with demo data before putting it public.

**Comment by sqrrrl** [comment]
That demo account can not be used with the API. There's a note on that page:

> The demo account cannot be used with the Analytics Reporting API. Attempting to access the
> demo account with the Analytics Reporting API will result in a permissions error: (403) 
> insufficientPermissions.
