### ISSUE TITLE
Filters stripped from datastore_v1beta3 query

### ISSUE THREAD

**Issue by gozup** [google/google-api-ruby-client#471]
Hi all,

Since Datastore v1 is still not available in this library, I'm using de v1beta3 API.

But when I want to process a run_query, the filters are removed from the body that is sent to the API endpoint. See below how I'm doing the call.

```ruby
@client = Google::Apis::DatastoreV1beta3::DatastoreService.new
query = {
	"kind": [{
		"name": "Events"
	}],
	"filter": {
		"compositeFilter": {
			"filters": [{
				"propertyFilter": {
					"op": "equal",
					"property": {
						"name": "type"
					},
					"value": {
						"stringValue": "acquaintance"
					}
				}
			}, {
				"propertyFilter": {
					"op": "equal",
					"property": {
						"name": "app"
					},
					"value": {
						"integerValue": 2
					}
				}
			}, {
				"propertyFilter": {
					"op": "equal",
					"property": {
						"name": "users"
					},
					"value": {
						"integerValue": 345
					}
				}
			}],
			"op": "AND"
		}
	}
}

datasetId = 'xxxxxxxx'
run_query_request_object = Google::Apis::DatastoreV1beta3::RunQueryRequest.new( query: query )
result = client.run_project_query(datasetId, run_query_request_object)
```

But the API raises the following error:
> Google::Apis::ClientError: badRequest: a filter must have exactly one of its fields set

However, the `run_query_request_object` returns a well formatted query, but the content of the body that is sent to the endpoint is :
`"{"query":{"filter":{},"kind":[{"name":"Events"}]}}"`
You can see that the filters have been stripped from the filter key...

I took a screenshot of my variables. [Watchable here](https://s3.amazonaws.com/elemoine/forums_images/variables_datastore_ruby_client.png).

I tried hundreds of things, but I couldn't make it work... If someone could help I would be very thankful.

I currently use the v1beta2 right now, but it will be stopped by Google in less than 10 days, so I really need to handle this update of version...

Many thanks !

**Comment by sqrrrl** [comment]
See [the readme](https://github.com/google/google-api-ruby-client#naming-conventions-vs-json-representation) which covers this topic. Use snake_case when using the ruby client -- `composite_filter`, `property_filter`, `integer_value`, etc..

**Comment by sqrrrl** [comment]
And I'll update to include datastore v1 shortly
