### ISSUE TITLE
BigQuery insert_job returns a job id that cannot be fed to get_job

### ISSUE THREAD

**Issue by bittrance** [google/google-api-ruby-client#472]
My intuition would be that you should be able to do this:

```
job_id = @service.insert_job(@project_id, jobdef).id
job = @service.get_job(@project_id, job_id)
```

However, this results in `Google::Apis::ClientError: invalid: Invalid job ID "my-project:job_1b5nA7p8CHu-Tv0dfsvMSGmFDuo". Job IDs must be alphanumeric (plus underscores and dashes) and must be at most 1024 characters long.`

In order to achieve success, I need to filter the ID thus `job.id.gsub(/^.*:/, '')`.

I realise that I can use .job_reference.job_id to get the "local" ID, but would it not make sens to make the get_job() call accept a full JobReference?

**Comment by sqrrrl** [comment]
Agree, though it's just how the API is designed.

Note that some of the GCP products have alternative client libraries. For BigQuery, you may want to try https://github.com/GoogleCloudPlatform/google-cloud-ruby
