### ISSUE TITLE
Google::Apis::ClientError Forbidden

### ISSUE THREAD

**Issue by garbanotas** [google/google-api-ruby-client#477]
Hello, I'm using `0.9.15` version. I have storage api enabled. What I'm doing:
1. require 'google/apis/storage_v1'
2. Storage = Google::Apis::StorageV1
3. service = Storage::StorageService.new
4. I have also `google_storage_client.json`.
5. I'm calling `auth = Google::Auth::ServiceAccountCredentials.new(token_credential_uri: 'https://www.googleapis.com/oauth2/v3/token', audience: 'https://www.googleapis.com/oauth2/v3/token', scope: ["https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/devstorage.full_control"], issuer: "[my-service-account]", signing_key: OpenSSL::PKey::RSA.new([private_key_from_json]))`
1.  service.authorization = auth
2. Then trying to make api request `service.list_buckets('my-bucket-name')`
3. And receive `Google::Apis::ClientError: forbidden: Forbidden`.

I also tried with `auth.sub = 'my_admin_email'` with no luck.

the same is with 

`scopes =  ['https://www.googleapis.com/auth/cloud-platform','https://www.googleapis.com/auth/compute']
 => ["https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/compute"]`
`authorization = Google::Auth.get_application_default(scopes)`
Can you help please with that?

**Comment by garbanotas** [comment]
Ok, I managed to get token by calling `authorization.apply({})`
 => {:authorization=>"Bearer long hash"}
But still when I do request `service.list_buckets('my-bucket-name')` it fails with 403 Forbidden.

**Comment by garbanotas** [comment]
@sqrrrl could you please help with that issue? thanks

**Comment by mattwhisenhunt** [comment]
For the Cloud Storage API please use https://github.com/GoogleCloudPlatform/google-cloud-ruby
