### ISSUE TITLE
speech api sync_recognize_request_object example

### ISSUE THREAD

**Issue by ThomasRoest** [google/google-api-ruby-client#480]
Hi!

  The sync_recognize_speech method in [speech_v1beta1/service.rb](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/speech_v1beta1/service.rb) takes the **sync_recognize_request_object** as the first argument. 
  
  Do you have an example of what that sync_recognize_request_object should look like? 

  I've used the curl / gcloud example with the following sync request json file:

`{'config': {
      'encoding':'FLAC',
      'sampleRate': 44100 ,
      'languageCode': 'en-GB'
  },
  'audio': {
    'content' : 'base64 audio file..'
  }
}`

This works, however, I cannot get the request right in this api-client. I've tried various objects but it keeps returning the following error:

<Google::Apis::ClientError: badRequest: Invalid recognition 'config': request must contain 'config' field.

Thank you

**Comment by ThomasRoest** [comment]
figured it out:

example:


```
sync_recognize_request_object = Google::Apis::SpeechV1beta1::SyncRecognizeRequest.new

sync_recognize_request_object.config = { encoding: "FLAC", sample_rate: 16000, language_code: "en-US" }
sync_recognize_request_object.audio = { uri: "gs://cloud-samples-tests/speech/brooklyn.flac"}

speech.sync_recognize_speech(sync_recognize_request_object)


```

**Comment by spinksa** [comment]
thx!
