### ISSUE TITLE
Can't upload video from remote source

### ISSUE THREAD

**Issue by faustoct** [google/google-api-ruby-client#481]
Can't perform youtube.insert_video from remote source

    file = Google::Apis::Core::UploadIO.from_file('http://domain.com/file.mp4')
    youtube.insert_video('snippet', body, upload_source: file)

Any workaround?

**Comment by sqrrrl** [comment]
Download the file yourself :)

AFAIK YouTube doesn't have that feature, nor does the client library. That said, `upload_source` can be an input stream. So you should be able to do something like:

```ruby
require 'open-uri'

open('http://domain.com/file.mp4') do |f|
  youtube.insert_video('snippet', body, upload_source: f)
end
```
