### ISSUE TITLE
WebmastersV3 get_sitemap pending status always false even if pending

### ISSUE THREAD

**Issue by maxfwerner** [google/google-api-ruby-client#484]
It has repeatedly happened to me that regardless of whether a sitemap is shown as processed or pending in the search console website, the API call for `get_sitemap`'s property of `is_pending?` always returns false. In addition to that, if the sitemap in question is indeed pending, the API also returns a `indexed` value of 0.

This seems to be more an API issue than a bug in this library as I get the same results using the Google APIs Explorer. You can see the output from the APIs Explorer on the left of the picture (same output as the ruby api call) and the search console view on the right.

![webmastersv3bug](https://cloud.githubusercontent.com/assets/12665106/19441406/04f2d244-945c-11e6-8f81-408749d05c21.PNG)

**Comment by sqrrrl** [comment]
Since it appears to be more of an API issue, I suggest reporting directly to the webmaster team. You can try the forum or one of the scheduled office hours (see https://developers.google.com/webmaster-tools/)
