### ISSUE TITLE
Allow passing of a json object in place of the ruby object

### ISSUE THREAD

**Issue by Carpela** [google/google-api-ruby-client#488]
Is there a way to just pass a standard json object as the body of the ruby client requests. 

e.g.

client = Google::Apis::GmailV1::GmailService.new 
.....Authorise it properly
 json_variables = {addLabelsIds:[], removeLabelIds:['INBOX']}.to_json

client.modify_message("me", id, json_variables)

This provides a migration path for using previous versions. i.e. 0.8
It allows people to rely on the documentation provided for the GmailAPI more generally (which is much more up to date) 

It stops people having to do create the following: 

Google::Apis::GmailV1::ModifyMessageRequest.new(add_label_ids: [], remove_label_ids: ['INBOX']) 

It keeps a consistent set of variables whether you're using Threads or Messages or Drafts

i.e. in the threads scenario (in theory) you would have to do the following:
Google::Apis::GmailV1::ModifyThreadRequest.new(add_label_ids: [], remove_label_ids: ['INBOX'])

(When I say in theory, sending the first one works, but someone might block that as 'wrong' in the future). 

It's a big change, but certainly on Gmail, it would be useful to be able to rely on the JSON variables because they're documented properly in the API.

**Comment by Carpela** [comment]
Hi guys, can I ask if this one's been done?

**Comment by sqrrrl** [comment]
Yes, in v0.11+

See https://github.com/google/google-api-ruby-client#using-raw-json
