### ISSUE TITLE
My Business

### ISSUE THREAD

**Issue by mmotherwell** [google/google-api-ruby-client#490]
Does the My Business API https://developers.google.com/my-business/reference/rest/ show up in the list?

I ran this code:

client.discovered_apis.each do |gapi| 
  puts "#{gapi.title} \t #{gapi.id} \t #{gapi.preferred}"
end

And I can't see it at all.

**Comment by sqrrrl** [comment]
It's not in the API directory, but the discovery doc is available at https://developers.google.com/my-business/samples/.  v3 is supported in this client.
