### ISSUE TITLE
Support timed publishing?

### ISSUE THREAD

**Issue by mychaelgo** [google/google-api-ruby-client#491]
According to this url [https://support.google.com/googleplay/android-developer/answer/6334282?hl=en](https://support.google.com/googleplay/android-developer/answer/6334282?hl=en) , is any open api google have to support timed publishing and trigger `go live` via api?

**Comment by sqrrrl** [comment]
See https://developers.google.com/android-publisher which is supported by this client. I don't know if it explicitly supports timed publishing or not, but that's the only API I know of related to android publishing.
