### ISSUE TITLE
Difference between google/google-api-ruby-client and google-cloud-ruby

### ISSUE THREAD

**Issue by mustela** [google/google-api-ruby-client#495]
Hey everyone, I'm starting an integration with Google Vision, and I realized that there are 2 libs from Google that supports it, this one and this one: https://github.com/GoogleCloudPlatform/google-cloud-ruby.

Wondering which is the difference and which one is the recommended one?

Thanks

**Comment by sqrrrl** [comment]
For most cloud APIs, google-cloud-ruby is the preferred client. Not every cloud API is covered in that library though.

For everything else, this one.

There is some overlap between the two. The main difference is google-cloud-ruby is hand-written specifically for the cloud APIs. This one auto-generates the APIs. While the auto-generated code is usually fine, there are cases where the google-cloud-ruby may be easier to use.
