### ISSUE TITLE
[Question] How to filter nested fields with ComputeBeta#list_instances

### ISSUE THREAD

**Issue by sonots** [google/google-api-ruby-client#500]
As looking a reference https://cloud.google.com/compute/docs/reference/latest/instances/list, it says

> Compute Engine Beta API Only: When filtering in the Beta API, you can also filter on nested fields. For example, you could filter on instances that have set the scheduling.automaticRestart field to true. 

So, I tried to filter tags or metadata such as:

```
list_instances(project_id, zone, filter: 'tags.items[0] eq foo')
list_instances(project_id, zone, filter: 'metadata.items[0].value eq foo')
```

but I got `Invalid list filter expression`. How can I filter tags or metadata field?

**Comment by stonith** [comment]
I ran into this as well, apparently it's not supported "Only atomic field types are supported (string, number, boolean)." per the link you referenced.

**Comment by sonots** [comment]
Okay, thanks.
