### ISSUE TITLE
redirect_uri - Can't convert Hash into String

### ISSUE THREAD

**Issue by hsalazarl** [google/google-api-ruby-client#503]
I know this issue was solved in the past for authorization_uri, but now is happening with redirect_uri, when it comes as a hash, it fails at `def redirect_uri=(new_redirect_uri)`, since it is not validating the type of object that comes in, it just calls `Addressable::URI.parse(new_redirect_uri)` immediately.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
