### ISSUE TITLE
Can't update files with mime type "plain/text"

### ISSUE THREAD

**Issue by MStadlmeier** [google/google-api-ruby-client#505]
Whenever I try to update a text/plain file (either meta data or media) with  `DriveV3::DriveService#update_file` , I get a 400 from the server which results in a `ClientError` exception with the message "Parse Error". Initially uploading text/plain files works without a problem.

Every other mime type can be updated just fine. In fact, I can even just change the `content_type` parameter to whatever I want and the exact same request with the same file and the same data works fine. 

I followed the call until `ResumableUploadCommand#send_start_comand` and the request looks fine to me. If I follow the same call with a different mime type, the state of the function looks exactly the same, with the only difference being that the ` UPLOAD_CONTENT_TYPE_HEADER` field in the request header is some other type, instead of "text/plain".

My code that throws the exception : `@service.update_file(file.id, content_type: "text/plain", upload_source: "some/path.txt")`

The version of the gem I'm using is 0.9.20 on ruby 2.3.0

**Comment by sqrrrl** [comment]
Think this might be a backend issue where it doesn't accept an empty JSON payload for the update request. There is a workaround though -- just set include `file_object = {}` in the `update_file` call.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
