### ISSUE TITLE
`batch_update_presentation` suddenly throwing errors when passing `replace_all_shapes_with_image` requests

### ISSUE THREAD

**Issue by coryschires** [google/google-api-ruby-client#510]
### Background
I have an application which, very similar to [this guide](https://developers.google.com/slides/how-tos/merge), creates presentations based on a template. Up until a few days ago, it's been working swimmingly. 

### Problem
On Dec 15, my app started failing with errors like:

    Google::Apis::ClientError: badRequest: Invalid requests[8].replaceAllShapesWithImage: The operation is not allowed on notes page element g12bc5ef721_2_5 

After some debugging, I determined that this error only occurs if I am trying to merge images by setting `replace_all_shapes_with_image`. If I remove that bit, the error disappears. 

Normally, I would assume this is a bug in my code. But, oddly, I don't seem to have changed anything during the time frame when the issue arose. 

Also, if it's helpful, I've been using the latest version `0.9.20` the entire time

**Comment by sqrrrl** [comment]
This appears to be an issue or change with the Slides API itself, not the client. Recommend using the support options at https://developers.google.com/slides/support instead.

My hunch though is whatever text you're searching for appears in the speaker notes and it's trying to do the shape replacement on the notes, which isn't allowed.

**Comment by coryschires** [comment]
Thanks for the advice!

For future reference, this problem resolved itself after upgrading from version ` 0.9.20` to `0.12.0`. Must have been a short-lived bug in the Slides API.
