### ISSUE TITLE
Support POST requests for TranslateV2 to circumvent GET size limit

### ISSUE THREAD

**Issue by atyndall** [google/google-api-ruby-client#516]
Hi there,

We use the TranslateV2 API to perform large amounts of bulk translation like so;

```ruby
client = Google::Apis::TranslateV2::TranslateService.new
client.key = GOOGLE_TRANSLATE_API_KEY
client.list_translations(["foo", "bar", "baz", ...], 'en')
```

However, this gem's implementation of the API request uses a GET request, which quickly runs into Google Translate's GET length limit; 

> The URL for GET requests, including parameters, must be less than 2K characters.
> -- https://cloud.google.com/translate/docs/translating-text

In this case, it is possible to send a POST request of identical format to the same API endpoint to circumvent this limit. 

Would it be possible for the gem to support this use case?

In terms of underlying implementation, we've found that only a very simple change is required; appbot/google-api-ruby-client@5edbd3e. However I understand this may be difficult given the auto-generating nature of the APIs.

Thanks,
Ash

Edit: As of today this change has also been necessary to perform the POST request without getting a 404 from Google; appbot/google-api-ruby-client@18da701

**Comment by mattwhisenhunt** [comment]
I am looking into this, in the mean time you may want to check out https://github.com/GoogleCloudPlatform/google-cloud-ruby#cloud-translation-api-ga

**Comment by mattwhisenhunt** [comment]
It hasn't been intentionally shelved, good to know you are still watching it. I noticed `translate_translation_text` which does POST is very similar to `list_translations`. Would you be willing to see if it was a better fit for those big workloads?

**Comment by atyndall** [comment]
Hi @mattwhisenhunt, I can confirm that the new method seems to work for our use case. Thanks for the hint!
