### ISSUE TITLE
Update README / release notes to mention 0.10.0

### ISSUE THREAD

**Issue by remi** [google/google-api-ruby-client#548]
I see that version 0.10.0 was released.

What breaking changes are there from 0.9 to 0.10?  It would be really useful to put a short description on the release: https://github.com/google/google-api-ruby-client/releases/tag/0.10.0

The README mentions...

> **Migrating from 0.8.x**
> Version 0.9 is not compatible with previous versions.  See [MIGRATING](https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md) for additional details on how to migrate to the latest version.

But 0.10 is the latest, so it's a little confusing 😄

**Comment by saicheems** [comment]
Ah yes, I had https://github.com/google/google-api-ruby-client/pull/541 out for that but forgot to update, will do.

Thanks for the issue

**Comment by sqrrrl** [comment]
Merged #541.
