### ISSUE TITLE
Ability to CRUD Topic attribute in Google::Apis::ClassroomV1::CourseWork class?

### ISSUE THREAD

**Issue by schmudu** [google/google-api-ruby-client#551]
Hello All,
I was wondering if there is a way via the Ruby API doc to modify a Topic for the following class:
Google::Apis::ClassroomV1::CourseWork

Topics were introduced in August 2016 as far as I can tell as a way for teachers to organize their stream:
https://support.google.com/edu/classroom/answer/6149237?hl=en

Does anyone know of a way?  I'm okay with making a REST call as well if necessary.

Thanks!

**Comment by sqrrrl** [comment]
Topics aren't supported in the classroom API. It's a known feature request, but not aware of any plans to add support for it yet.

**Comment by CarlosPerezUdabe** [comment]
Its a feature requested still
[https://issuetracker.google.com/issues/70885100](url)
