### ISSUE TITLE
Typos in the Google Drive methods?

### ISSUE THREAD

**Issue by matiaskorhonen** [google/google-api-ruby-client#562]
Both the V2 and V3 versions of the Google Drive client seem to typo `teamdrive` in multiple places as `teamdrife`.

For example in [generated/google/apis/drive_v3/service.rb](https://github.com/google/google-api-ruby-client/blob/cf8ca47083009e23197a2f2719acd6dece229822/generated/google/apis/drive_v3/service.rb#L1672)

```ruby
def create_teamdrife(request_id, team_drive_object = nil, fields: nil, quota_user: nil, user_ip: nil, options: nil, &block)
  #...
end
```

**Comment by sqrrrl** [comment]
Weird case in the active support inflector.

Given that Teamdrive support in the API is very new and there likely are very few apps affected, I fixed the generator and the typo is fixed in 0.10.3. Ideally should have waited to 0.11, but that has other more substantial changes in it.
