### ISSUE TITLE
appsmarket v2 support

### ISSUE THREAD

**Issue by jwg2s** [google/google-api-ruby-client#563]
We're currently on v0.8.7 of the `google-api-ruby-client` and we're attempting to upgrade to at least v0.9.

One of our calls is to the appsmarket_v2 api.  https://developers.google.com/apps-marketplace/v2/reference/

However, I can't find how to make a call to this API in v0.9+.  Am I missing something?

Here's an example of the call in v0.8x:

```ruby
    api_client = ::Google::APIClient.new(
      :application_name => 'not relevant',
      :application_version => 'not relevant'
    )
    api_client.authorization = Signet::OAuth2::Client.new(
      :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      :audience => 'https://accounts.google.com/o/oauth2/token',
      :scope => 'https://www.googleapis.com/auth/appsmarketplace.license',
      :issuer => 'not_relevant',
      :signing_key => 'not_relevant')
    )
    api_client.authorization.fetch_access_token!

    service = api_client.discovered_api('appsmarket', 'v2')
    response = api_client.execute(service.customer_license.get, 'applicationId' => 'not relevant', 'customerId' => 'example.com')
```

**Comment by jwg2s** [comment]
@sqrrrl I'm assuming this implies it's not possible and will be added back in v0.11?

**Comment by sqrrrl** [comment]
I added it to 0.11 which was release a couple of days ago.

See https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/appsmarket_v2/service.rb

**Comment by jwg2s** [comment]
Awesome - thanks @sqrrrl
