### ISSUE TITLE
Sheets API v4 is returning 503 Unavailable

### ISSUE THREAD

**Issue by mendoncakr** [google/google-api-ruby-client#565]
I'm using the Google API Ruby [client][1] to do 4 things:

 1. Access my drive
 2. Create a new spreadsheet
 3. Update cells in the the spreadsheet
 4. Get cells with calculated results from same spreadsheet

I'm able to successfully achieve the first 3 items listed above, but arrive at a 503 error when attempting to fetch the cells. I am able to get cells from the spreadsheet if I ***DO NOT*** run the #batch_update_values method. The error only occurs when both functions are called sequentially, yet work when called individually.

In my service:

    data = [list of ValueRange Objects]
    request_body = Google::Apis::SheetsV4::BatchUpdateValuesRequest.new
    request_body.value_input_option = "user_entered";
    request_body.data = data;

    # this works
    @sheets_client.batch_update_values(working_copy.id, request_body)

    # this does not work even with retries set
    range = "Sheet2!A3:BN23"
    response = @sheets_client.get_spreadsheet_values(working_copy.id, range, value_render_option: "UNFORMATTED_VALUE", date_time_render_option: "SERIAL_NUMBER")

The exact error is:

    {"error": {
    "cause": null,
    "status_code": 503,
    "header": {
      "Vary": "Referer",
      "Content-Type": "application/json; charset=UTF-8",
      "Content-Encoding": "gzip",
      "Date": "Tue, 04 Apr 2017 00:42:21 GMT",
      "Server": "ESF",
      "Cache-Control": "private",
      "X-Xss-Protection": "1; mode=block",
      "X-Frame-Options": "SAMEORIGIN",
      "Alt-Svc": "quic=\":443\"; ma=2592000; v=\"37,36,35\"",
      "Transfer-Encoding": "chunked"
    },
    "body": "{\n  \"error\": {\n    \"code\": 503,\n    \"message\": \"The service is currently unavailable.\",\n    \"errors\": [\n      {\n        \"message\": \"The service is currently unavailable.\",\n        \"domain\": \"global\",\n        \"reason\": \"backendError\"\n      }\n    ],\n    \"status\": \"UNAVAILABLE\"\n  }\n}\n"
  }
}

  [1]: https://github.com/google/google-api-ruby-client "client"

**Comment by sqrrrl** [comment]
For help with the sheets API itself, see https://developers.google.com/sheets/api/support.
