### ISSUE TITLE
How to get the project number of developer account

### ISSUE THREAD

**Issue by gagaJay** [google/google-api-ruby-client#570]
Hey guys, I know this is weird but I really want to know if the client provide a way to get the project number (every project id comes with a project number) from the developer account, given that I have the jsonkey which contains the project id. I need this project number because I want to use it for GCM senderID. 

another side question is that, does the API provide a way to retrieve the android MAP KEY as well?

Many thanks in advance.

**Comment by swcloud** [comment]
This is the same issue as https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1416. Can close now.
