### ISSUE TITLE
Fusion Tables API -- Combine multi-column locations

### ISSUE THREAD

**Issue by durcak** [google/google-api-ruby-client#571]
Hi, can somebody help me to create fusion table with two column location type for longitude and latitude?
In web application its really easy (https://support.google.com/fusiontables/answer/175922?hl=en), but I can find a way how to do that with API. Thanks.

**Comment by sqrrrl** [comment]
For help with the Fusion Tables API, try StackOverflow -- http://stackoverflow.com/search?q=fusion-tables
