### ISSUE TITLE
RFC5545 discrepancy in Calendar API.

### ISSUE THREAD

**Issue by ilyakorol** [google/google-api-ruby-client#572]
When I'm importing event with `recurrence: ['RRULE:FREQ=HOURLY']` I am getting`Google::Apis::ServerError: Server error` but it's a valid format according to the RFC.

**Comment by sqrrrl** [comment]
For behavioral issues with the calendar API itself, please see https://developers.google.com/google-apps/calendar/support.

If you've confirmed that it's a bug in the client library vs the service itself, please re-open.
