### ISSUE TITLE
Since 0.11.2 update - "uninitialized constant Google::Apis::PeopleV1::PeopleService"

### ISSUE THREAD

**Issue by hundsim** [google/google-api-ruby-client#574]
I've been using the People Api without problem for 6 months. But today when I updated the `google-api-client` gem to `0.11.2`, I received the following error:

> NameError (uninitialized constant Google::Apis::PeopleV1::PeopleService):

due to this line in my code:

`client = Google::Apis::PeopleV1::PeopleService.new`

**Are there any changes how to initialize the API or is this a bug?**

**Comment by saicheems** [comment]
It seems the People API owners changed the canonical name of their API  to "People Service".

That's forced the Ruby code generator to produce `Google::Apis::PeopleV1::PeopleServiceService`.

That's a pretty unfortunate renaming... but please try replacing `PeopleService` with `PeopleServiceService`.

**Comment by hundsim** [comment]
Yes, that change solved the issue. Thanks a lot for the quick response!
