### ISSUE TITLE
cacerts.pem breaks ServerNameIndication for LetsEncrypt

### ISSUE THREAD

**Issue by maxfwerner** [google/google-api-ruby-client#577]
When using the cacerts.pem file from this gem as the `ENV['SSL_CERT_FILE']` (which is what many people who develop on Mac or Windows do to get SSL working, SNI will no longer work for the LetsEncrypt Certificates.

For instance in a Rails 4 app:

`config/initializers/some_initializer.rb`:
```
cert_path = Gem.loaded_specs['google-api-client'].full_gem_path+'/lib/cacerts.pem'
ENV['SSL_CERT_FILE'] = cert_path
```
which resolves to this (in my case I installed the gem to `vendor/bundle`):
"/home/user/appname/vendor/bundle/ruby/2.3.0/gems/google-api-client-0.11.1/lib/cacerts.pem"

After this trying to make HTTPS calls against certs provided by LetsEncrypt which require SNI (such as multiple ssl vhosts on one IP address) will throw this exception:

`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`

**Comment by sqrrrl** [comment]
The bundle included here is intended only for connected to Google APIs.
