### ISSUE TITLE
too much debug level logging, not enough info level

### ISSUE THREAD

**Issue by wlipa** [google/google-api-ruby-client#580]
Compared to the AWS sdk, the Google Cloud Platform ruby libraries are very verbose in their logging, for example including the entire inspection result of the API responses.  This is helpful information from time to time, but typically it is more useful to simply see what API calls are happening and whether or not they returned errors.

I tried setting the log level to info, and that essentially wiped out all information in the log.  I would like to suggest that there be a log level that includes high level call/response status but not the innermost details of every field in the response.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.

**Comment by julienbfabre** [comment]
how can i disable all that unnecessary logging in development env without changing the entire logging level of rails?
is there an option i can set? 

i looked through the code and tried the following but that doesnt seem to do anything:

```
client = AnalyticsReportingService.new
client.client_options.log_http_requests = false
```
