### ISSUE TITLE
append_spreadsheet_value not working

### ISSUE THREAD

**Issue by vipulkhullar** [google/google-api-ruby-client#581]
hi all
I am using v 0.9.9 and trying to use append metho but it gives the following error
NoMethodError: undefined method `append_spreadsheet_value' for #<Google::Apis::SheetsV4::SheetsService:0x0000000fcd61a8>

ruby version 2.0.0
rails version 3.2.1
 update_spreadsheet_value is working fine

CODE 

sheet_name = 'Sheet1'
range = "Sheet1!A1:Z1000"
request_body = Google::Apis::SheetsV4::ValueRange.new({
  major_dimension: "ROWS",
  values: [
     ["Item", "tt", "Stocked", "Ship Date"]
   ]
})

insert_data_option = 'INSERT_ROWS' 
**response = service.append_spreadsheet_value(spreadsheet_id, range, request_body, value_input_option: 'USER_ENTERED', insert_data_option: insert_data_option)**

**Comment by corey2** [comment]
I'm still getting this error
