### ISSUE TITLE
environment specific json

### ISSUE THREAD

**Issue by vipulkhullar** [google/google-api-ruby-client#582]
hi all ,
I am using version 0.9.26 and rails 3.2.1,ruby 2.0
is there any feature which allows to load path of json file specific to environment. 

ie ENV['GOOGLE_APPLICATION_CREDENTIALS'] = "path/to/file"[Rails.env]

as I want to have different keys for different environment
or some way to convert into yml files like this 

development:
  credentials same as json file
production:
  different credentials 
test:
  different credentials

**Comment by sqrrrl** [comment]
Not in this client, but you might be able to do what you're looking for with https://github.com/bkeepers/dotenv
