### ISSUE TITLE
get_spreadsheet_values removed?

### ISSUE THREAD

**Issue by bootstraponline** [google/google-api-ruby-client#588]
The sample references:
> result = sheets.get_spreadsheet_values(options[:spreadsheet_key], options[:range])

however that method no longer exists:

> NoMethodError: undefined method `get_spreadsheet_values' for #<Google::Apis::SheetsV4::SheetsService:0x007f89a6c8ae60>

It looks like the method is now called `get_spreadsheet_value`

**Comment by ravishwetha** [comment]
@bootstraponline Thanks! had no idea why a program that was running yesterday did not today when I set up on a new machine. Had to change it to get_spreadsheet_value

**Comment by saicheems** [comment]
This is my fault, and related to #590

I plan to release v0.13.0 to revert this to the past behavior (`get_spreadsheet_values`).

**Comment by bootstraponline** [comment]
> This library is in Alpha. We will make an effort to support the library, but we reserve the right to make incompatible changes when necessary.

the readme makes it clear there will be incompatible changes. I'm fine with stuff breaking. 😄

**Comment by saicheems** [comment]
Reverted in v0.13.0

Thanks for your understanding :)
