### ISSUE TITLE
Retry on transmission error?

### ISSUE THREAD

**Issue by bootstraponline** [google/google-api-ruby-client#589]
I'm seeing this error randomly:

```
 Google::Apis::TransmissionError:
       execution expired

     # --- Caused by: ---
     # HTTPClient::ReceiveTimeoutError:
     #   execution expired
```

It seems like the client should auto retry in this situation?

**Comment by gmoore** [comment]
`client.request_options.retries = 3`

see: https://github.com/google/google-api-ruby-client/issues/357#issuecomment-184236598

**Comment by bootstraponline** [comment]
Thanks. That should probably be set by default.
