### ISSUE TITLE
v0.12.0 breaks lots of compabilities

### ISSUE THREAD

**Issue by sonots** [google/google-api-ruby-client#590]
It seems v0.12.0 breaks lots of compatibilities although they are not written in CHANGELOG.

https://github.com/google/google-api-ruby-client/commit/3f26743ef728466c7f3edfe8dfb1224122c596b5

For example, `Google::Apis::ComputeV1::ComputeService` had `list_aggregated_instances` method before, but it was renamed to `aggregated_address_list`. 

I am not sure how they are auto generated, but I currently do not feel these incompatibility changes worth to be introduced.

Are there any chances to get them back?

**Comment by saicheems** [comment]
Ah... you're right, I see where I've messed up.

Thanks for making an issue, I'll get this fixed shortly and release v0.13.0

**Comment by saicheems** [comment]
Reverted in v0.13.0
