### ISSUE TITLE
Sending HTTP post https://www.googleapis.com/admin/directory/v1/users? 403

### ISSUE THREAD

**Issue by devhas** [google/google-api-ruby-client#591]
I am trying to create user accounts using service account. I have gone through multiple samples and combinations of code regarding how to properly achieve this but every attempt I make is rolledback with a 403 error.
```
service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.client_options.application_name = APPLICATION_NAME
scope =  'https://www.googleapis.com/auth/admin.directory.user'
authorization = Google::Auth::ServiceAccountCredentials.make_creds(
json_key_io: StringIO.new(File.read('service_account_file.json')), scope: scope)
authorization.fetch_access_token!
service.authorization = authorization
```

After this I create an object of user and assign it the required attributes and upon execution of the following line I face the hurdle which I have described in the title.

`result = service.insert_user(user_object)`

Following is the output I get in my console:
```
Sending HTTP post https://www.googleapis.com/admin/directory/v1/users?
403
#<Hurley::Response POST https://www.googleapis.com/admin/directory/v1/users == 403 (232 bytes) 1183ms>
Caught error forbidden: Not Authorized to access this resource/api
Error - #<Google::Apis::ClientError: forbidden: Not Authorized to access this resource/api>

```
I don't know what can I be doing wrong. Any help would really be appreciated, thanks.

**Comment by saicheems** [comment]
Hmm, I wasn't able to replicate...

Does your service account have the correct role? That would be my first guess.

Are you able to get a request through on APIs explorer?
https://apis-explorer.appspot.com/apis-explorer/#search/directory_v1/admin/directory_v1/directory.users.insert

**Comment by sqrrrl** [comment]
+1 to Sai's comment -- service accounts, acting as themselves, aren't domain members or admins. They have no permission to insert users.

You need to be operating as an authorized admin to create users. You *can* use a service account for that *if* you impersonate an actual admin. See [domain wide delegation](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) for more.
