### ISSUE TITLE
unknown keyword: snippet

### ISSUE THREAD

**Issue by HsuTimothy** [google/google-api-ruby-client#595]
Hey, I'm currently trying to do an insert_comment method call using the sample code. However, when I run my code I get hit with a `unknown keyword: snippet` with `.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/google-api-client-0.13.0/generated/google/apis/youtube_v3/service.rb:1211:in 'insert_comment'
`
```ruby
properties = {
	'snippet.parentId': '123',
	'snippet.textOriginal': 'hi'
}
resource = create_resource(properties)
response = service.insert_comment('snippet', resource)
```

Not sure if I'm doing it wrong or if this is an actual issue

**Comment by HsuTimothy** [comment]
However, I am able to successfully leave a comment when I do
```ruby
snippet = Google::Apis::YoutubeV3::CommentSnippet.new(parent_id: parent_id, text_original: message)
comment = Google::Apis::YoutubeV3::Comment.new(snippet: snippet)

response = service.insert_comment('snippet', comment)
```

**Comment by sqrrrl** [comment]
Running into a ruby quirk -- because you're passing a hash as the last param, it's trying to expand it to match the keyword args.

You can work around it by just adding an extra empty hash as the last parameter:

```ruby
response = service.insert_comment('snippet', resource, {})
```
