### ISSUE TITLE
[Batch Processing] Google::Apis::ClientError - Invalid request

### ISSUE THREAD

**Issue by marine1079** [google/google-api-ruby-client#603]
Does batch processing API changed recently?
------

1. I got 'Invalid request' error.

![image](https://user-images.githubusercontent.com/14011993/28493576-e8d6c394-6f53-11e7-883e-78784ee0412c.png)

2. It works fine without batch processing.

![image](https://user-images.githubusercontent.com/14011993/28493581-07807b46-6f54-11e7-924a-cb9c27271c01.png)

------
My batch processing codes worked fine even a few days ago.
Why does that error happen?
I can't figure out what's the problem.

Please help.
Thanks.

**Comment by DuBistKomisch** [comment]
Getting the same issue, my code's worked fine for months, and just stopped working a while ago. Removed the batch and it works.

**Comment by Mifrill** [comment]
I get this error when I specify `download_dest`
```
gdrive.get_file(file_id)
#<Google::Apis::DriveV3::File:0x00005560d19e91e8 @id="FILE_ID", @kind="drive#file", @mime_type="application/vnd.google-apps.spreadsheet", @name="MY_FILE_NAME>

gdrive.get_file(file_id, download_dest: '/tmp/my_file.xls')
*** Google::Apis::ClientError Exception: Invalid request
```
it's strange that with other files everything works correctly

I have rights to view and download that file:
```
SCOPE = Google::Apis::DriveV3::AUTH_DRIVE_READONLY
```
any ideas? thanks

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks @Mifrill! Please add a comment if you have any more questions and we can reopen this issue.

**Comment by DuBistKomisch** [comment]
@mattwhisenhunt I don't think @Mifrill's comment had anything to do with the original issue?

**Comment by mattwhisenhunt** [comment]
@DuBistKomisch are batch requests still coming back 404?

**Comment by DuBistKomisch** [comment]
Not sure, been working fine without batching, I'll try it out again this weekend.

**Comment by utkarshrai003** [comment]
I still am getting the `Google::Apis::ClientError: Invalid request` while specifying download_dest. If I don't specify download_dest, the file gets downloaded but its empty.

Any idea guys ?

**Comment by nduncan-cs130** [comment]
I'm having a similar issue with the gmail API

**Comment by Mifrill** [comment]
@nduncan-cs130 please try to use correct mime_type, you can compare with those:
https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

**Comment by nduncan-cs130** [comment]
@Mifrill My issue is a bit different than what's being discussed in this thread.

I'm using the Gmail API to batch the requests to fetch information about a list of emails. My code looks like this:
```
gmail_api.batch do |gmail|
        message_ids.each do |message_id|
          gmail.get_user_message("me", message_id, :format => "metadata")  do 
            [process message...]
          end
        end
      end
```
I'm non-deterministically getting the error message:
`Google::Apis::ClientError - Invalid request`

**Comment by Mifrill** [comment]
@nduncan-cs130 can you shed some light for this implementation, please?
(what is `gmail_api` and `text_answer`) in details

**Comment by syakovyn** [comment]
I have exactly the same issue @marine1079 described. When processing requests in a batch and one of them fails the error is returned to all the requests effectively drawing batching requests as a useless thing.
Performing the same requests one be one provides the expected behavior: only one with the wrong ID fails.
