### ISSUE TITLE
Rebooting a ChromeOS Device

### ISSUE THREAD

**Issue by craigsheen** [google/google-api-ruby-client#604]
After finally getting this API working to list and find the ChromeOS devices, I was surprised to not see the ability to reboot a device.

I know this can be achieved in the Google Admin CDM, but from time to time I need to reboot a number of devices and going through each device and rebooting is extremely time consuming. It would be great if I was able to do this via the API, so I could do it automatically based on versions etc.

I have tried searching everywhere but I can't seem to spot anything regarding this, so sorry if I have missed this somewhere.

Is this possible?
If not, will it ever be possible?

Thanks.

**Comment by sqrrrl** [comment]
Suggest asking at https://productforums.google.com/forum/#!forum/apps or contacting support. The API here is auto-generated and whether or not an API supports particularly functionality is up to the individual product teams.
