### ISSUE TITLE
Insert Live Broadcast ArgumentError

### ISSUE THREAD

**Issue by wuilkysb** [google/google-api-ruby-client#607]
I'm trying :

    <YT = Google::Apis::YoutubeV3
      youtube = YT::YouTubeService.new
      youtube.authorization = "my-authorization.json"

      metadata  = {
        snippet: {
          title: "test",
          scheduled_start_time: "2017-08-03T14:50:00.000Z"
        },
        status: {
          privacy_status: 'private'
        }
      }
      part = "snippet"

      youtube.insert_live_broadcast(part, metadata)>

But this gives me the error:

<ArgumentError (unknown keywords: snippet, status)>

Any idea?

**Comment by sqrrrl** [comment]
See the readme for warning about using hashes. This is a ruby quirk where hashes passed as the last parameter get expanded into keyword args.

You can work around it by adding an empty hash as a 3rd parameter.

**Comment by wuilkysb** [comment]
I've tried it too and it's not working for me.

youtube.insert_live_broadcast(part, metadata, {})

BTW i'm use Rails 5
