### ISSUE TITLE
Exporting specific tab of a Spreadsheet?

### ISSUE THREAD

**Issue by AlexGascon** [google/google-api-ruby-client#618]
I need to export a Spreadsheet to do some offline processing with it. I'm doing it with the `export_file` method of `Google::Apis::DriveV2::DriveService`, and while I can access it without any problem, I don't know if it's possible to export a specific tab instead of the default one. Is there any way to specify the `gid` parameter on that method? Or is there any other method in which I can specify it?

Thanks in advance for your help!

**Comment by bantini** [comment]
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo

Does this help?

**Comment by AlexGascon** [comment]
It's possible, I'll take a look at it. Thanks!

**Comment by bantini** [comment]
I am assuming the link solved your problem. I am closing this issue for now. Feel free to reopen it if you face any more problems.
