### ISSUE TITLE
documentation for 'copy_spreadsheet' method

### ISSUE THREAD

**Issue by architapatelis** [google/google-api-ruby-client#620]
@sqrrrl
Here is the link to the documentation for the `copy_spreadsheet` method : https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo

I think that, it would be easier for developers if the following line of code is added to that documentation:

```ruby
request_body.destination_spreadsheet_id = "PLACE_THE_ID_OF_THE_DESTINATION_SPREADSHEET_HERE"

```
The documentation only shows:
```ruby
request_body = Google::Apis::SheetsV4::CopySheetToAnotherSpreadsheetRequest.new
```
Which is helpful, but it's not obvious which `Instance Attribute` we have to set. In this case, you would have to look up the code [here]( https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/classes.rb) to determine that you have to setup `destination_spreadsheet_id` .  Once you have an instance attribute, you can then use 
```ruby
response = service.copy_spreadsheet(spreadsheet_id, sheet_id, request_body)
```

**Comment by bantini** [comment]
@architapatelis Thanks for the suggestion. However, since this is a documentation issue, can you submit via the 'Send Feedback' link on that page instead? Thanks!
