### ISSUE TITLE
UrlshortenerV1::UrlshortenerService Caught error required: Required

### ISSUE THREAD

**Issue by mattrothstein** [google/google-api-ruby-client#630]
I am unable to use the UrlShortener. Following this workflow.

I am able to instantiate the service and confirm the service object is successfully created. 

```ruby 
shortener_service = Google::Apis::UrlshortenerV1::UrlshortenerService.new
```

```ruby
#<Google::Apis::UrlshortenerV1::UrlshortenerService:0x007ff7c1748e28
 @base_path="urlshortener/v1/",
 @batch_path="batch/urlshortener/v1",
 @client_options=#<struct Google::Apis::ClientOptions application_name="unknown", application_version="0.0.0", proxy_url=nil, open_timeout_sec=nil, read_timeout_sec=nil, send_timeout_sec=nil, log_http_requests=false>,
 @request_options=#<struct Google::Apis::RequestOptions authorization=nil, retries=0, header=nil, normalize_unicode=false, skip_serialization=false, skip_deserialization=false, api_format_version=nil>,
 @root_url="https://www.googleapis.com/",
 @upload_path="upload/urlshortener/v1/">
```

Then I set the api key. 
```ruby 
shortener_service.key = ENV['GOOGLE_API_KEY']
```

This whole process seems to work fine, unless there is something wrong with the instantiated UrlShortnerService object. 

I use the following to create a short url.
```ruby 
shortener_service.insert_url('https://github.com/google/google-api-ruby-client')
``` 
And it generates the following request. The key is intentionally masked and the request is pasted as test to avoid no-wrap.

#<HTTP::Message:0x007ff7beab9268 @http_header=#
HTTP::Message::Headers:0x007ff7beab9218 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3ffbdf55cd58 URI:https://www.googleapis.com/urlshortener/v1/url?key=####################>, @request_query=nil, @request_absolute_uri=nil, @status_code=400, @reason_phrase="Bad Request", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Fri, 10 Nov 2017 14:43:28 GMT"], ["Expires", "Fri, 10 Nov 2017 14:43:28 GMT"], ["Cache-Control", "private, max-age=0"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x007ff7c1789838>, issuer=#<OpenSSL::X509::Name:0x007ff7c1789810>, serial=#<OpenSSL::BN:0x007ff7c17897e8>, not_before=2017-11-01 13:58:28 UTC, not_after=2018-01-24 13:31:00 UTC>, @http_body=#<HTTP::Message::Body:0x007ff7beab91a0 @body="{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"required\",\n    \"message\": \"Required\",\n    \"locationType\": \"parameter\",\n    \"location\": \"resource.longUrl\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"Required\"\n }\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>

The following is the error that I don't understand.
```
Caught error required: Required
Error - #<Google::Apis::ClientError: required: Required>

Google::Apis::ClientError: required: Required
from /Users/matt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/google-api-client-0.17.0/lib/google/apis/core/http_command.rb:218:in `check_status'
 ```

**Comment by bantini** [comment]
Try this:

```ruby
require 'google/apis/urlshortener_v1'
shortener_service = Google::Apis::UrlshortenerV1::UrlshortenerService.new
url = Google::Apis::UrlshortenerV1::Url.new
shortener_service.key = 'service_key'
url.long_url = "https://github.com/google/google-api-ruby-client"
response = shortener_service.insert_url(url)
puts response
```

**Comment by bantini** [comment]
Closing this issue assuming the response solved the problem. Feel free to reopen the issue if the problem persists.
