### ISSUE TITLE
Sheets V4 Missing UpdateValuesRequest

### ISSUE THREAD

**Issue by grant** [google/google-api-ruby-client#631]
Sheets V4 class `UpdateValueRequest` is missing (Non-batch). See [sheets_v4/representations](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/representations.rb).

i.e.
[BatchUpdateValuesRequest](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/representations.rb#L241)
[BatchUpdateValuesResponse](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/representations.rb#L247)

[UpdateValuesResponse](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/representations.rb#L1015)
UpdateValuesRequest?

CC @erickoledadevrel @sqrrrl

**Comment by erickoledadevrel** [comment]
I believe this is working as intended. As per the [reference docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update#request-body) the method uses a `ValueRange` type for the request body. Likewise, the Ruby client method [`update_spreadsheet_value`](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/sheets_v4/service.rb#L776) takes a `ValueRange` representation object.

**Comment by grant** [comment]
Thanks for the comment and help. You're right, used a `ValueRange`.
