### ISSUE TITLE
No publicLink returned for google slide published/published_outside_domain revision

### ISSUE THREAD

**Issue by MiluchOK** [google/google-api-ruby-client#635]
I am trying to publish a google slide revision and to get it's public link. 
Tried to do so with v3 and v2 APIs.

The v3 says that there is no field for public_link.
v2 simply gives me nil value.

I googled for days now and would appreciate help.

Thanks.
Alexey.

**Comment by bantini** [comment]
@MiluchOK Does the google slide api help?

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/slides_v1/service.rb

**Comment by bantini** [comment]
Since there has been no response for a week now, I am assuming the issue is resolved, and hence I am closing it for now. Feel free to reopen it if the problem persists.
