### ISSUE TITLE
Is it possible to disable Gzip decompression?

### ISSUE THREAD

**Issue by quartzmo** [google/google-api-ruby-client#636]
To resolve GoogleCloudPlatform/google-cloud-ruby#1835, we need to disable the Gzip decompression that is automatically performed by google-api-ruby-client. I believe it is enabled here in [base_service.rb#L403](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/base_service.rb#L403).

Is it currently possible to do this, or else can the library be updated to allow for this configuration to be modified?

/cc @blowmage @geigerj

**Comment by geigerj** [comment]
@bantini Could you please check into this and provide a work estimate if the library needs to be updated? It's possible to work around this downstream in the `google-cloud-ruby` client but a solution here would be better.

**Comment by bantini** [comment]
@quartzmo Can this issue be closed?

**Comment by quartzmo** [comment]
Yes, thank you!

**Comment by quartzmo** [comment]
@bantini When can we expect a release containing the change in #637?

**Comment by bantini** [comment]
@quartzmo Unfortunately, I am not aware of the release process. 
CC @geigerj @saicheems

**Comment by saicheems** [comment]
Released in 0.17.4

**Comment by quartzmo** [comment]
@saicheems Thank you!
