### ISSUE TITLE
GMB API Issue

### ISSUE THREAD

**Issue by johnharlan** [google/google-api-ruby-client#644]
Here is my code:
`@client = Google::APIClient.new(application_name: APPLICATION_NAME)`
`@client.authorization = auth_client`
`@api = @client.discovered_api('my-business', 'v3')`

And this is what I get back:
`Google::APIClient::Request Sending API request get https://www.googleapis.com/discovery/v1/apis/my-business/v3/rest {"User-Agent"=>"Reviews App/0.0.0 google-api-ruby-client/0.8.2 Mac OS X/10.13.1\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>""}
Decompressing gzip encoded response (120 bytes)
Decompressed (165 bytes)
Google::APIClient::Request Result: 404 {"vary"=>"Origin, X-Origin", "content-type"=>"application/json; charset=UTF-8", "date"=>"Wed, 03 Jan 2018 14:54:06 GMT", "expires"=>"Wed, 03 Jan 2018 14:54:06 GMT", "cache-control"=>"private, max-age=0", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "server"=>"GSE", "alt-svc"=>"hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\"", "connection"=>"close", "transfer-encoding"=>"chunked"}
Google::APIClient::ClientError: Not Found`

Any help here would be much appreciated.

**Comment by bantini** [comment]
Try 
```ruby
@api = @client.discovered_api('mybusiness', 'v3')
```

**Comment by johnharlan** [comment]
Thanks @bantini. I realized that I was using an older version of the gem that didn't include MyBusiness. I updated the gem and got it working.
