### ISSUE TITLE
Google::Apis::OS_VERSION includes new line on Linux

### ISSUE THREAD

**Issue by zstewar1** [google/google-api-ruby-client#645]
`Google::Apis::OS_VERSION` includes a newline on Linux.

https://github.com/google/google-api-ruby-client/blob/38e271cfb4532d61b857f624478108592288da06/lib/google/apis/version.rb#L33

This results in generating a user agent string which is not valid -- it inculdes the new line in the user agent string.
https://github.com/google/google-api-ruby-client/blob/b35f5face3649f25a4f24413b1fc9288f8bbe732/lib/google/apis/core/base_service.rb#L432

**Comment by ChauskinRodion** [comment]
Have prepared related PR https://github.com/google/google-api-ruby-client/pull/654

**Comment by mattwhisenhunt** [comment]
Fixed by #648
