### ISSUE TITLE
API server error The operation was successful, but there was an error preparing the response.

### ISSUE THREAD

**Issue by bonyii** [google/google-api-ruby-client#650]
HI we received this error from google do you have any idea what could cause this?
I contacted with google and they suggested that I should raise this issue here?

https://www.googleapis.com/drive/v3/files/

...

 @http_body=#<HTTP::Message::Body:0x000055c82f5074c0 @body="{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"responsePreparationFailure\",\n    \"message\": \"The operation was successful, but there was an error preparing the response.\"\n   }\n  ],\n  \"code\": 500,\n  \"message\": \"The operation was successful, but there was an error preparing the response.\"\n }\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
Caught error Server error
Error - #<Google::Apis::ServerError: Server error>

**Comment by bantini** [comment]
@bonyii Can you share the code that is causing this problem?

**Comment by bonyii** [comment]
Hi @bantini! 

Thanks for dealing with this issue. We are using https://github.com/gimite/google-drive-ruby gem which under the hood use your gem.

GoogleDrive invoke copy_file method
https://github.com/google/google-api-ruby-client/blob/808ddace3e4e381b06d9c23920684b98f3c1a8a1/generated/google/apis/drive_v3/service.rb#L549

like this

```
def copy(title)
      api_file = @session.drive.copy_file(id, { name: title }, fields: '*')
      @session.wrap_api_file(api_file)
 end
```
If we replace the fields: '*' keyword argument with {} it works fine though according this bug report it will miss out some attribute from the file https://github.com/gimite/google-drive-ruby/issues/256

**Comment by hirosmans** [comment]
Hey Hello!!!

I have the same error. This is the response that i got after exec from active job.
`
[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] Sending HTTP post https://www.googleapis.com/drive/v3/files/1xnSsWVxmgu7AT1dZsoWRtjRVkPlXR5CHm2jE1SRdEbI/copy?fields=%2A
[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] 500
[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] #<HTTP::Message:0x007fa2c401bf08 @http_header=#<HTTP::Message::Headers:0x007fa2c401bee0 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x63ab924 URI:https://www.googleapis.com/drive/v3/files/1xnSsWVxmgu7AT1dZsoWRtjRVkPlXR5CHm2jE1SRdEbI/copy?fields=%2A>, @request_query=nil, @request_absolute_uri=nil, @status_code=500, @reason_phrase="Internal Server Error", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Wed, 14 Feb 2018 19:29:34 GMT"], ["Expires", "Wed, 14 Feb 2018 19:29:34 GMT"], ["Cache-Control", "private, max-age=0"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x0000000c717508>, issuer=#<OpenSSL::X509::Name:0x0000000c717530>, serial=#<OpenSSL::BN:0x0000000c717558>, not_before=2018-01-23 13:53:01 UTC, not_after=2018-04-17 13:36:00 UTC>, @http_body=#<HTTP::Message::Body:0x007fa2c401be18 @body="{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"responsePreparationFailure\",\n    \"message\": \"The operation was successful, but there was an error preparing the response.\"\n   }\n  ],\n  \"code\": 500,\n  \"message\": \"The operation was successful, but there was an error preparing the response.\"\n }\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] Caught error Server error
[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] Error - #<Google::Apis::ServerError: Server error>

[ActiveJob] [SpreadsheetsJob] [d3e02106-510e-4919-afae-a5aa4117a1fe] Performed SpreadsheetsJob from Sidekiq(default) in 2806.16ms
Google::Apis::ServerError: Server error
from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:221:in `check_status'
`
i'm trying to create a new spreedsheet to my users and get the response error.
please help!!! 
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by hirosmans** [comment]
Hi @bantini how can I help you to resolve this issue?

**Comment by hirosmans** [comment]
Hello @bantini, now i'm doing some tests and it's working again!!!
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by bonyii** [comment]
I close it because of inactivity!
