### ISSUE TITLE
Suggest supported API method in README

### ISSUE THREAD

**Issue by xaviershay** [google/google-api-ruby-client#660]
Hello! The README says this alpha software and isn't really been supported.

What is your recommended supported option instead? Using the rest APIs directly? This would be a great thing to put into the README.

**Comment by xaviershay** [comment]
Also the samples don't appear to work anymore. Am trying to insert an event per https://github.com/google/google-api-ruby-client/blob/master/samples/cli/lib/samples/calendar.rb and get 'unknown keywords: summary, attendees, start, end'. The example at https://developers.google.com/calendar/v3/reference/events/insert#examples isn't even valid Ruby. Amending the brackets so that it is, it doesn't run with an error `Event.new` requires 0 parameters, not the 1 given.

By adding `puts` into the library code I've discovered that `lib/google/apis/core/api_command.rb#65` is problematic - the representation object it creates contains data that I pass to `insert_event` (as a hash with string keys - NOT symbols) but the `to_json` call returns and empty object `{}`.

Any help/suggestions/advice welcome, this is most frustrating.

**Comment by mattwhisenhunt** [comment]
For certain APIs we do suggest google-cloud libraries.
https://github.com/google/google-api-ruby-client#working-with-google-cloud-platform-apis

Try running
```sh
cd ../..
./google-api-samples calendar list --limit 16
````
https://github.com/google/google-api-ruby-client/blob/master/samples/cli/README.md

Thanks for the heads up about the reference page. Could add a comment to #587?

Have you seen [the migration guide](https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md)? Let me know any specific concerns that doesn't address.

I will have to look into the insert_event method and get back to you on that.

**Comment by mattwhisenhunt** [comment]
It looks like `insert_event` does a round trip to the server to get its results. You may have to specify fields to get back the data in the response you are looking for. https://developers.google.com/apis-explorer/#search/calendar/m/calendar/v3/calendar.events.insert has a handy fields editor with a complete list for this method.
