### ISSUE TITLE
500 Server Error When Exporting Large Files

### ISSUE THREAD

**Issue by zzlyn** [google/google-api-ruby-client#664]
When using ```service.export_file(id, 'application/pdf', download_dest: StringIO.new)```, I get a 500 server error if the generated pdf of the file is larger than about 10 MB (I can still manually download it from the page). 

![screen shot 2018-04-05 at 11 30 38 am](https://user-images.githubusercontent.com/20763405/38375718-ddf86604-38c4-11e8-8398-e0067c5143c0.png)

**Comment by mattwhisenhunt** [comment]
The exported content is limited to 10MB
https://developers.google.com/drive/v3/reference/files/export

**Comment by syakovyn** [comment]
I have the same issue when exporting to PDF. However, when exporting the same file using `service.export_file(id, 'application/rtf')` I'm getting 403 error with a reason: `exportSizeLimitExceeded`
According to https://developers.google.com/drive/api/v3/handle-errors#resolve_a_500_error_backend_error our service retries 500 errors.
Thus, the way export to PDF is handled creates a lot of unnecessary requests. Could the decision to close the ticket be rethought?
