### ISSUE TITLE
unable to use url shortener

### ISSUE THREAD

**Issue by chiwenchen** [google/google-api-ruby-client#665]
I have encounter an issue with the api to shorten url, the below document is the reference I take try to use the api.

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/urlshortener_v1/service.rb

can anyone demonstrate how to call the api step by step, many thanks.

here is my step trying to use it.

```
require 'google/apis/urlshortener_v1'
Urlshortener = Google::Apis::UrlshortenerV1
service = Urlshortener::UrlshortenerService.new
service.key = MY_API_KEY

# this not work
service.insert_url("www.longlongurl.com")

# this worked
service.get_url("https://goo.gl/3XoAL3")
```

**Comment by mattwhisenhunt** [comment]
This is due to a recent change made on the API side: https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html
