### ISSUE TITLE
Typo in ComputeV1::Network attributes

### ISSUE THREAD

**Issue by Temikus** [google/google-api-ruby-client#666]
It appears that there's a typo of in the network attributes, can you check:
https://github.com/google/google-api-ruby-client/blob/7757a2c7df8e8e001d8de63f146736512b1d6281/generated/google/apis/compute_v1/classes.rb#L11119
https://github.com/google/google-api-ruby-client/blob/7757a2c7df8e8e001d8de63f146736512b1d6281/generated/google/apis/compute_v1/classes.rb#L11092

**Comment by mattwhisenhunt** [comment]
Fixed by #669
