### ISSUE TITLE
Fetch total google user license?

### ISSUE THREAD

**Issue by sudovinh** [google/google-api-ruby-client#681]
Is there a way to fetch the total amount of google user licenses?

**Comment by mattwhisenhunt** [comment]
I don't understand your question. Please include which API or Google service you are working wanting to query. It almost always helps to include as much code as you have and what line is not working and what you expect it to be doing. Remember to clear out your credentials before you post it here though.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
