### ISSUE TITLE
Google::Apis::ClientError: insufficientPermissions: Insufficient Permission - :list_groups

### ISSUE THREAD

**Issue by the-codetrane** [google/google-api-ruby-client#683]
_version_: google-api-client (0.22.0)

_query:_ Sending HTTP get https://www.googleapis.com/admin/directory/v1/groups?userKey=<user_key>

_response_:

` 403
#<HTTP::Message:0x00007fe8b9852cb8 @http_header=#<HTTP::Message::Headers:0x00007fe8b9852c90 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x3ff45cc29d8c URI:https://www.googleapis.com/admin/directory/v1/customer/<domain>/domains?>, @request_query=nil, @request_absolute_uri=nil, @status_code=403, @reason_phrase="Forbidden", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["WWW-Authenticate", "Bearer realm=\"https://accounts.google.com/\", error=insufficient_scope, scope=\"https://www.googleapis.com/auth/admin.directory.domain.readonly\""], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Fri, 01 Jun 2018 15:10:14 GMT"], ["Expires", "Fri, 01 Jun 2018 15:10:14 GMT"], ["Cache-Control", "private, max-age=0"], ["X-Content-Type-Options", "nosniff"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], ["Server", "GSE"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"43,42,41,39,35\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x00007fe8b7f0bed0>, issuer=#<OpenSSL::X509::Name:0x00007fe8b7f0bea8>, serial=#<OpenSSL::BN:0x00007fe8b7f0be80>, not_before=2018-05-15 20:42:14 UTC, not_after=2018-08-07 19:53:00 UTC>, @http_body=#<HTTP::Message::Body:0x00007fe8b9852c18 @body="{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"insufficientPermissions\",\n    \"message\": \"Insufficient Permission\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Insufficient Permission\"\n }\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>`

_domain redacted_

I'm using the OAuth authorization, and `:list_users` works. Please advise. Thanks!

**Comment by mattwhisenhunt** [comment]
It looks like you are querying a group method with a domain scope. The scopes for list_groups are:
https://www.googleapis.com/auth/admin.directory.group
https://www.googleapis.com/auth/admin.directory.group.readonly

**Comment by the-codetrane** [comment]
I see. Thanks! Is there a method on the `Google::AdminDirectoryV1::DirectoryService` to set the scope, or is that done through the authentication?

**Comment by mattwhisenhunt** [comment]
That's right.
Your follow-up question prompted me to look at the way we do it in Ruby. It looks like we don't have scopes as a concept here. They seem to be very nicely abstracted behind the user_credentials_for function. TIL.

**Comment by the-codetrane** [comment]
I see, so if the scope for `:list_groups(user_key)` is incorrect, how do I fix it?

**Comment by the-codetrane** [comment]
![image](https://user-images.githubusercontent.com/12383156/40991314-6928e2fe-68c1-11e8-96b0-df279eb3ea1e.png)
![image](https://user-images.githubusercontent.com/12383156/40991331-7ba794b6-68c1-11e8-9a5b-aaa699a8e803.png)

I can't tell what I'm doing wrong; per the documentation I'm passing the appropriate params. Am I missing something?

**Comment by the-codetrane** [comment]
...and I'm an idiot. I had bad permissions locally. Thanks!!

**Comment by kcatstack** [comment]
@the-codetrane Hi, what do you meant you had bad permissions locally?
I'm having the same issue without knowing why. `list_users` works but not `list_groups`.
Thanks

**Comment by the-codetrane** [comment]
@kcatstack If I recall, I was passing the wrong API Token to the API. If `list_users` works, that might not be the case. Did you use the API Explorer on Google's site to verify you're passing the proper params?

**Comment by kcatstack** [comment]
My request is authorized domain-wide with a json file containing private key and other information as in this guide https://developers.google.com/admin-sdk/directory/v1/guides/delegation. So I think wrong token might not be problem.
My account doesn't have to permission to view organization's information so API Explorer is useless in my case.
Thanks anyway :)
