### ISSUE TITLE
Update file labels

### ISSUE THREAD

**Issue by tembaby** [google/google-api-ruby-client#687]
Hi,

I'm trying to use code like the following to locate file in Drive (V2) and update file labels:

files = drive.list_files(q: query,	page_token: page_token)
files.items.each do |file|
    # Code to match for file criteria
    # 
    # I tried several constructs like:

    # 1-
    file.labels.restricted = true
    drive.update_file(file.id, file)

    # 2-
    file.labels.update!(:restricted => true)
    drive.update_file(file.id, file)

    # 3-
    __f = Google::Apis::DriveV2::File.new(id: file.id)
    __f.labels = Google::Apis::DriveV2::File::Labels.new(restricted: true)
    drive.patch_file(file.id, __f)
end

Always fails with:
Traceback (most recent call last):
	19: from ./my-gdrive-helper.rb:479:in `<main>'
	18: from ./my-gdrive-helper.rb:176:in `find_directory'
	17: from ./my-gdrive-helper.rb:176:in `each'
	16: from ./my-gdrive-helper.rb:196:in `block in find_directory'
	15: from ./my-gdrive-helper.rb:233:in `apply_action'
	14: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/generated/google/apis/drive_v2/service.rb:1324:in `patch_file'
	13: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	12: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:93:in `execute'
	11: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	10: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	 9: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	 8: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:101:in `block in execute'
	 7: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	 6: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	 5: from /var/lib/gems/2.5.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	 4: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	 3: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:299:in `execute_once'
	 2: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:183:in `process_response'
	 1: from /var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/api_command.rb:116:in `check_status'
/var/lib/gems/2.5.0/gems/google-api-client-0.21.1/lib/google/apis/core/http_command.rb:218:in `check_status': badRequest: Bad Request (Google::Apis::ClientError)

My question is, what am I doing wrong? How to update File labels to change "restricted" to "true" programmatically?

Thanks,
Tamer

**Comment by tembaby** [comment]
I think I know the issue:
I was trying to run the above code to a directory not a file, from the Google Drive UI I cannot find "Prevent copy/download/printing" for directories (of course).  I tried the following code on file (mime_type != 'application/vnd.google-apps.folder') and it worked correctly:

		file.labels.restricted = true
		drive.patch_file(file.id, file)

Thank you.

**Comment by mattwhisenhunt** [comment]
Give us a holler if you need anything else.
