### ISSUE TITLE
Google::Apis::ClientOptions (Timeouts) can not be passed as an option

### ISSUE THREAD

**Issue by dosuken123** [google/google-api-ruby-client#689]
As the transition from 0.10 to 0.11, timeout settings (`open_timeout_sec`, `read_timeout_sec`, `send_timeout_sec`) were separated from `Google::Apis::RequestOptions`.

However, interfaces of `google/apis/storage_v1` only accepts `Google::Apis::RequestOptions` as the `option`. This means we can not set different timeouts in a single application.

As a workaround, we can tweak the global configuration for a specific target; e.g.

```
_tmp_default_timeout = ::Google::Apis::ClientOptions.default.send_timeout_sec
::Google::Apis::ClientOptions.default.send_timeout_sec = 1200 # Set a long timeout value

service.insert_bucket_access_control(...) # Upload a huge object

::Google::Apis::ClientOptions.default.send_timeout_sec = _tmp_default_timeout # Restore default
```

but there is a race condition, for example, another process can set `send_timeout_sec` before the `insert_bucket_access_control` invoked.

Ref:
- https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md#timeouts
- https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/19581

**Comment by mattwhisenhunt** [comment]
Why not create a new service with its own timeout to upload huge objects?

**Comment by dosuken123** [comment]
@mattwhisenhunt Ah, ok. It seems we only need a patch in fog-google side then. Thanks for headsup!

**Comment by dosuken123** [comment]
Created https://github.com/fog/fog-google/pull/375
