### ISSUE TITLE
No class CourseWorkChangesInfo for creating classroom registration for feed_type COURSE_WORK_CHANGES

### ISSUE THREAD

**Issue by rtcoms** [google/google-api-ruby-client#704]
For feed type COURSE_WORK_CHANGES, we need to pass additional info inform of CourseWorkChangesInfo, similar to what we do for COURSE_ROSTER_CHANGES. 

There is CourseRosterChangesInfo but not CourseWorkChangesInfo. 

This causes error while creating registration using method 

`Google::Apis::ClassroomV1::ClassroomService#create_registration`

**Comment by dazuma** [comment]
The automated update was stuck due to some upstream dependency issues, but this has been resolved. Sorry for the delay.
