### ISSUE TITLE
uninitialized constant Signet::RemoteServerError

### ISSUE THREAD

**Issue by blowmage** [google/google-api-ruby-client#708]
The PR #707 added `Signet::RemoteServerError` as a retrial error, but this constant can't be found and raises an error. This is because `Signet::RemoteServerError` requires `signet` 0.9.x. But the current dependency on `googleauth` pins this dependency to `~> 0.7`. So there is no way for this constant to resolve correctly, which is why it is raising. 

We probably need either to revert the change, test of the constant exists before attempting to rescue it, or cut a new release of `googleauth` with an updated dependency on `signet`.

Related issues:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/2353
https://github.com/fastlane/fastlane/issues/13198

**Comment by blowmage** [comment]
By adding `Signet::RemoteServerError` as a retrial error, google-api-client has effectively set a dependency on signet with a minimum version of 0.9.0. But the current dependency is inherited from googleauth, and set to `~> 0.7`, which is too low. So a simple fix here would be to specify what the true dependency on signet is by adding the following to the gemspec:

```ruby
spec.add_runtime_dependency 'signet', '~> 0.9'
```

**Comment by TheRoyalTnetennba** [comment]
This should be resolved as of 0.23.7
