### ISSUE TITLE
invalid_grant error

### ISSUE THREAD

**Issue by lessless** [google/google-api-ruby-client#84]
Hello! Today I've faced an invalid grant error, and as I'm doing a service application I'm confused because there should not be any  refresh tokens, only access tokens, right?  https://developers.google.com/accounts/docs/OAuth2ServiceAccount
```ruby
WARN -- : Google::APIClient - Please provide :application_name and :application_version when initializing the client
/home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/signet-0.4.5/lib/signet/oauth_2/client.rb:873:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error" : "invalid_grant"
}
	from /home/lessless/.rvm/gems/ruby-2.0.0-p247/gems/signet-0.4.5/lib/signet/oauth_2/client.rb:888:in `fetch_access_token!'
	from /home/lessless/projects/repaker/generator/_plugins/lib/google_client.rb:23:in `fetch_api_token!'
	from /home/lessless/projects/repaker/generator/_plugins/lib/google_client.rb:8:in `initialize'
```

here is my code

```ruby

  class GoogleClient
    attr_reader :credentials, :client
    
    def initialize(credentials)
      @credentials = credentials
      @client = Google::APIClient.new()
      fetch_api_token!
    end
    
    
    def fetch_api_token!
      # Load our credentials for the service account
      key = Google::APIClient::KeyUtils.load_from_pkcs12(credentials['key_file'], credentials['key_secret'])
      @client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer => credentials['service_account_email'],
        :signing_key => key)

      # Request a token for our service account
      @client.authorization.fetch_access_token!      
    end    
    
  end

```

also time is synced with ntp:  sudo ntpdate ntp.ubuntu.com
as https://developers.google.com/analytics/devguides/reporting/core/v2/gdataAuthentication suggests

**Comment by palfvin** [comment]
And yet another +1 here

**Comment by smarquezs** [comment]
I solve my issue running  ```udo ntpdate ntp.ubuntu.com```
And here is my code

```ruby
class GoogleClientService
  def initialize(scope, key_file)
    @scope    = scope
    @key_file = key_file
  end

  def get_access_token
    client = Google::APIClient.new(application_name: 'app_name')
    key    = Google::APIClient::KeyUtils.load_from_pkcs12(@key_file, 'notasecret')

    client.authorization = Signet::OAuth2::Client.new(
      token_credential_uri: ENV['TOKEN_URI'],
      audience:             ENV['TOKEN_URI'],
      scope:                @scope,
      issuer:               ENV['SERVICE_ACCOUNT_EMAIL'],
      signing_key:          key
    )

    client.authorization.fetch_access_token!
  end

end
```

**Comment by pacuna** [comment]
solution from @smarquezs solved the issue for me.

**Comment by thiagoxvo** [comment]
:+1: @smarquezs same solution here, thanks!!

**Comment by nasaabg** [comment]
@smarquezs same solutoin, good job!

**Comment by adityamajeti** [comment]
hi @smarquezs

i followed your code, but i am getting error  WARN: Authorization failed.  Server message: {"error" : "invalid_grant"}, plz help me!

    require "google/api_client"

    @account_email = "xxxxxxxxxxxxxxx@developer.gserviceaccount.com"
    @key_file = "pcskudos-xxxxxxxxx.p12"

    client = Google::APIClient.new(application_name: 'pcskudos')
    key    = Google::APIClient::KeyUtils.load_from_pkcs12(@key_file, 'notasecret')

    client.authorization = Signet::OAuth2::Client.new(
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      audience:             'https://accounts.google.com/o/oauth2/token',
      scope:                @scope,
      issuer:               @account_email,
      signing_key:          key
    )

client.authorization.fetch_access_token!
puts client.authorization.fetch_access_token

**Comment by nasaabg** [comment]
Have you tried to run `sudo ntpdate ntp.ubuntu.com` ?

**Comment by adityamajeti** [comment]
yes i tried

**Comment by adityamajeti** [comment]
I need to access spreadsheet which is drive of my mail. is any other process

**Comment by rafath** [comment]
I've spent 2,5 hours searching for solution, on localhost everything was fine, but on server it didn't work...
and after runing _sudo ntpdate ntp.ubuntu.com_ everything was fine... thanks

**Comment by omarojo** [comment]
What is this.. Im not using ubuntu. Im using MacOSX and also iOS in both platforms Im able to get new access tokens, using the refresh token. The problem is that after some hours.. specially after the access token expired, I try to get a new one... then I get the invalid_grant response. I dont know why it works perfectly.. but soon after the access_token expires... the refresh_token is not able to get more access_tokens.

**Comment by tvcam** [comment]
+1 for `sudo ntpdate ntp.ubuntu.com`

**Comment by jahrichie** [comment]
OS X running latest Ruby, is this dead?

**Comment by amrutjadhav** [comment]
I was suffering from same problem. But after resetting clock on my laptop, It worked.

**Comment by tacnoman** [comment]
I had this problem with Mac Os X. My date and time was wrong. I fixed this and the problem was solved.

**Comment by MohdAnas** [comment]
I am using this code 

`require 'google/api_client'

account_email = EMAIL_ADDRESS
key_file = PATH_OF_PRIVATEKEY.p12
key_secret = 'notasecret'
client = Google::APIClient.new

key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)

 client.authorization = Signet::OAuth2::Client.new(
   :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
   :audience => 'https://accounts.google.com/o/oauth2/token',
   :scope => 'https://www.googleapis.com/auth/content',
   :issuer => account_email,
   :signing_key => key)

 client.authorization.fetch_access_token!
 service = client.discovered_api('content', 'v2')`

I am able to get the access token but when I hit the reseller API for site verification I am getting the following error

`(byebug) site_verification = Google::Apis::SiteVerificationV1::SiteVerificationService.new
*** NameError Exception: uninitialized constant Google::Apis

nil
`

**Comment by sqrrrl** [comment]
@MohdAnas - Looks like you're mixing versions of the client library. The initial block is using the older 0.8.x version, the 2nd block looks like 0.9.x

**Comment by alexismansilla** [comment]
If your case is dinghy, you should restart proxy container 

`$ dinghy restart`
