### ISSUE TITLE
Support the Admin Settings API with two legged oauth

### ISSUE THREAD

**Issue by hadees** [google/google-api-ruby-client#91]
I'm writing an app for the [Google Marketplace](https://developers.google.com/google-apps/marketplace/) and have had trouble using the oauth keys with `two_legged_oauth_1` to access the [Admin Settings API](https://developers.google.com/admin-sdk/admin-settings/).  I know `google-api-ruby-client` doesn't explicitly support `GData` but I figure just passing it a `uri` should at least get me a valid response that I can parse myself right?

```ruby
client = Google::APIClient.new(application_name: 'Foobar', application_version: '0.0.1', authorization: :two_legged_oauth_1)
client.authorization.client_credential_key = ENV['GOOGLE_MARKETPLACE_KEY']
client.authorization.client_credential_secret = ENV['GOOGLE_MARKETPLACE_SECRET']
client.execute(uri: "https://apps-apis.google.com/a/feeds/domain/2.0/foobar.com/general/organizationName", "xoauth_requestor_id" => "hadees@foobar.com")
```

That produces an `Unknown authorization header` error.

I've even tried making the call with the api key and domain which I know the [Directory API](https://developers.google.com/admin-sdk/directory/) required.  I've had no problems using that api with my marketplace oauth keys.

I primarily need to use the Admin Settings API to get the organization name of the client installing my marketplace app.  If there is an easier way of getting that then I wouldn't need this.

**Comment by sqrrrl** [comment]
Marking as obsolete - oauth1 no longer supported by Google APIs.
